// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package execbehavior

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

type MarkedNode interface {
	IsMarkedNode()
	GetID() string
}

type ProbeUnion interface {
	IsProbeUnion()
}

type ArgObject struct {
	Echo *string `json:"echo,omitempty"`
	Ok   string  `json:"ok"`
}

type CheckedInput struct {
	Mode  string `json:"mode"`
	Value string `json:"value"`
}

type ChildProbe struct {
	Scalar    *string             `json:"scalar,omitempty"`
	EnumValue *ProbeEnum          `json:"enumValue,omitempty"`
	Union     ProbeUnion          `json:"union,omitempty"`
	Iface     MarkedNode          `json:"iface,omitempty"`
	Object    *ChildProbeObject   `json:"object,omitempty"`
	List      []*ChildProbeObject `json:"list,omitempty"`
}

type ChildProbeObject struct {
	ID     string  `json:"id"`
	Nested *string `json:"nested,omitempty"`
}

func (ChildProbeObject) IsProbeUnion() {}

type CoerceInput struct {
	Numbers []int         `json:"numbers,omitempty"`
	Items   []*CoerceItem `json:"items,omitempty"`
}

type CoerceItem struct {
	Value Strict `json:"value"`
}

type DeferItem struct {
	ID             int     `json:"id"`
	Slow           string  `json:"slow"`
	Failing        *string `json:"failing,omitempty"`
	NonNullFailing string  `json:"nonNullFailing"`
}

// An object with descriptions and deprecations.
type Described struct {
	// The current name.
	Name    string  `json:"name"`
	OldName *string `json:"oldName,omitempty"`
	Link    *string `json:"link,omitempty"`
}

type DescribedInput struct {
	// The name.
	Name    *string `json:"name,omitempty"`
	OldName *string `json:"oldName,omitempty"`
}

type ErrorProbe struct {
	Ok             string  `json:"ok"`
	Failing        *string `json:"failing,omitempty"`
	FailingNonNull string  `json:"failingNonNull"`
	WithExtensions *string `json:"withExtensions,omitempty"`
	Multiple       *string `json:"multiple,omitempty"`
	ValueAndError  *string `json:"valueAndError,omitempty"`
}

type LimitedItem struct {
	ID   int `json:"id"`
	Slow int `json:"slow"`
}

type MarkedChild struct {
	Value         *string    `json:"value,omitempty"`
	ResolvedValue *string    `json:"resolvedValue,omitempty"`
	Node          MarkedNode `json:"node,omitempty"`
	PlainNode     MarkedNode `json:"plainNode,omitempty"`
}

type MarkedLeaf struct {
	ID string `json:"id"`
}

func (MarkedLeaf) IsMarkedNode()      {}
func (this MarkedLeaf) GetID() string { return this.ID }

type MarkedParent struct {
	Name  *string      `json:"name,omitempty"`
	Child *MarkedChild `json:"child,omitempty"`
}

type Mutation struct {
}

type OmittableInput struct {
	Text  graphql.Omittable[*string]  `json:"text,omitempty"`
	Count graphql.Omittable[*int]     `json:"count,omitempty"`
	List  graphql.Omittable[[]string] `json:"list,omitempty"`
}

// Exactly one of the fields.
type OneOfInput struct {
	ByName *string `json:"byName,omitempty"`
	ByID   *string `json:"byId,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type Viewer struct {
	Name          string    `json:"name"`
	Query         *Query    `json:"query"`
	OptionalQuery *Query    `json:"optionalQuery,omitempty"`
	Mutation      *Mutation `json:"mutation,omitempty"`
}

type WrongTypeInput struct {
	Value *string `json:"value,omitempty"`
}

type WrongTypes struct {
	IntAsString          *string `json:"intAsString,omitempty"`
	NonNullIntAsString   string  `json:"nonNullIntAsString"`
	Marshaler            string  `json:"marshaler"`
	ReplacedByMiddleware *string `json:"replacedByMiddleware,omitempty"`
}

// How to format a name.
type NameFormat string

const (
	NameFormatFull  NameFormat = "FULL"
	NameFormatShort NameFormat = "SHORT"
)

var AllNameFormat = []NameFormat{
	NameFormatFull,
	NameFormatShort,
}

func (e NameFormat) IsValid() bool {
	switch e {
	case NameFormatFull, NameFormatShort:
		return true
	}
	return false
}

func (e NameFormat) String() string {
	return string(e)
}

func (e *NameFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NameFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NameFormat", str)
	}
	return nil
}

func (e NameFormat) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NameFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NameFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProbeEnum string

const (
	ProbeEnumA ProbeEnum = "A"
)

var AllProbeEnum = []ProbeEnum{
	ProbeEnumA,
}

func (e ProbeEnum) IsValid() bool {
	switch e {
	case ProbeEnumA:
		return true
	}
	return false
}

func (e ProbeEnum) String() string {
	return string(e)
}

func (e *ProbeEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProbeEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProbeEnum", str)
	}
	return nil
}

func (e ProbeEnum) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProbeEnum) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProbeEnum) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
