// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package execbehavior

import (
	"context"
)

type Stub struct {
	ArgObjectResolver struct {
		Echo func(ctx context.Context, obj *ArgObject, strict Strict) (*string, error)
	}
	DeferItemResolver struct {
		Slow           func(ctx context.Context, obj *DeferItem) (string, error)
		Failing        func(ctx context.Context, obj *DeferItem) (*string, error)
		NonNullFailing func(ctx context.Context, obj *DeferItem) (string, error)
	}
	ErrorProbeResolver struct {
		Failing        func(ctx context.Context, obj *ErrorProbe) (*string, error)
		FailingNonNull func(ctx context.Context, obj *ErrorProbe) (string, error)
		WithExtensions func(ctx context.Context, obj *ErrorProbe) (*string, error)
		Multiple       func(ctx context.Context, obj *ErrorProbe) (*string, error)
		ValueAndError  func(ctx context.Context, obj *ErrorProbe) (*string, error)
	}
	LimitedItemResolver struct {
		Slow func(ctx context.Context, obj *LimitedItem) (int, error)
	}
	MarkedChildResolver struct {
		ResolvedValue func(ctx context.Context, obj *MarkedChild) (*string, error)
		Node          func(ctx context.Context, obj *MarkedChild) (MarkedNode, error)
	}
	MutationResolver struct {
		Touch     func(ctx context.Context) (string, error)
		Panicking func(ctx context.Context) (*string, error)
		AppendLog func(ctx context.Context, entry string) ([]string, error)
	}
	QueryResolver struct {
		Ping             func(ctx context.Context) (string, error)
		Animals          func(ctx context.Context) ([]Animal, error)
		Pets             func(ctx context.Context) ([]Pet, error)
		StrangeAnimal    func(ctx context.Context, kind string) (Animal, error)
		ArgProbe         func(ctx context.Context, strict *Strict, withDefault *int, plain *string) (*string, error)
		ArgObject        func(ctx context.Context) (*ArgObject, error)
		DeferItem        func(ctx context.Context) (*DeferItem, error)
		DeferItems       func(ctx context.Context) ([]*DeferItem, error)
		ChildProbe       func(ctx context.Context) (*ChildProbe, error)
		Coerce           func(ctx context.Context, input *CoerceInput, numbers []int, nested [][]int) (*string, error)
		CheckedInput     func(ctx context.Context, input CheckedInput) (string, error)
		Described        func(ctx context.Context, input *DescribedInput, choice *OneOfInput) (*Described, error)
		MarkedParent     func(ctx context.Context) (*MarkedParent, error)
		Nullability      func(ctx context.Context, valid bool) (*Nullability, error)
		Panicking        func(ctx context.Context) (*string, error)
		PanickingNonNull func(ctx context.Context) (string, error)
		ErrorProbe       func(ctx context.Context) (*ErrorProbe, error)
		FailingRoot      func(ctx context.Context) (*string, error)
		Viewer           func(ctx context.Context) (*Viewer, error)
		ValueViewer      func(ctx context.Context) (*ValueViewer, error)
		LimitedItems     func(ctx context.Context, count int) ([]*LimitedItem, error)
		WrongTypes       func(ctx context.Context) (*WrongTypes, error)
		WrongTypeArg     func(ctx context.Context, value *string) (*string, error)
		WrongTypeInput   func(ctx context.Context, input WrongTypeInput) (*string, error)
	}
}

func (r *Stub) ArgObject() ArgObjectResolver {
	return &stubArgObject{r}
}
func (r *Stub) DeferItem() DeferItemResolver {
	return &stubDeferItem{r}
}
func (r *Stub) ErrorProbe() ErrorProbeResolver {
	return &stubErrorProbe{r}
}
func (r *Stub) LimitedItem() LimitedItemResolver {
	return &stubLimitedItem{r}
}
func (r *Stub) MarkedChild() MarkedChildResolver {
	return &stubMarkedChild{r}
}
func (r *Stub) Mutation() MutationResolver {
	return &stubMutation{r}
}
func (r *Stub) Query() QueryResolver {
	return &stubQuery{r}
}

type stubArgObject struct{ *Stub }

func (r *stubArgObject) Echo(ctx context.Context, obj *ArgObject, strict Strict) (*string, error) {
	return r.ArgObjectResolver.Echo(ctx, obj, strict)
}

type stubDeferItem struct{ *Stub }

func (r *stubDeferItem) Slow(ctx context.Context, obj *DeferItem) (string, error) {
	return r.DeferItemResolver.Slow(ctx, obj)
}
func (r *stubDeferItem) Failing(ctx context.Context, obj *DeferItem) (*string, error) {
	return r.DeferItemResolver.Failing(ctx, obj)
}
func (r *stubDeferItem) NonNullFailing(ctx context.Context, obj *DeferItem) (string, error) {
	return r.DeferItemResolver.NonNullFailing(ctx, obj)
}

type stubErrorProbe struct{ *Stub }

func (r *stubErrorProbe) Failing(ctx context.Context, obj *ErrorProbe) (*string, error) {
	return r.ErrorProbeResolver.Failing(ctx, obj)
}
func (r *stubErrorProbe) FailingNonNull(ctx context.Context, obj *ErrorProbe) (string, error) {
	return r.ErrorProbeResolver.FailingNonNull(ctx, obj)
}
func (r *stubErrorProbe) WithExtensions(ctx context.Context, obj *ErrorProbe) (*string, error) {
	return r.ErrorProbeResolver.WithExtensions(ctx, obj)
}
func (r *stubErrorProbe) Multiple(ctx context.Context, obj *ErrorProbe) (*string, error) {
	return r.ErrorProbeResolver.Multiple(ctx, obj)
}
func (r *stubErrorProbe) ValueAndError(ctx context.Context, obj *ErrorProbe) (*string, error) {
	return r.ErrorProbeResolver.ValueAndError(ctx, obj)
}

type stubLimitedItem struct{ *Stub }

func (r *stubLimitedItem) Slow(ctx context.Context, obj *LimitedItem) (int, error) {
	return r.LimitedItemResolver.Slow(ctx, obj)
}

type stubMarkedChild struct{ *Stub }

func (r *stubMarkedChild) ResolvedValue(ctx context.Context, obj *MarkedChild) (*string, error) {
	return r.MarkedChildResolver.ResolvedValue(ctx, obj)
}
func (r *stubMarkedChild) Node(ctx context.Context, obj *MarkedChild) (MarkedNode, error) {
	return r.MarkedChildResolver.Node(ctx, obj)
}

type stubMutation struct{ *Stub }

func (r *stubMutation) Touch(ctx context.Context) (string, error) {
	return r.MutationResolver.Touch(ctx)
}
func (r *stubMutation) Panicking(ctx context.Context) (*string, error) {
	return r.MutationResolver.Panicking(ctx)
}
func (r *stubMutation) AppendLog(ctx context.Context, entry string) ([]string, error) {
	return r.MutationResolver.AppendLog(ctx, entry)
}

type stubQuery struct{ *Stub }

func (r *stubQuery) Ping(ctx context.Context) (string, error) {
	return r.QueryResolver.Ping(ctx)
}
func (r *stubQuery) Animals(ctx context.Context) ([]Animal, error) {
	return r.QueryResolver.Animals(ctx)
}
func (r *stubQuery) Pets(ctx context.Context) ([]Pet, error) {
	return r.QueryResolver.Pets(ctx)
}
func (r *stubQuery) StrangeAnimal(ctx context.Context, kind string) (Animal, error) {
	return r.QueryResolver.StrangeAnimal(ctx, kind)
}
func (r *stubQuery) ArgProbe(ctx context.Context, strict *Strict, withDefault *int, plain *string) (*string, error) {
	return r.QueryResolver.ArgProbe(ctx, strict, withDefault, plain)
}
func (r *stubQuery) ArgObject(ctx context.Context) (*ArgObject, error) {
	return r.QueryResolver.ArgObject(ctx)
}
func (r *stubQuery) DeferItem(ctx context.Context) (*DeferItem, error) {
	return r.QueryResolver.DeferItem(ctx)
}
func (r *stubQuery) DeferItems(ctx context.Context) ([]*DeferItem, error) {
	return r.QueryResolver.DeferItems(ctx)
}
func (r *stubQuery) ChildProbe(ctx context.Context) (*ChildProbe, error) {
	return r.QueryResolver.ChildProbe(ctx)
}
func (r *stubQuery) Coerce(ctx context.Context, input *CoerceInput, numbers []int, nested [][]int) (*string, error) {
	return r.QueryResolver.Coerce(ctx, input, numbers, nested)
}
func (r *stubQuery) CheckedInput(ctx context.Context, input CheckedInput) (string, error) {
	return r.QueryResolver.CheckedInput(ctx, input)
}
func (r *stubQuery) Described(ctx context.Context, input *DescribedInput, choice *OneOfInput) (*Described, error) {
	return r.QueryResolver.Described(ctx, input, choice)
}
func (r *stubQuery) MarkedParent(ctx context.Context) (*MarkedParent, error) {
	return r.QueryResolver.MarkedParent(ctx)
}
func (r *stubQuery) Nullability(ctx context.Context, valid bool) (*Nullability, error) {
	return r.QueryResolver.Nullability(ctx, valid)
}
func (r *stubQuery) Panicking(ctx context.Context) (*string, error) {
	return r.QueryResolver.Panicking(ctx)
}
func (r *stubQuery) PanickingNonNull(ctx context.Context) (string, error) {
	return r.QueryResolver.PanickingNonNull(ctx)
}
func (r *stubQuery) ErrorProbe(ctx context.Context) (*ErrorProbe, error) {
	return r.QueryResolver.ErrorProbe(ctx)
}
func (r *stubQuery) FailingRoot(ctx context.Context) (*string, error) {
	return r.QueryResolver.FailingRoot(ctx)
}
func (r *stubQuery) Viewer(ctx context.Context) (*Viewer, error) {
	return r.QueryResolver.Viewer(ctx)
}
func (r *stubQuery) ValueViewer(ctx context.Context) (*ValueViewer, error) {
	return r.QueryResolver.ValueViewer(ctx)
}
func (r *stubQuery) LimitedItems(ctx context.Context, count int) ([]*LimitedItem, error) {
	return r.QueryResolver.LimitedItems(ctx, count)
}
func (r *stubQuery) WrongTypes(ctx context.Context) (*WrongTypes, error) {
	return r.QueryResolver.WrongTypes(ctx)
}
func (r *stubQuery) WrongTypeArg(ctx context.Context, value *string) (*string, error) {
	return r.QueryResolver.WrongTypeArg(ctx, value)
}
func (r *stubQuery) WrongTypeInput(ctx context.Context, input WrongTypeInput) (*string, error) {
	return r.QueryResolver.WrongTypeInput(ctx, input)
}
