//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package valuetypes

import (
	"bytes"
	"context"
	"embed"
	"fmt"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/99designs/gqlgen/graphql/introspection"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ***************************** api!.gotpl *****************************

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{SchemaData: cfg.Schema, Resolvers: cfg.Resolvers, Directives: cfg.Directives, ComplexityRoot: cfg.Complexity}
}

type Config = graphql.Config[ResolverRoot, DirectiveRoot, ComplexityRoot]

type ResolverRoot interface {
	Query() QueryResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
}

// endregion ***************************** api!.gotpl *****************************

// region    ************************** generated!.gotpl **************************

type QueryResolver interface {
	Items(ctx context.Context) ([]Item, error)
	Item(ctx context.Context, name string) (*Item, error)
	ItemValue(ctx context.Context, name string) (Item, error)
	Echo(ctx context.Context, input []ItemInput) ([]Item, error)
	Levels(ctx context.Context, in []Level) ([]Level, error)
}

// endregion ************************** generated!.gotpl **************************

// region    ************************** internal!.gotpl ***************************

type executableSchema graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot]

func (e *executableSchema) Schema() *ast.Schema {
	if e.SchemaData != nil {
		return e.SchemaData
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := newExecutionContext(nil, e, nil)
	_ = ec
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := newExecutionContext(opCtx, e, make(chan graphql.DeferredResult))
	inputUnmarshalers := func() *graphql.InputUnmarshalerIndex {
		return graphql.NewInputUnmarshalerIndex(
			graphql.NewInputUnmarshaler("ItemInput", graphql.BindUnmarshaler(ec, exec.InputFunc[*executionContext, ItemInput](&inputItemInput))),
		)
	}
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithLazyInputUnmarshalerIndex(ctx, inputUnmarshalers)
				data = objectQuery.Marshal(ctx, ec, opCtx.Operation.SelectionSet, nil)
			} else {
				if atomic.LoadInt32(&ec.PendingDeferred) > 0 {
					result := <-ec.DeferredResults
					atomic.AddInt32(&ec.PendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.Deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.PendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.ExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot]
}

func newExecutionContext(
	opCtx *graphql.OperationContext,
	execSchema *executableSchema,
	deferredResults chan graphql.DeferredResult,
) *executionContext {
	return &executionContext{
		ExecutionContextState: graphql.NewExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot](
			opCtx,
			(*graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot])(execSchema),
			parsedSchema,
			deferredResults,
		),
	}
}

//go:embed "schema.graphql"
var sourcesFS embed.FS

func sourceData(filename string) string {
	data, err := sourcesFS.ReadFile(filename)
	if err != nil {
		panic(fmt.Sprintf("codegen problem: %s not available", filename))
	}
	return string(data)
}

var sources = []*ast.Source{
	{Name: "schema.graphql", Input: sourceData("schema.graphql"), BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)

// childFields_* functions provide shared child field context lookups.
// Each function is generated once per unique object type, deduplicating the
// switch statements that were previously inlined in every fieldContext_* function.
var outMarshalNBoolean2bool = exec.OutOf(marshalNBoolean2bool)
var outMarshalNItem2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItem = exec.OutOf(marshalNItem2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItem)
var outMarshalNItem2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItemᚄ = exec.OutOf(marshalNItem2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItemᚄ)
var outMarshalNLevel2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel = exec.OutOf(marshalNLevel2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel)
var outMarshalNLevel2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelᚄ = exec.OutOf(marshalNLevel2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelᚄ)
var outMarshalNOwner2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐOwner = exec.OutOf(marshalNOwner2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐOwner)
var outMarshalNString2string = exec.OutOf(marshalNString2string)
var outMarshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ = exec.OutOf(marshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ)
var outMarshalN__DirectiveLocation2ᚕstringᚄ = exec.OutOf(marshalN__DirectiveLocation2ᚕstringᚄ)
var outMarshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.OutOf(marshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ)
var outMarshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.OutOf(marshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ)
var outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.OutOf(marshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType)
var outMarshalN__TypeKind2string = exec.OutOf(marshalN__TypeKind2string)
var outMarshalOBoolean2bool = exec.OutOf(marshalOBoolean2bool)
var outMarshalOItem2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItem = exec.OutOf(marshalOItem2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItem)
var outMarshalOOwner2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐOwner = exec.OutOf(marshalOOwner2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐOwner)
var outMarshalOString2ᚕstringᚄ = exec.OutOf(marshalOString2ᚕstringᚄ)
var outMarshalOString2ᚖstring = exec.OutOf(marshalOString2ᚖstring)
var outMarshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ = exec.OutOf(marshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ)
var outMarshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ = exec.OutOf(marshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ)
var outMarshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.OutOf(marshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ)
var outMarshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema = exec.OutOf(marshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema)
var outMarshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.OutOf(marshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ)
var outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.OutOf(marshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType)
var inUnmarshalNItemInput2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItemInputᚄ = exec.InOf(unmarshalNItemInput2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItemInputᚄ)
var inUnmarshalNLevel2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelᚄ = exec.InOf(unmarshalNLevel2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelᚄ)
var inUnmarshalNString2string = exec.InOf(unmarshalNString2string)
var inUnmarshalOBoolean2bool = exec.InOf(unmarshalOBoolean2bool)
var inUnmarshalOBoolean2ᚖbool = exec.InOf(unmarshalOBoolean2ᚖbool)
var inUnmarshalOLevel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel = exec.InOf(unmarshalOLevel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel)
var inUnmarshalOString2ᚕstringᚄ = exec.InOf(unmarshalOString2ᚕstringᚄ)
var inUnmarshalOString2ᚖstring = exec.InOf(unmarshalOString2ᚖstring)

// endregion ************************** internal!.gotpl ***************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

var inputItemInput = exec.Input[*executionContext]{Name: "ItemInput", GoType: "ItemInput"}

func init() {
	inputItemInput.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "name"}, inUnmarshalNString2string, func(it *ItemInput, v string) { it.Name = v }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "note"}, inUnmarshalOString2ᚖstring, func(it *ItemInput, v *string) { it.Note = v }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "level", Default: "LOW"}, inUnmarshalOLevel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel, func(it *ItemInput, v *Level) { it.Level = v }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "tags"}, inUnmarshalOString2ᚕstringᚄ, func(it *ItemInput, v []string) { it.Tags = v }),
	}
}

// UnmarshalItemInput unmarshals raw into the ItemInput input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalItemInput(ctx context.Context, raw any) (ItemInput, error) {
	var out ItemInput
	err := graphql.UnmarshalNamedInputFromContext(ctx, "ItemInput", raw, &out)
	return out, err
}

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectItem = exec.Object[*executionContext]{Name: "Item", Implementors: []string{"Item"}}

func init() {
	objectItem.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *Item) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "note", Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *Item) *string { return obj.Note }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "level", NonNull: true, Leaf: "Level"}, outMarshalNLevel2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel, func(obj *Item) Level { return obj.Level }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "levels", NonNull: true, Leaf: "Level"}, outMarshalNLevel2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelᚄ, func(obj *Item) []Level { return obj.Levels }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "tags", Leaf: "String"}, outMarshalOString2ᚕstringᚄ, func(obj *Item) []string { return obj.Tags }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "child", Children: &objectItem}, outMarshalOItem2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItem, func(obj *Item) *Item { return obj.Child }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "owner", Children: &objectOwner}, outMarshalOOwner2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐOwner, func(obj *Item) *Owner { return obj.Owner }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "mainOwner", NonNull: true, Children: &objectOwner}, outMarshalNOwner2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐOwner, func(obj *Item) Owner { return obj.MainOwner }),
	})
}

var objectOwner = exec.Object[*executionContext]{Name: "Owner", Implementors: []string{"Owner"}}

func init() {
	objectOwner.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *Owner) string { return obj.Name }),
	})
}

var objectQuery = exec.Object[*executionContext]{Name: "Query", Implementors: []string{"Query"}, Root: true}

func init() {
	objectQuery.Init([]exec.Field[*executionContext]{
		{Name: "items", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectItem, Out: outMarshalNItem2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItemᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Items(ctx)
		}},
		{Name: "item", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectItem, Args: []exec.Arg[*executionContext]{
			{Name: "name", Type: inUnmarshalNString2string.In},
		}, Out: outMarshalOItem2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItem.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Item(ctx, args["name"].(string))
		}},
		{Name: "itemValue", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectItem, Args: []exec.Arg[*executionContext]{
			{Name: "name", Type: inUnmarshalNString2string.In},
		}, Out: outMarshalNItem2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItem.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().ItemValue(ctx, args["name"].(string))
		}},
		{Name: "echo", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectItem, Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalNItemInput2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItemInputᚄ.In},
		}, Out: outMarshalNItem2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItemᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Echo(ctx, args["input"].([]ItemInput))
		}},
		{Name: "levels", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Level", Args: []exec.Arg[*executionContext]{
			{Name: "in", Type: inUnmarshalNLevel2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelᚄ.In},
		}, Out: outMarshalNLevel2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Levels(ctx, args["in"].([]Level))
		}},
		{Name: "__type", IsMethod: true, Children: &object__Type, Args: []exec.Arg[*executionContext]{
			{Name: "name", Type: inUnmarshalNString2string.In},
		}, Out: outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.IntrospectType(args["name"].(string))
		}},
		{Name: "__schema", IsMethod: true, Children: &object__Schema, Out: outMarshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.IntrospectSchema()
		}},
	})
}

var object__Directive = exec.Object[*executionContext]{Name: "__Directive", Implementors: []string{"__Directive"}}

func init() {
	object__Directive.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.Directive) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Directive) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isRepeatable", NonNull: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.Directive) bool { return obj.IsRepeatable }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "locations", NonNull: true, Leaf: "__DirectiveLocation"}, outMarshalN__DirectiveLocation2ᚕstringᚄ, func(obj *introspection.Directive) []string { return obj.Locations }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "args", NonNull: true, Children: &object__InputValue, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2ᚖbool.In},
		}}, outMarshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ, func(obj *introspection.Directive) []introspection.InputValue { return obj.Args }),
	})
}

var object__EnumValue = exec.Object[*executionContext]{Name: "__EnumValue", Implementors: []string{"__EnumValue"}}

func init() {
	object__EnumValue.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.EnumValue) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.EnumValue) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isDeprecated", NonNull: true, IsMethod: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.EnumValue) bool { return obj.IsDeprecated() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "deprecationReason", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.EnumValue) *string { return obj.DeprecationReason() }),
	})
}

var object__Field = exec.Object[*executionContext]{Name: "__Field", Implementors: []string{"__Field"}}

func init() {
	object__Field.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.Field) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Field) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "args", NonNull: true, Children: &object__InputValue, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2ᚖbool.In},
		}}, outMarshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ, func(obj *introspection.Field) []introspection.InputValue { return obj.Args }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "type", NonNull: true, Children: &object__Type}, outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Field) *introspection.Type { return obj.Type }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isDeprecated", NonNull: true, IsMethod: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.Field) bool { return obj.IsDeprecated() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "deprecationReason", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Field) *string { return obj.DeprecationReason() }),
	})
}

var object__InputValue = exec.Object[*executionContext]{Name: "__InputValue", Implementors: []string{"__InputValue"}}

func init() {
	object__InputValue.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.InputValue) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.InputValue) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "type", NonNull: true, Children: &object__Type}, outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.InputValue) *introspection.Type { return obj.Type }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "defaultValue", Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.InputValue) *string { return obj.DefaultValue }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isDeprecated", NonNull: true, IsMethod: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.InputValue) bool { return obj.IsDeprecated() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "deprecationReason", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.InputValue) *string { return obj.DeprecationReason() }),
	})
}

var object__Schema = exec.Object[*executionContext]{Name: "__Schema", Implementors: []string{"__Schema"}}

func init() {
	object__Schema.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Schema) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "types", NonNull: true, IsMethod: true, Children: &object__Type}, outMarshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ, func(obj *introspection.Schema) []introspection.Type { return obj.Types() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "queryType", NonNull: true, IsMethod: true, Children: &object__Type}, outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Schema) *introspection.Type { return obj.QueryType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "mutationType", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Schema) *introspection.Type { return obj.MutationType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "subscriptionType", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Schema) *introspection.Type { return obj.SubscriptionType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "directives", NonNull: true, IsMethod: true, Children: &object__Directive}, outMarshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ, func(obj *introspection.Schema) []introspection.Directive { return obj.Directives() }),
	})
}

var object__Type = exec.Object[*executionContext]{Name: "__Type", Implementors: []string{"__Type"}}

func init() {
	object__Type.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "kind", NonNull: true, IsMethod: true, Leaf: "__TypeKind"}, outMarshalN__TypeKind2string, func(obj *introspection.Type) string { return obj.Kind() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Type) *string { return obj.Name() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Type) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "specifiedByURL", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Type) *string { return obj.SpecifiedByURL() }),
		{Name: "fields", IsMethod: true, Children: &object__Field, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2bool.In},
		}, Out: outMarshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return obj.(*introspection.Type).Fields(args["includeDeprecated"].(bool)), nil
		}},
		exec.FieldGet(exec.Field[*executionContext]{Name: "interfaces", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ, func(obj *introspection.Type) []introspection.Type { return obj.Interfaces() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "possibleTypes", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ, func(obj *introspection.Type) []introspection.Type { return obj.PossibleTypes() }),
		{Name: "enumValues", IsMethod: true, Children: &object__EnumValue, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2bool.In},
		}, Out: outMarshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return obj.(*introspection.Type).EnumValues(args["includeDeprecated"].(bool)), nil
		}},
		exec.FieldGet(exec.Field[*executionContext]{Name: "inputFields", IsMethod: true, Children: &object__InputValue}, outMarshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ, func(obj *introspection.Type) []introspection.InputValue { return obj.InputFields() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "ofType", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Type) *introspection.Type { return obj.OfType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isOneOf", IsMethod: true, Leaf: "Boolean"}, outMarshalOBoolean2bool, func(obj *introspection.Type) bool { return obj.IsOneOf() }),
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var unmarshalNBoolean2bool = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalBoolean)

var marshalNBoolean2bool = exec.MarshalFunc[*executionContext](true, graphql.MarshalBoolean)

var marshalNItem2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItem = exec.MarshalObject[*executionContext, Item](&objectItem)

var marshalNItem2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItemᚄ = exec.MarshalList(marshalNItem2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItem, exec.ListOptions{ElemNonNull: true})

var unmarshalNItemInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItemInput = exec.UnmarshalInput[*executionContext, ItemInput](&inputItemInput)

var unmarshalNItemInput2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItemInputᚄ = exec.UnmarshalList(false, unmarshalNItemInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItemInput)

func unmarshalNLevel2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel(ctx context.Context, ec *executionContext, v any) (Level, error) {
	tmp, err := graphql.UnmarshalString(v)
	res := unmarshalNLevel2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelF[tmp]
	return res, graphql.ErrorOnPath(ctx, err)
}

func marshalNLevel2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel(ctx context.Context, ec *executionContext, sel ast.SelectionSet, v Level) graphql.Marshaler {
	_ = sel
	res := graphql.MarshalString(marshalNLevel2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelF[v])
	if res == graphql.Null {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
	}
	return res
}

var (
	unmarshalNLevel2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelF = map[string]Level{
		"LOW":  LevelLow,
		"HIGH": LevelHigh,
	}
	marshalNLevel2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelF = map[Level]string{
		LevelLow:  "LOW",
		LevelHigh: "HIGH",
	}
)

func unmarshalNLevel2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelᚄ(ctx context.Context, ec *executionContext, v any) ([]Level, error) {
	vSlice := graphql.CoerceList(v)
	var err error
	res := make([]Level, len(vSlice))
	for i := range vSlice {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithIndex(i))
		res[i], err = unmarshalNLevel2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel(ctx, ec, vSlice[i])
		if err != nil {
			return nil, err
		}
	}
	return res, nil
}

func marshalNLevel2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelᚄ(ctx context.Context, ec *executionContext, sel ast.SelectionSet, v []Level) graphql.Marshaler {
	ret := graphql.MarshalSliceConcurrently(ctx, len(v), 0, false, func(ctx context.Context, i int) graphql.Marshaler {
		fc := graphql.GetFieldContext(ctx)
		fc.Result = &v[i]
		return marshalNLevel2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel(ctx, ec, sel, v[i])
	})

	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}

	return ret
}

var marshalNOwner2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐOwner = exec.MarshalObject[*executionContext, Owner](&objectOwner)

var unmarshalNString2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalNString2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalString)

var marshalN__Directive2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirective = exec.MarshalObject[*executionContext, introspection.Directive](&object__Directive)

var marshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ = exec.MarshalList(marshalN__Directive2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirective, exec.ListOptions{ElemNonNull: true})

var unmarshalN__DirectiveLocation2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalN__DirectiveLocation2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalString)

var unmarshalN__DirectiveLocation2ᚕstringᚄ = exec.UnmarshalList(false, unmarshalN__DirectiveLocation2string)

var marshalN__DirectiveLocation2ᚕstringᚄ = exec.MarshalList(marshalN__DirectiveLocation2string, exec.ListOptions{ElemNonNull: true})

var marshalN__EnumValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValue = exec.MarshalObject[*executionContext, introspection.EnumValue](&object__EnumValue)

var marshalN__Field2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐField = exec.MarshalObject[*executionContext, introspection.Field](&object__Field)

var marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue = exec.MarshalObject[*executionContext, introspection.InputValue](&object__InputValue)

var marshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.MarshalList(marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue, exec.ListOptions{ElemNonNull: true})

var marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.MarshalObject[*executionContext, introspection.Type](&object__Type)

var marshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.MarshalList(marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, exec.ListOptions{ElemNonNull: true})

var marshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.MarshalObjectPtr[*executionContext, introspection.Type](true, &object__Type)

var unmarshalN__TypeKind2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalN__TypeKind2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalString)

var unmarshalOBoolean2bool = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalBoolean)

var marshalOBoolean2bool = exec.MarshalFunc[*executionContext](false, graphql.MarshalBoolean)

var unmarshalOBoolean2ᚖbool = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalBoolean)

var marshalOBoolean2ᚖbool = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalBoolean)

var marshalOItem2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐItem = exec.MarshalObjectPtr[*executionContext, Item](false, &objectItem)

func unmarshalOLevel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel(ctx context.Context, ec *executionContext, v any) (*Level, error) {
	if v == nil {
		return nil, nil
	}
	tmp, err := graphql.UnmarshalString(v)
	res := unmarshalOLevel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelF[tmp]
	return &res, graphql.ErrorOnPath(ctx, err)
}

func marshalOLevel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevel(ctx context.Context, ec *executionContext, sel ast.SelectionSet, v *Level) graphql.Marshaler {
	if v == nil {
		return graphql.Null
	}
	_ = sel
	_ = ctx
	res := graphql.MarshalString(marshalOLevel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelF[*v])
	return res
}

var (
	unmarshalOLevel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelF = map[string]Level{
		"LOW":  LevelLow,
		"HIGH": LevelHigh,
	}
	marshalOLevel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐLevelF = map[Level]string{
		LevelLow:  "LOW",
		LevelHigh: "HIGH",
	}
)

var marshalOOwner2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋexecbehaviorᚋvaluetypesᚐOwner = exec.MarshalObjectPtr[*executionContext, Owner](false, &objectOwner)

var unmarshalOString2ᚕstringᚄ = exec.UnmarshalList(true, unmarshalNString2string)

var marshalOString2ᚕstringᚄ = exec.MarshalList(marshalNString2string, exec.ListOptions{Nullable: true, ElemNonNull: true, Leaf: true})

var unmarshalOString2ᚖstring = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalString)

var marshalOString2ᚖstring = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalString)

var marshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ = exec.MarshalList(marshalN__EnumValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValue, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ = exec.MarshalList(marshalN__Field2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐField, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.MarshalList(marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema = exec.MarshalObjectPtr[*executionContext, introspection.Schema](false, &object__Schema)

var marshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.MarshalList(marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.MarshalObjectPtr[*executionContext, introspection.Type](false, &object__Type)

// endregion ***************************** type.gotpl *****************************
