// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package valuetypes

type Item struct {
	Name      string   `json:"name"`
	Note      *string  `json:"note,omitempty"`
	Level     Level    `json:"level"`
	Levels    []Level  `json:"levels"`
	Tags      []string `json:"tags,omitempty"`
	Child     *Item    `json:"child,omitempty"`
	Owner     *Owner   `json:"owner,omitempty"`
	MainOwner Owner    `json:"mainOwner"`
}

type ItemInput struct {
	Name  string   `json:"name"`
	Note  *string  `json:"note,omitempty"`
	Level *Level   `json:"level,omitempty"`
	Tags  []string `json:"tags,omitempty"`
}

type Owner struct {
	Name string `json:"name"`
}

type Query struct {
}
