// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package valuetypes

import (
	"context"
)

type Stub struct {
	QueryResolver struct {
		Items     func(ctx context.Context) ([]Item, error)
		Item      func(ctx context.Context, name string) (*Item, error)
		ItemValue func(ctx context.Context, name string) (Item, error)
		Echo      func(ctx context.Context, input []ItemInput) ([]Item, error)
		Levels    func(ctx context.Context, in []Level) ([]Level, error)
	}
}

func (r *Stub) Query() QueryResolver {
	return &stubQuery{r}
}

type stubQuery struct{ *Stub }

func (r *stubQuery) Items(ctx context.Context) ([]Item, error) {
	return r.QueryResolver.Items(ctx)
}
func (r *stubQuery) Item(ctx context.Context, name string) (*Item, error) {
	return r.QueryResolver.Item(ctx, name)
}
func (r *stubQuery) ItemValue(ctx context.Context, name string) (Item, error) {
	return r.QueryResolver.ItemValue(ctx, name)
}
func (r *stubQuery) Echo(ctx context.Context, input []ItemInput) ([]Item, error) {
	return r.QueryResolver.Echo(ctx, input)
}
func (r *stubQuery) Levels(ctx context.Context, in []Level) ([]Level, error) {
	return r.QueryResolver.Levels(ctx, in)
}
