// Package exec is the runtime for executors generated with exec.mode set to "table".
//
// This package is for the code that gqlgen generates, and no other code should import
// it. Its compatibility covers only what the code generated by the same release of
// gqlgen needs: a release may change it in any way, and code generated by an earlier
// release must then be generated again. The generated code refers to
// SupportPackageIsVersion1, so that code that no longer matches the runtime fails to
// compile on that name.
//
// In that mode gqlgen generates tables that describe the schema's inputs and objects
// instead of one function per field. The tables, and the function generated for each of
// them, hold the code that differs per field, such as reading a struct field or calling
// a resolver, and this package holds the code that is the same for every field:
// building the field context, running directives and middleware, propagating nulls and
// running fields concurrently.
//
// The values here are created by generated code, which builds the tables of each
// executable schema when the schema is created; they are only read afterwards. EC is the
// generated executionContext type. Functions that unmarshal or marshal a Go value take a context and the execution
// context first, such as unmarshalNString2string(ctx, ec, v).
//
// The functions that generated code calls once per entry of its tables are kept out of
// the inliner with the noinline directive: a large schema calls each thousands of times,
// and inlining them into the functions that build the tables made the compiler use more
// memory for no gain, as they run once, when the schema is created.
package exec
