// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package nopanichandler

import (
	"context"
)

type Stub struct {
	MutationResolver struct {
		Panicking func(ctx context.Context) (*string, error)
	}
	QueryResolver struct {
		Ping            func(ctx context.Context) (string, error)
		Panicking       func(ctx context.Context) (*string, error)
		PanickingObject func(ctx context.Context) (*PanicObject, error)
		PanickingList   func(ctx context.Context) ([]*PanicObject, error)
	}
	SubscriptionResolver struct {
		Count     func(ctx context.Context) (<-chan int, error)
		Failing   func(ctx context.Context) (<-chan int, error)
		Panicking func(ctx context.Context) (<-chan *int, error)
	}
}

func (r *Stub) Mutation() MutationResolver {
	return &stubMutation{r}
}
func (r *Stub) Query() QueryResolver {
	return &stubQuery{r}
}
func (r *Stub) Subscription() SubscriptionResolver {
	return &stubSubscription{r}
}

type stubMutation struct{ *Stub }

func (r *stubMutation) Panicking(ctx context.Context) (*string, error) {
	return r.MutationResolver.Panicking(ctx)
}

type stubQuery struct{ *Stub }

func (r *stubQuery) Ping(ctx context.Context) (string, error) {
	return r.QueryResolver.Ping(ctx)
}
func (r *stubQuery) Panicking(ctx context.Context) (*string, error) {
	return r.QueryResolver.Panicking(ctx)
}
func (r *stubQuery) PanickingObject(ctx context.Context) (*PanicObject, error) {
	return r.QueryResolver.PanickingObject(ctx)
}
func (r *stubQuery) PanickingList(ctx context.Context) ([]*PanicObject, error) {
	return r.QueryResolver.PanickingList(ctx)
}

type stubSubscription struct{ *Stub }

func (r *stubSubscription) Count(ctx context.Context) (<-chan int, error) {
	return r.SubscriptionResolver.Count(ctx)
}
func (r *stubSubscription) Failing(ctx context.Context) (<-chan int, error) {
	return r.SubscriptionResolver.Failing(ctx)
}
func (r *stubSubscription) Panicking(ctx context.Context) (<-chan *int, error) {
	return r.SubscriptionResolver.Panicking(ctx)
}
