//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package protogetters

import (
	"bytes"
	"context"
	"embed"
	"fmt"
	"sync"
	"sync/atomic"

	"github.com/99designs/gqlgen/codegen/testserver/protogetters/models"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/99designs/gqlgen/graphql/introspection"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// The graphql/exec runtime that this code is built with must support the version of it
// that the code was generated for. See exec.SupportPackageIsVersion1.
const _ = exec.SupportPackageIsVersion1

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		ExecutableSchemaState: &graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot]{SchemaData: cfg.Schema, Resolvers: cfg.Resolvers, Directives: cfg.Directives, ComplexityRoot: cfg.Complexity},
		tables:                builtTables(),
	}
}

type Config = graphql.Config[ResolverRoot, DirectiveRoot, ComplexityRoot]

type ResolverRoot interface {
	Query() QueryResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	Query struct {
		User func(childComplexity int, id string) int
	}

	User struct {
		GetAge   func(childComplexity int) int
		GetEmail func(childComplexity int) int
		GetId    func(childComplexity int) int
		GetName  func(childComplexity int) int
	}
}

type QueryResolver interface {
	User(ctx context.Context, id string) (*models.User, error)
}

type executableSchema struct {
	*graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot]
	tables *tables
}

func (e *executableSchema) Schema() *ast.Schema {
	if e.SchemaData != nil {
		return e.SchemaData
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := newExecutionContext(nil, e, nil)
	_ = ec
	switch typeName + "." + field {

	case "Query.user":
		if e.ComplexityRoot.Query.User == nil {
			break
		}

		args, err := ec.tables.objectQuery.ParseArgs(ctx, ec, "user", rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.User(childComplexity, args["id"].(string)), true

	case "User.age":
		if e.ComplexityRoot.User.GetAge == nil {
			break
		}

		return e.ComplexityRoot.User.GetAge(childComplexity), true
	case "User.email":
		if e.ComplexityRoot.User.GetEmail == nil {
			break
		}

		return e.ComplexityRoot.User.GetEmail(childComplexity), true
	case "User.id":
		if e.ComplexityRoot.User.GetId == nil {
			break
		}

		return e.ComplexityRoot.User.GetId(childComplexity), true
	case "User.name":
		if e.ComplexityRoot.User.GetName == nil {
			break
		}

		return e.ComplexityRoot.User.GetName(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := newExecutionContext(opCtx, e, make(chan graphql.DeferredResult))
	inputUnmarshalers := func() *graphql.InputUnmarshalerIndex {
		return graphql.NewInputUnmarshalerIndex(ec.tables.schema.InputUnmarshalers(ec)...)
	}
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithLazyInputUnmarshalerIndex(ctx, inputUnmarshalers)
				data = ec.tables.objectQuery.Marshal(ctx, ec, opCtx.Operation.SelectionSet, nil)
			} else {
				if atomic.LoadInt32(&ec.PendingDeferred) > 0 {
					result := <-ec.DeferredResults
					atomic.AddInt32(&ec.PendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.Deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.PendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.ExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot]
	tables *tables
}

func newExecutionContext(
	opCtx *graphql.OperationContext,
	execSchema *executableSchema,
	deferredResults chan graphql.DeferredResult,
) *executionContext {
	return &executionContext{
		ExecutionContextState: graphql.NewExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot](
			opCtx,
			execSchema.ExecutableSchemaState,
			parsedSchema,
			deferredResults,
		),
		tables: execSchema.tables,
	}
}

//go:embed "schema.graphql"
var sourcesFS embed.FS

func sourceData(filename string) string {
	data, err := sourcesFS.ReadFile(filename)
	if err != nil {
		panic(fmt.Sprintf("codegen problem: %s not available", filename))
	}
	return string(data)
}

var sources = []*ast.Source{
	{Name: "schema.graphql", Input: sourceData("schema.graphql"), BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)

// builtTables builds the tables when NewExecutableSchema is first called, for every
// executable schema of the package: they do not depend on the Config and are only read
// once built. They are linked to the schema as it is then, which code may change later
// through Schema, while the functions mode runs the code it was generated for.
var builtTables = sync.OnceValue(func() *tables {
	return newTables(parsedSchema)
})

// The entries of the tables, for the generated files that build them.
type (
	tableField      = exec.Field[*executionContext]
	tableInputField = exec.InputField[*executionContext]
	tableOut        = *exec.Out[*executionContext]
	tableIn         = *exec.In[*executionContext]
)

// tables holds the tables that the graphql/exec runtime executes, and the marshalers
// and unmarshalers they are built from. newTables builds them, once for the package, and
// they are only read afterwards. What the schema says about them, the runtime reads from
// the schema.
type tables struct {
	schema                                                                                  *exec.Schema[*executionContext]
	objectUser, objectQuery, object__Type, object__Field, object__Schema, object__Directive exec.Object[*executionContext]

	object__EnumValue, object__InputValue exec.Object[*executionContext]

	marshalNInt2int32   exec.OutFor[*executionContext, int32]
	unmarshalNInt2int32 exec.InFor[*executionContext, int32]

	marshalOBoolean2ᚖbool    exec.OutFor[*executionContext, *bool]
	marshalOString2ᚖstring   exec.OutFor[*executionContext, *string]
	unmarshalOBoolean2ᚖbool  exec.InFor[*executionContext, *bool]
	unmarshalOString2ᚖstring exec.InFor[*executionContext, *string]

	marshalN__Type2introspectionᚐType      exec.OutFor[*executionContext, introspection.Type]
	marshalN__Field2introspectionᚐField    exec.OutFor[*executionContext, introspection.Field]
	unmarshalN__DirectiveLocation2ᚕstringᚄ tableIn

	marshalN__Directive2introspectionᚐDirective    exec.OutFor[*executionContext, introspection.Directive]
	marshalN__EnumValue2introspectionᚐEnumValue    exec.OutFor[*executionContext, introspection.EnumValue]
	marshalN__InputValue2introspectionᚐInputValue  exec.OutFor[*executionContext, introspection.InputValue]
	unmarshalNBoolean2bool, unmarshalOBoolean2bool exec.InFor[*executionContext, bool]

	unmarshalNID2string, unmarshalNString2string, unmarshalOString2string, unmarshalN__TypeKind2string, unmarshalN__DirectiveLocation2string exec.InFor[*executionContext, string]

	marshalNBoolean2bool, marshalOBoolean2bool exec.OutFor[*executionContext, bool]

	marshalNID2string, marshalNString2string, marshalOString2string, marshalN__TypeKind2string, marshalN__DirectiveLocation2string exec.OutFor[*executionContext, string]

	marshalN__DirectiveLocation2ᚕstringᚄ, marshalN__Type2ᚕintrospectionᚐTypeᚄ, marshalO__Type2ᚕintrospectionᚐTypeᚄ, marshalO__Field2ᚕintrospectionᚐFieldᚄ, marshalN__Directive2ᚕintrospectionᚐDirectiveᚄ, marshalO__EnumValue2ᚕintrospectionᚐEnumValueᚄ tableOut

	marshalN__InputValue2ᚕintrospectionᚐInputValueᚄ, marshalO__InputValue2ᚕintrospectionᚐInputValueᚄ tableOut
}

func newTables(schemaToLink *ast.Schema) *tables {
	t := &tables{schema: exec.NewSchema[*executionContext](schemaToLink)}
	// The marshalers only take the address of the tables they marshal, so they come
	// first, each after the marshalers it uses.
	t.initMarshalers0()
	t.initObjectQuery()
	t.initObject__Field()
	t.initObject__Schema()
	t.initObject__Type()
	t.schema.Link()
	return t
}

func (t *tables) initMarshalers0() {
	t.marshalNBoolean2bool = exec.OutOf(exec.MarshalFunc[*executionContext]("Boolean!", graphql.MarshalBoolean))
	t.marshalNID2string = exec.OutOf(exec.MarshalFunc[*executionContext]("ID!", graphql.MarshalID))
	t.marshalNInt2int32 = exec.OutOf(exec.MarshalFunc[*executionContext]("Int!", graphql.MarshalInt32))
	t.marshalNString2string = exec.OutOf(exec.MarshalFunc[*executionContext]("String!", graphql.MarshalString))
	t.marshalN__Directive2introspectionᚐDirective = exec.OutOf(exec.MarshalObject[*executionContext, introspection.Directive](&t.object__Directive))
	t.marshalN__DirectiveLocation2string = exec.OutOf(exec.MarshalFunc[*executionContext]("__DirectiveLocation!", graphql.MarshalString))
	t.marshalN__EnumValue2introspectionᚐEnumValue = exec.OutOf(exec.MarshalObject[*executionContext, introspection.EnumValue](&t.object__EnumValue))
	t.marshalN__Field2introspectionᚐField = exec.OutOf(exec.MarshalObject[*executionContext, introspection.Field](&t.object__Field))
	t.marshalN__InputValue2introspectionᚐInputValue = exec.OutOf(exec.MarshalObject[*executionContext, introspection.InputValue](&t.object__InputValue))
	t.marshalN__Type2introspectionᚐType = exec.OutOf(exec.MarshalObject[*executionContext, introspection.Type](&t.object__Type))
	t.marshalN__TypeKind2string = exec.OutOf(exec.MarshalFunc[*executionContext]("__TypeKind!", graphql.MarshalString))
	t.marshalOBoolean2bool = exec.OutOf(exec.MarshalFunc[*executionContext]("Boolean", graphql.MarshalBoolean))
	t.marshalOBoolean2ᚖbool = exec.OutOf(exec.MarshalFuncPtr[*executionContext]("Boolean", graphql.MarshalBoolean))
	t.marshalOString2string = exec.OutOf(exec.MarshalFunc[*executionContext]("String", graphql.MarshalString))
	t.marshalOString2ᚖstring = exec.OutOf(exec.MarshalFuncPtr[*executionContext]("String", graphql.MarshalString))
	t.unmarshalNBoolean2bool = exec.InOf(exec.UnmarshalFunc[*executionContext](graphql.UnmarshalBoolean))
	t.unmarshalNID2string = exec.InOf(exec.UnmarshalFunc[*executionContext](graphql.UnmarshalID))
	t.unmarshalNInt2int32 = exec.InOf(exec.UnmarshalFunc[*executionContext](graphql.UnmarshalInt32))
	t.unmarshalNString2string = exec.InOf(exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString))
	t.unmarshalN__DirectiveLocation2string = exec.InOf(exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString))
	t.unmarshalN__TypeKind2string = exec.InOf(exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString))
	t.unmarshalOBoolean2bool = exec.InOf(exec.UnmarshalFunc[*executionContext](graphql.UnmarshalBoolean))
	t.unmarshalOBoolean2ᚖbool = exec.InOf(exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalBoolean))
	t.unmarshalOString2string = exec.InOf(exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString))
	t.unmarshalOString2ᚖstring = exec.InOf(exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalString))
	t.marshalN__Directive2ᚕintrospectionᚐDirectiveᚄ = exec.ListOut(t.marshalN__Directive2introspectionᚐDirective.Marshal, exec.ListOptions{ElemNonNull: true})
	t.marshalN__DirectiveLocation2ᚕstringᚄ = exec.ListOut(t.marshalN__DirectiveLocation2string.Marshal, exec.ListOptions{ElemNonNull: true})
	t.marshalN__InputValue2ᚕintrospectionᚐInputValueᚄ = exec.ListOut(t.marshalN__InputValue2introspectionᚐInputValue.Marshal, exec.ListOptions{ElemNonNull: true})
	t.marshalN__Type2ᚕintrospectionᚐTypeᚄ = exec.ListOut(t.marshalN__Type2introspectionᚐType.Marshal, exec.ListOptions{ElemNonNull: true})
	t.marshalO__EnumValue2ᚕintrospectionᚐEnumValueᚄ = exec.ListOut(t.marshalN__EnumValue2introspectionᚐEnumValue.Marshal, exec.ListOptions{Nullable: true, ElemNonNull: true})
	t.marshalO__Field2ᚕintrospectionᚐFieldᚄ = exec.ListOut(t.marshalN__Field2introspectionᚐField.Marshal, exec.ListOptions{Nullable: true, ElemNonNull: true})
	t.marshalO__InputValue2ᚕintrospectionᚐInputValueᚄ = exec.ListOut(t.marshalN__InputValue2introspectionᚐInputValue.Marshal, exec.ListOptions{Nullable: true, ElemNonNull: true})
	t.marshalO__Type2ᚕintrospectionᚐTypeᚄ = exec.ListOut(t.marshalN__Type2introspectionᚐType.Marshal, exec.ListOptions{Nullable: true, ElemNonNull: true})
	t.unmarshalN__DirectiveLocation2ᚕstringᚄ = exec.ListIn(false, t.unmarshalN__DirectiveLocation2string.Unmarshal)
}

func (t *tables) initObjectQuery() {
	t.objectQuery.Init(t.schema, "Query", _Query_resolve, []tableField{
		{Name: "user", IsResolver: true, Args: []any{t.unmarshalNID2string.In}, Type: (**models.User)(nil)},
		{Name: "__type", IsMethod: true, Args: []any{t.unmarshalNString2string.In}, Type: (**introspection.Type)(nil)},
		{Name: "__schema", IsMethod: true, Type: (**introspection.Schema)(nil)},
	})
	t.objectUser.Init(t.schema, "User", _User_resolve, []tableField{
		{Name: "id", IsMethod: true, Out: t.marshalNID2string.Out},
		{Name: "name", IsMethod: true, Out: t.marshalOString2string.Out},
		{Name: "email", IsMethod: true, Out: t.marshalOString2string.Out},
		{Name: "age", IsMethod: true, Out: t.marshalNInt2int32.Out},
	})
	t.object__Directive.Init(t.schema, "__Directive", ___Directive_resolve, []tableField{
		{Name: "name", Out: t.marshalNString2string.Out},
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "isRepeatable", Out: t.marshalNBoolean2bool.Out},
		{Name: "locations", Out: t.marshalN__DirectiveLocation2ᚕstringᚄ},
		{Name: "args", Args: []any{t.unmarshalOBoolean2ᚖbool.In}, Out: t.marshalN__InputValue2ᚕintrospectionᚐInputValueᚄ},
	})
	t.object__EnumValue.Init(t.schema, "__EnumValue", ___EnumValue_resolve, []tableField{
		{Name: "name", Out: t.marshalNString2string.Out},
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "isDeprecated", IsMethod: true, Out: t.marshalNBoolean2bool.Out},
		{Name: "deprecationReason", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
	})
}

func _Query_resolve(ctx context.Context, ec *executionContext, _ any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	switch fieldIndex {
	case 0:
		return ec.Resolvers.Query().User(ctx, fieldArgs["id"].(string))
	case 1:
		return ec.IntrospectType(fieldArgs["name"].(string))
	case 2:
		return ec.IntrospectSchema()
	}
	return nil, exec.NoField(fieldIndex)
}

func _User_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*models.User)
	switch fieldIndex {
	case 0:
		var v string = obj.GetId()
		return v, nil
	case 1:
		if !obj.HasName() {
			return nil, nil
		}
		return obj.GetName(), nil
	case 2:
		if !obj.HasEmail() {
			return nil, nil
		}
		return obj.GetEmail(), nil
	case 3:
		var v int32 = obj.GetAge()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func ___Directive_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.Directive)
	switch fieldIndex {
	case 0:
		var v string = obj.Name
		return v, nil
	case 1:
		var v *string = obj.Description()
		return v, nil
	case 2:
		var v bool = obj.IsRepeatable
		return v, nil
	case 3:
		var v []string = obj.Locations
		return v, nil
	case 4:
		var v []introspection.InputValue = obj.Args
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func ___EnumValue_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.EnumValue)
	switch fieldIndex {
	case 0:
		var v string = obj.Name
		return v, nil
	case 1:
		var v *string = obj.Description()
		return v, nil
	case 2:
		var v bool = obj.IsDeprecated()
		return v, nil
	case 3:
		var v *string = obj.DeprecationReason()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func (t *tables) initObject__Field() {
	t.object__Field.Init(t.schema, "__Field", ___Field_resolve, []tableField{
		{Name: "name", Out: t.marshalNString2string.Out},
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "args", Args: []any{t.unmarshalOBoolean2ᚖbool.In}, Out: t.marshalN__InputValue2ᚕintrospectionᚐInputValueᚄ},
		{Name: "type", Type: (**introspection.Type)(nil)},
		{Name: "isDeprecated", IsMethod: true, Out: t.marshalNBoolean2bool.Out},
		{Name: "deprecationReason", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
	})
	t.object__InputValue.Init(t.schema, "__InputValue", ___InputValue_resolve, []tableField{
		{Name: "name", Out: t.marshalNString2string.Out},
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "type", Type: (**introspection.Type)(nil)},
		{Name: "defaultValue", Out: t.marshalOString2ᚖstring.Out},
		{Name: "isDeprecated", IsMethod: true, Out: t.marshalNBoolean2bool.Out},
		{Name: "deprecationReason", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
	})
}

func ___Field_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.Field)
	switch fieldIndex {
	case 0:
		var v string = obj.Name
		return v, nil
	case 1:
		var v *string = obj.Description()
		return v, nil
	case 2:
		var v []introspection.InputValue = obj.Args
		return v, nil
	case 3:
		var v *introspection.Type = obj.Type
		return v, nil
	case 4:
		var v bool = obj.IsDeprecated()
		return v, nil
	case 5:
		var v *string = obj.DeprecationReason()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func ___InputValue_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.InputValue)
	switch fieldIndex {
	case 0:
		var v string = obj.Name
		return v, nil
	case 1:
		var v *string = obj.Description()
		return v, nil
	case 2:
		var v *introspection.Type = obj.Type
		return v, nil
	case 3:
		var v *string = obj.DefaultValue
		return v, nil
	case 4:
		var v bool = obj.IsDeprecated()
		return v, nil
	case 5:
		var v *string = obj.DeprecationReason()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func (t *tables) initObject__Schema() {
	t.object__Schema.Init(t.schema, "__Schema", ___Schema_resolve, []tableField{
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "types", IsMethod: true, Out: t.marshalN__Type2ᚕintrospectionᚐTypeᚄ},
		{Name: "queryType", IsMethod: true, Type: (**introspection.Type)(nil)},
		{Name: "mutationType", IsMethod: true, Type: (**introspection.Type)(nil)},
		{Name: "subscriptionType", IsMethod: true, Type: (**introspection.Type)(nil)},
		{Name: "directives", IsMethod: true, Out: t.marshalN__Directive2ᚕintrospectionᚐDirectiveᚄ},
	})
}

func ___Schema_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.Schema)
	switch fieldIndex {
	case 0:
		var v *string = obj.Description()
		return v, nil
	case 1:
		var v []introspection.Type = obj.Types()
		return v, nil
	case 2:
		var v *introspection.Type = obj.QueryType()
		return v, nil
	case 3:
		var v *introspection.Type = obj.MutationType()
		return v, nil
	case 4:
		var v *introspection.Type = obj.SubscriptionType()
		return v, nil
	case 5:
		var v []introspection.Directive = obj.Directives()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func (t *tables) initObject__Type() {
	t.object__Type.Init(t.schema, "__Type", ___Type_resolve, []tableField{
		{Name: "kind", IsMethod: true, Out: t.marshalN__TypeKind2string.Out},
		{Name: "name", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "specifiedByURL", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "fields", IsMethod: true, Args: []any{t.unmarshalOBoolean2bool.In}, Out: t.marshalO__Field2ᚕintrospectionᚐFieldᚄ},
		{Name: "interfaces", IsMethod: true, Out: t.marshalO__Type2ᚕintrospectionᚐTypeᚄ},
		{Name: "possibleTypes", IsMethod: true, Out: t.marshalO__Type2ᚕintrospectionᚐTypeᚄ},
		{Name: "enumValues", IsMethod: true, Args: []any{t.unmarshalOBoolean2bool.In}, Out: t.marshalO__EnumValue2ᚕintrospectionᚐEnumValueᚄ},
		{Name: "inputFields", IsMethod: true, Args: []any{nil}, Out: t.marshalO__InputValue2ᚕintrospectionᚐInputValueᚄ},
		{Name: "ofType", IsMethod: true, Type: (**introspection.Type)(nil)},
		{Name: "isOneOf", IsMethod: true, Out: t.marshalOBoolean2bool.Out},
	})
}

func ___Type_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.Type)
	switch fieldIndex {
	case 0:
		var v string = obj.Kind()
		return v, nil
	case 1:
		var v *string = obj.Name()
		return v, nil
	case 2:
		var v *string = obj.Description()
		return v, nil
	case 3:
		var v *string = obj.SpecifiedByURL()
		return v, nil
	case 4:
		return obj.Fields(fieldArgs["includeDeprecated"].(bool)), nil
	case 5:
		var v []introspection.Type = obj.Interfaces()
		return v, nil
	case 6:
		var v []introspection.Type = obj.PossibleTypes()
		return v, nil
	case 7:
		return obj.EnumValues(fieldArgs["includeDeprecated"].(bool)), nil
	case 8:
		var v []introspection.InputValue = obj.InputFields()
		return v, nil
	case 9:
		var v *introspection.Type = obj.OfType()
		return v, nil
	case 10:
		var v bool = obj.IsOneOf()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}
