//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
)

func (t *tables) initObjectMap() {
	t.objectMap.Init(t.schema, "Map", _Map_resolve, []tableField{
		{Name: "id", Out: t.marshalNID2string.Out},
	})
}

func _Map_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*Map)
	switch fieldIndex {
	case 0:
		var v string = obj.ID
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}
