//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
)

// region    ************************** generated!.gotpl **************************

type MutationResolver interface {
	DefaultInput(ctx context.Context, input DefaultInput) (*DefaultParametersMirror, error)
	OverrideValueViaInput(ctx context.Context, input FieldsOrderInput) (*FieldsOrderPayload, error)
	UpdateProduct(ctx context.Context, input map[string]interface{}) (string, error)
	Issue4053(ctx context.Context, input *Issue4053Input1) (bool, error)
	UpdateSomething(ctx context.Context, input SpecialInput) (string, error)
	UpdatePtrToPtr(ctx context.Context, input UpdatePtrToPtrOuter) (*PtrToPtrOuter, error)
}

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

var inputDefaultInput = exec.Input[*executionContext]{Name: "DefaultInput", GoType: "DefaultInput"}

func init() {
	inputDefaultInput.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "falsyBoolean", Default: false}, inUnmarshalOBoolean2ᚖbool, func(it *DefaultInput, v *bool) { it.FalsyBoolean = v }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "truthyBoolean", Default: true}, inUnmarshalOBoolean2ᚖbool, func(it *DefaultInput, v *bool) { it.TruthyBoolean = v }),
	}
}

// UnmarshalDefaultInput unmarshals raw into the DefaultInput input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalDefaultInput(ctx context.Context, raw any) (DefaultInput, error) {
	var out DefaultInput
	err := graphql.UnmarshalNamedInputFromContext(ctx, "DefaultInput", raw, &out)
	return out, err
}

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectDefaultParametersMirror = exec.Object[*executionContext]{Name: "DefaultParametersMirror", Implementors: []string{"DefaultParametersMirror"}}

func init() {
	objectDefaultParametersMirror.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "falsyBoolean", Leaf: "Boolean"}, outMarshalOBoolean2ᚖbool, func(obj *DefaultParametersMirror) *bool { return obj.FalsyBoolean }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "truthyBoolean", Leaf: "Boolean"}, outMarshalOBoolean2ᚖbool, func(obj *DefaultParametersMirror) *bool { return obj.TruthyBoolean }),
	})
}

var objectMutation = exec.Object[*executionContext]{Name: "Mutation", Implementors: []string{"Mutation"}, Root: true}

func init() {
	objectMutation.Init([]exec.Field[*executionContext]{
		{Name: "defaultInput", NonNull: true, IsMethod: true, IsResolver: true, Children: &objectDefaultParametersMirror, Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalNDefaultInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDefaultInput.In},
		}, Out: outMarshalNDefaultParametersMirror2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDefaultParametersMirror.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Mutation().DefaultInput(ctx, args["input"].(DefaultInput))
		}},
		{Name: "overrideValueViaInput", NonNull: true, IsMethod: true, IsResolver: true, Children: &objectFieldsOrderPayload, Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalNFieldsOrderInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐFieldsOrderInput.In},
		}, Out: outMarshalNFieldsOrderPayload2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐFieldsOrderPayload.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Mutation().OverrideValueViaInput(ctx, args["input"].(FieldsOrderInput))
		}},
		{Name: "updateProduct", NonNull: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "id", Type: inUnmarshalNID2string.In},
			{Name: "name", Type: inUnmarshalOString2ᚖstring.In},
			{Name: "price", Type: inUnmarshalOFloat2ᚖfloat64.In},
		}, Out: outMarshalNString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, _ any, args map[string]any) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Mutation().UpdateProduct(ctx, map[string]interface{}{
				"id":    fc.Args["id"].(string),
				"name":  fc.Args["name"].(*string),
				"price": fc.Args["price"].(*float64),
			})
		}},
		{Name: "issue4053", NonNull: true, IsMethod: true, IsResolver: true, Leaf: "Boolean", Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalOIssue4053Input12ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐIssue4053Input1.In},
		}, Out: outMarshalNBoolean2bool.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Mutation().Issue4053(ctx, args["input"].(*Issue4053Input1))
		}},
		{Name: "updateSomething", NonNull: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalNSpecialInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐSpecialInput.In},
		}, Out: outMarshalNString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Mutation().UpdateSomething(ctx, args["input"].(SpecialInput))
		}},
		{Name: "updatePtrToPtr", NonNull: true, IsMethod: true, IsResolver: true, Children: &objectPtrToPtrOuter, Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalNUpdatePtrToPtrOuter2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐUpdatePtrToPtrOuter.In},
		}, Out: outMarshalNPtrToPtrOuter2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPtrToPtrOuter.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Mutation().UpdatePtrToPtr(ctx, args["input"].(UpdatePtrToPtrOuter))
		}},
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var unmarshalNDefaultInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDefaultInput = exec.UnmarshalInput[*executionContext, DefaultInput](&inputDefaultInput)

var marshalNDefaultParametersMirror2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDefaultParametersMirror = exec.MarshalObjectPtr[*executionContext, DefaultParametersMirror](true, &objectDefaultParametersMirror)

// endregion ***************************** type.gotpl *****************************
