//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

type DeferModelResolver interface {
	OtherResolvedValue(ctx context.Context, obj *DeferModel) (string, error)
	Values(ctx context.Context, obj *DeferModel) ([]string, error)
}

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

func _DeferModelInterface(ctx context.Context, ec *executionContext, sel ast.SelectionSet, obj DeferModelInterface) graphql.Marshaler {
	switch obj := (obj).(type) {
	case nil:
		return graphql.Null
	case DeferModel:
		return objectDeferModel.Marshal(ctx, ec, sel, &obj)
	case *DeferModel:
		if obj == nil {
			return graphql.Null
		}
		return objectDeferModel.Marshal(ctx, ec, sel, obj)
	default:
		if typedObj, ok := obj.(graphql.Marshaler); ok {
			return typedObj
		} else {
			panic(fmt.Errorf("unexpected type %T; non-generated variants of DeferModelInterface must implement graphql.Marshaler", obj))
		}
	}
}

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectDeferModel = exec.Object[*executionContext]{Name: "DeferModel", Implementors: []string{"DeferModel", "DeferModelInterface"}}

func init() {
	objectDeferModel.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *DeferModel) string { return obj.ID }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *DeferModel) string { return obj.Name }),
		{Name: "otherResolvedValue", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Out: outMarshalNString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.DeferModel().OtherResolvedValue(ctx, obj.(*DeferModel))
		}},
		{Name: "values", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Out: outMarshalNString2ᚕstringᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.DeferModel().Values(ctx, obj.(*DeferModel))
		}},
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var marshalNDeferModel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDeferModel = exec.MarshalObjectPtr[*executionContext, DeferModel](true, &objectDeferModel)

var marshalODeferModel2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDeferModelᚄ = exec.MarshalList(marshalNDeferModel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDeferModel, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalODeferModel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDeferModel = exec.MarshalObjectPtr[*executionContext, DeferModel](false, &objectDeferModel)

// endregion ***************************** type.gotpl *****************************
