//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

func dir_directive3WithArg_args(ctx context.Context, ec *executionContext, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "inputNamespace",
		func(ctx context.Context, v any) (string, error) {
			return unmarshalNString2string(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["inputNamespace"] = arg0
	return args, nil
}

func dir_length_args(ctx context.Context, ec *executionContext, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "min",
		func(ctx context.Context, v any) (int, error) {
			return unmarshalNInt2int(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["min"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "max",
		func(ctx context.Context, v any) (*int, error) {
			return unmarshalOInt2ᚖint(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["max"] = arg1
	arg2, err := graphql.ProcessArgField(ctx, rawArgs, "message",
		func(ctx context.Context, v any) (*string, error) {
			return unmarshalOString2ᚖstring(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["message"] = arg2
	return args, nil
}

func dir_logged_args(ctx context.Context, ec *executionContext, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "id",
		func(ctx context.Context, v any) (string, error) {
			return unmarshalNUUID2string(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["id"] = arg0
	return args, nil
}

func dir_order1_args(ctx context.Context, ec *executionContext, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "location",
		func(ctx context.Context, v any) (string, error) {
			return unmarshalNString2string(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["location"] = arg0
	return args, nil
}

func dir_order2_args(ctx context.Context, ec *executionContext, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "location",
		func(ctx context.Context, v any) (string, error) {
			return unmarshalNString2string(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["location"] = arg0
	return args, nil
}

func dir_populate_args(ctx context.Context, ec *executionContext, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "value",
		func(ctx context.Context, v any) (string, error) {
			return unmarshalNString2string(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["value"] = arg0
	return args, nil
}

func dir_range_args(ctx context.Context, ec *executionContext, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "min",
		func(ctx context.Context, v any) (*int, error) {
			return unmarshalOInt2ᚖint(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["min"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "max",
		func(ctx context.Context, v any) (*int, error) {
			return unmarshalOInt2ᚖint(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["max"] = arg1
	return args, nil
}

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

var inputInnerDirectives = exec.Input[*executionContext]{Name: "InnerDirectives", GoType: "InnerDirectives"}

func init() {
	inputInnerDirectives.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "message", Directives: exec.Dirs(directiveLength.With(map[string]any{"min": 1, "message": "not valid"}))}, inUnmarshalNString2string, func(it *InnerDirectives, v string) { it.Message = v }),
	}
}

// UnmarshalInnerDirectives unmarshals raw into the InnerDirectives input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalInnerDirectives(ctx context.Context, raw any) (InnerDirectives, error) {
	var out InnerDirectives
	err := graphql.UnmarshalNamedInputFromContext(ctx, "InnerDirectives", raw, &out)
	return out, err
}

var inputInputDirectives = exec.Input[*executionContext]{Name: "InputDirectives", GoType: "InputDirectives"}

func init() {
	inputInputDirectives.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "text", Directives: exec.Dirs(directiveLength.With(map[string]any{"min": 0, "max": 7, "message": "not valid"}))}, inUnmarshalNString2string, func(it *InputDirectives, v string) { it.Text = v }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "nullableText", NilOK: true, Directives: exec.Dirs(directiveToNull.With(nil))}, inUnmarshalOString2ᚖstring, func(it *InputDirectives, v *string) { it.NullableText = v }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "inner"}, inUnmarshalNInnerDirectives2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInnerDirectives, func(it *InputDirectives, v *InnerDirectives) { it.Inner = v }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "innerNullable"}, inUnmarshalOInnerDirectives2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInnerDirectives, func(it *InputDirectives, v *InnerDirectives) { it.InnerNullable = v }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "thirdParty", NilOK: true, Directives: exec.Dirs(directiveLength.With(map[string]any{"min": 0, "max": 7}))}, inUnmarshalOThirdParty2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐThirdParty, func(it *InputDirectives, v *ThirdParty) { it.ThirdParty = v }),
	}
	inputInputDirectives.Directives = exec.Dirs(directiveDirective3.With(nil))
}

// UnmarshalInputDirectives unmarshals raw into the InputDirectives input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalInputDirectives(ctx context.Context, raw any) (InputDirectives, error) {
	var out InputDirectives
	err := graphql.UnmarshalNamedInputFromContext(ctx, "InputDirectives", raw, &out)
	return out, err
}

var inputInputDirectivesWithArgs = exec.Input[*executionContext]{Name: "InputDirectivesWithArgs", GoType: "InputDirectivesWithArgs"}

func init() {
	inputInputDirectivesWithArgs.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "text"}, inUnmarshalNString2string, func(it *InputDirectivesWithArgs, v string) { it.Text = v }),
	}
	inputInputDirectivesWithArgs.Directives = exec.Dirs(directiveDirective3WithArg.With(map[string]any{"inputNamespace": "InputDirectivesWithArgs"}))
}

// UnmarshalInputDirectivesWithArgs unmarshals raw into the InputDirectivesWithArgs input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalInputDirectivesWithArgs(ctx context.Context, raw any) (InputDirectivesWithArgs, error) {
	var out InputDirectivesWithArgs
	err := graphql.UnmarshalNamedInputFromContext(ctx, "InputDirectivesWithArgs", raw, &out)
	return out, err
}

var inputOuterWrapperInput = exec.Input[*executionContext]{Name: "OuterWrapperInput", GoType: "OuterWrapperInput"}

func init() {
	inputOuterWrapperInput.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "inner"}, inUnmarshalNInputDirectives2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInputDirectives, func(it *OuterWrapperInput, v *InputDirectives) { it.Inner = v }),
	}
}

// UnmarshalOuterWrapperInput unmarshals raw into the OuterWrapperInput input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalOuterWrapperInput(ctx context.Context, raw any) (OuterWrapperInput, error) {
	var out OuterWrapperInput
	err := graphql.UnmarshalNamedInputFromContext(ctx, "OuterWrapperInput", raw, &out)
	return out, err
}

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectObjectDirectives = exec.Object[*executionContext]{Name: "ObjectDirectives", Implementors: []string{"ObjectDirectives"}}

func init() {
	objectObjectDirectives.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "text", NonNull: true, Leaf: "String", Directives: exec.Dirs(directiveLength.With(map[string]any{"min": 0, "max": 7, "message": "not valid"}))}, outMarshalNString2string, func(obj *ObjectDirectives) string { return obj.Text }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "nullableText", Leaf: "String", Directives: exec.Dirs(directiveToNull.With(nil))}, outMarshalOString2ᚖstring, func(obj *ObjectDirectives) *string { return obj.NullableText }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "order", NonNull: true, Leaf: "String"}, outMarshalNString2ᚕstringᚄ, func(obj *ObjectDirectives) []string { return obj.Order }),
	})
}

var objectObjectDirectivesWithCustomGoModel = exec.Object[*executionContext]{Name: "ObjectDirectivesWithCustomGoModel", Implementors: []string{"ObjectDirectivesWithCustomGoModel"}}

func init() {
	objectObjectDirectivesWithCustomGoModel.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "nullableText", Leaf: "String", Directives: exec.Dirs(directiveToNull.With(nil))}, outMarshalOString2string, func(obj *ObjectDirectivesWithCustomGoModel) string { return obj.NullableText }),
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var unmarshalNInnerDirectives2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInnerDirectives = exec.UnmarshalInputPtr[*executionContext, InnerDirectives](false, &inputInnerDirectives)

var unmarshalNInputDirectives2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInputDirectives = exec.UnmarshalInput[*executionContext, InputDirectives](&inputInputDirectives)

var unmarshalNInputDirectives2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInputDirectives = exec.UnmarshalInputPtr[*executionContext, InputDirectives](false, &inputInputDirectives)

var unmarshalNInputDirectivesWithArgs2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInputDirectivesWithArgs = exec.UnmarshalInput[*executionContext, InputDirectivesWithArgs](&inputInputDirectivesWithArgs)

var unmarshalNOuterWrapperInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterWrapperInput = exec.UnmarshalInput[*executionContext, OuterWrapperInput](&inputOuterWrapperInput)

var unmarshalOInnerDirectives2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInnerDirectives = exec.UnmarshalInputPtr[*executionContext, InnerDirectives](true, &inputInnerDirectives)

var unmarshalOInputDirectives2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInputDirectives = exec.UnmarshalInputPtr[*executionContext, InputDirectives](true, &inputInputDirectives)

var marshalOObjectDirectives2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐObjectDirectives = exec.MarshalObjectPtr[*executionContext, ObjectDirectives](false, &objectObjectDirectives)

var marshalOObjectDirectivesWithCustomGoModel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐObjectDirectivesWithCustomGoModel = exec.MarshalObjectPtr[*executionContext, ObjectDirectivesWithCustomGoModel](false, &objectObjectDirectivesWithCustomGoModel)

// endregion ***************************** type.gotpl *****************************
