//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"
	"reflect"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
)

type FieldsOrderInputResolver interface {
	OverrideFirstField(ctx context.Context, obj *FieldsOrderInput, data *string) error
}

// UnmarshalFieldsOrderInput unmarshals raw into the FieldsOrderInput input type, as graphql.UnmarshalNamedInputFromContext does.
func UnmarshalFieldsOrderInput(ctx context.Context, raw any) (out FieldsOrderInput, err error) {
	err = graphql.UnmarshalNamedInputFromContext(ctx, "FieldsOrderInput", raw, &out)
	return out, err
}

func (t *tables) initObjectFieldsOrderPayload() {
	t.objectFieldsOrderPayload.Init(t.schema, "FieldsOrderPayload", _FieldsOrderPayload_resolve, []tableField{
		{Name: "firstFieldValue", Out: t.marshalOString2ᚖstring.Out},
	})
	t.inputFieldsOrderInput.Init(t.schema, exec.Input[*executionContext]{Name: "FieldsOrderInput", GoType: "FieldsOrderInput", Type: reflect.TypeOf((*FieldsOrderInput)(nil)).Elem(), Set: _FieldsOrderInput_set}, []tableInputField{
		{Name: "firstField", In: t.unmarshalOString2ᚖstring.In},
		{Name: "overrideFirstField", In: t.unmarshalOString2ᚖstring.In, SetWith: func(ctx context.Context, ec *executionContext, inputValue, v any) error {
			fieldValue, _ := v.(*string)
			return ec.Resolvers.FieldsOrderInput().OverrideFirstField(ctx, inputValue.(*FieldsOrderInput), fieldValue)
		}},
	})
}

func _FieldsOrderPayload_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*FieldsOrderPayload)
	switch fieldIndex {
	case 0:
		var v *string = obj.FirstFieldValue
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func _FieldsOrderInput_set(inputValue any, fieldIndex int, v any) {
	p := inputValue.(*FieldsOrderInput)
	switch fieldIndex {
	case 0:
		p.FirstField, _ = v.(*string)
	}
}
