//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"
	"reflect"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
)

// UnmarshalIssue4053Input1 unmarshals raw into the Issue4053Input1 input type, as graphql.UnmarshalNamedInputFromContext does.
func UnmarshalIssue4053Input1(ctx context.Context, raw any) (out Issue4053Input1, err error) {
	err = graphql.UnmarshalNamedInputFromContext(ctx, "Issue4053Input1", raw, &out)
	return out, err
}

// UnmarshalIssue4053Input2 unmarshals raw into the Issue4053Input2 input type, as graphql.UnmarshalNamedInputFromContext does.
func UnmarshalIssue4053Input2(ctx context.Context, raw any) (out Issue4053Input2, err error) {
	err = graphql.UnmarshalNamedInputFromContext(ctx, "Issue4053Input2", raw, &out)
	return out, err
}

func (t *tables) initInputIssue4053Input1() {
	t.inputIssue4053Input1.Init(t.schema, exec.Input[*executionContext]{Name: "Issue4053Input1", GoType: "Issue4053Input1", Type: reflect.TypeOf((*Issue4053Input1)(nil)).Elem(), Set: _Issue4053Input1_set}, []tableInputField{
		{Name: "input2", Type: (*Issue4053Input2)(nil)},
	})
	t.inputIssue4053Input2.Init(t.schema, exec.Input[*executionContext]{Name: "Issue4053Input2", GoType: "Issue4053Input2", Type: reflect.TypeOf((*Issue4053Input2)(nil)).Elem(), Set: _Issue4053Input2_set}, []tableInputField{
		{Name: "hello", In: t.unmarshalOString2string.In},
		{Name: "helloWithDefault", In: t.unmarshalOString2string.In},
	})
}

func _Issue4053Input1_set(inputValue any, fieldIndex int, v any) {
	p := inputValue.(*Issue4053Input1)
	switch fieldIndex {
	case 0:
		p.Input2, _ = v.(Issue4053Input2)
	}
}

func _Issue4053Input2_set(inputValue any, fieldIndex int, v any) {
	p := inputValue.(*Issue4053Input2)
	switch fieldIndex {
	case 0:
		p.Hello, _ = v.(string)
	case 1:
		p.HelloWithDefault, _ = v.(string)
	}
}
