//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
)

func (t *tables) initObjectCheckIssue896() {
	t.objectCheckIssue896.Init(t.schema, "CheckIssue896", _CheckIssue896_resolve, []tableField{
		{Name: "id", Out: t.marshalOInt2ᚖint.Out},
	})
}

func _CheckIssue896_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*CheckIssue896)
	switch fieldIndex {
	case 0:
		var v *int = obj.ID
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}
