//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
)

func (t *tables) initObjectLoopA() {
	t.objectLoopA.Init(t.schema, "LoopA", _LoopA_resolve, []tableField{
		{Name: "b", Type: (**LoopB)(nil)},
	})
	t.objectLoopB.Init(t.schema, "LoopB", _LoopB_resolve, []tableField{
		{Name: "a", Type: (**LoopA)(nil)},
	})
}

func _LoopA_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*LoopA)
	switch fieldIndex {
	case 0:
		var v *LoopB = obj.B
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func _LoopB_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*LoopB)
	switch fieldIndex {
	case 0:
		var v *LoopA = obj.A
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}
