//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

var inputNestedInput = exec.Input[*executionContext]{Name: "NestedInput", GoType: "NestedInput"}

func init() {
	inputNestedInput.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "field"}, inUnmarshalNEmail2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐEmail, func(it *NestedInput, v Email) { it.Field = v }),
	}
}

// UnmarshalNestedInput unmarshals raw into the NestedInput input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalNestedInput(ctx context.Context, raw any) (NestedInput, error) {
	var out NestedInput
	err := graphql.UnmarshalNamedInputFromContext(ctx, "NestedInput", raw, &out)
	return out, err
}

var inputSpecialInput = exec.Input[*executionContext]{Name: "SpecialInput", GoType: "SpecialInput"}

func init() {
	inputSpecialInput.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "nesting"}, inUnmarshalNNestedInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐNestedInput, func(it *SpecialInput, v *NestedInput) { it.Nesting = v }),
	}
}

// UnmarshalSpecialInput unmarshals raw into the SpecialInput input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalSpecialInput(ctx context.Context, raw any) (SpecialInput, error) {
	var out SpecialInput
	err := graphql.UnmarshalNamedInputFromContext(ctx, "SpecialInput", raw, &out)
	return out, err
}

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var unmarshalNEmail2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐEmail = exec.UnmarshalGQL[*executionContext, Email]()

var marshalNEmail2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐEmail = exec.MarshalSelf[*executionContext, Email]()

var unmarshalNNestedInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐNestedInput = exec.UnmarshalInputPtr[*executionContext, NestedInput](false, &inputNestedInput)

var unmarshalNSpecialInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐSpecialInput = exec.UnmarshalInput[*executionContext, SpecialInput](&inputSpecialInput)

// endregion ***************************** type.gotpl *****************************
