//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
)

type ErrorsResolver interface {
	A(ctx context.Context, obj *Errors) (*Error, error)
	B(ctx context.Context, obj *Errors) (*Error, error)
	C(ctx context.Context, obj *Errors) (*Error, error)
	D(ctx context.Context, obj *Errors) (*Error, error)
	E(ctx context.Context, obj *Errors) (*Error, error)
}

func (t *tables) initObjectError() {
	t.objectError.Init(t.schema, "Error", _Error_resolve, []tableField{
		{Name: "id", Out: t.marshalNID2string.Out},
		{Name: "errorOnNonRequiredField", IsMethod: true, Out: t.marshalOString2string.Out},
		{Name: "errorOnRequiredField", IsMethod: true, Out: t.marshalNString2string.Out},
		{Name: "nilOnRequiredField", IsMethod: true, Out: t.marshalNString2ᚖstring.Out},
	})
	t.objectErrors.Init(t.schema, "Errors", _Errors_resolve, []tableField{
		{Name: "a", IsResolver: true, Type: (**Error)(nil)},
		{Name: "b", IsResolver: true, Type: (**Error)(nil)},
		{Name: "c", IsResolver: true, Type: (**Error)(nil)},
		{Name: "d", IsResolver: true, Type: (**Error)(nil)},
		{Name: "e", IsResolver: true, Type: (**Error)(nil)},
	})
}

func _Error_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*Error)
	switch fieldIndex {
	case 0:
		var v string = obj.ID
		return v, nil
	case 1:
		return obj.ErrorOnNonRequiredField()
	case 2:
		return obj.ErrorOnRequiredField()
	case 3:
		var v *string = obj.NilOnRequiredField()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func _Errors_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*Errors)
	switch fieldIndex {
	case 0:
		return ec.Resolvers.Errors().A(ctx, obj)
	case 1:
		return ec.Resolvers.Errors().B(ctx, obj)
	case 2:
		return ec.Resolvers.Errors().C(ctx, obj)
	case 3:
		return ec.Resolvers.Errors().D(ctx, obj)
	case 4:
		return ec.Resolvers.Errors().E(ctx, obj)
	}
	return nil, exec.NoField(fieldIndex)
}
