//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/99designs/gqlgen/graphql/introspection"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var object__Directive = exec.Object[*executionContext]{Name: "__Directive", Implementors: []string{"__Directive"}}

func init() {
	object__Directive.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.Directive) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Directive) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isRepeatable", NonNull: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.Directive) bool { return obj.IsRepeatable }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "locations", NonNull: true, Leaf: "__DirectiveLocation"}, outMarshalN__DirectiveLocation2ᚕstringᚄ, func(obj *introspection.Directive) []string { return obj.Locations }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "args", NonNull: true, Children: &object__InputValue, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2ᚖbool.In},
		}}, outMarshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ, func(obj *introspection.Directive) []introspection.InputValue { return obj.Args }),
	})
}

var object__EnumValue = exec.Object[*executionContext]{Name: "__EnumValue", Implementors: []string{"__EnumValue"}}

func init() {
	object__EnumValue.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.EnumValue) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.EnumValue) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isDeprecated", NonNull: true, IsMethod: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.EnumValue) bool { return obj.IsDeprecated() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "deprecationReason", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.EnumValue) *string { return obj.DeprecationReason() }),
	})
}

var object__Field = exec.Object[*executionContext]{Name: "__Field", Implementors: []string{"__Field"}}

func init() {
	object__Field.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.Field) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Field) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "args", NonNull: true, Children: &object__InputValue, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2ᚖbool.In},
		}}, outMarshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ, func(obj *introspection.Field) []introspection.InputValue { return obj.Args }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "type", NonNull: true, Children: &object__Type}, outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Field) *introspection.Type { return obj.Type }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isDeprecated", NonNull: true, IsMethod: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.Field) bool { return obj.IsDeprecated() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "deprecationReason", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Field) *string { return obj.DeprecationReason() }),
	})
}

var object__InputValue = exec.Object[*executionContext]{Name: "__InputValue", Implementors: []string{"__InputValue"}}

func init() {
	object__InputValue.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.InputValue) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.InputValue) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "type", NonNull: true, Children: &object__Type}, outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.InputValue) *introspection.Type { return obj.Type }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "defaultValue", Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.InputValue) *string { return obj.DefaultValue }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isDeprecated", NonNull: true, IsMethod: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.InputValue) bool { return obj.IsDeprecated() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "deprecationReason", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.InputValue) *string { return obj.DeprecationReason() }),
	})
}

var object__Schema = exec.Object[*executionContext]{Name: "__Schema", Implementors: []string{"__Schema"}}

func init() {
	object__Schema.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Schema) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "types", NonNull: true, IsMethod: true, Children: &object__Type}, outMarshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ, func(obj *introspection.Schema) []introspection.Type { return obj.Types() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "queryType", NonNull: true, IsMethod: true, Children: &object__Type}, outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Schema) *introspection.Type { return obj.QueryType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "mutationType", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Schema) *introspection.Type { return obj.MutationType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "subscriptionType", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Schema) *introspection.Type { return obj.SubscriptionType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "directives", NonNull: true, IsMethod: true, Children: &object__Directive}, outMarshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ, func(obj *introspection.Schema) []introspection.Directive { return obj.Directives() }),
	})
}

var object__Type = exec.Object[*executionContext]{Name: "__Type", Implementors: []string{"__Type"}}

func init() {
	object__Type.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "kind", NonNull: true, IsMethod: true, Leaf: "__TypeKind"}, outMarshalN__TypeKind2string, func(obj *introspection.Type) string { return obj.Kind() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Type) *string { return obj.Name() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Type) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "specifiedByURL", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Type) *string { return obj.SpecifiedByURL() }),
		{Name: "fields", IsMethod: true, Children: &object__Field, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2bool.In},
		}, Out: outMarshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return obj.(*introspection.Type).Fields(args["includeDeprecated"].(bool)), nil
		}},
		exec.FieldGet(exec.Field[*executionContext]{Name: "interfaces", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ, func(obj *introspection.Type) []introspection.Type { return obj.Interfaces() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "possibleTypes", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ, func(obj *introspection.Type) []introspection.Type { return obj.PossibleTypes() }),
		{Name: "enumValues", IsMethod: true, Children: &object__EnumValue, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2bool.In},
		}, Out: outMarshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return obj.(*introspection.Type).EnumValues(args["includeDeprecated"].(bool)), nil
		}},
		exec.FieldGet(exec.Field[*executionContext]{Name: "inputFields", IsMethod: true, Children: &object__InputValue}, outMarshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ, func(obj *introspection.Type) []introspection.InputValue { return obj.InputFields() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "ofType", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Type) *introspection.Type { return obj.OfType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isOneOf", IsMethod: true, Leaf: "Boolean"}, outMarshalOBoolean2bool, func(obj *introspection.Type) bool { return obj.IsOneOf() }),
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var unmarshalNBoolean2bool = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalBoolean)

var marshalNBoolean2bool = exec.MarshalFunc[*executionContext](true, graphql.MarshalBoolean)

var unmarshalNFloat2float64 = exec.UnmarshalFuncContext[*executionContext](graphql.UnmarshalFloatContext)

var marshalNFloat2float64 = exec.MarshalFuncContext[*executionContext](true, graphql.MarshalFloatContext)

var unmarshalNID2int = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalIntID)

var marshalNID2int = exec.MarshalFunc[*executionContext](true, graphql.MarshalIntID)

var unmarshalNID2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalID)

var marshalNID2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalID)

var unmarshalNInt2int = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalInt)

var marshalNInt2int = exec.MarshalFunc[*executionContext](true, graphql.MarshalInt)

var unmarshalNInt2int32 = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalInt32)

var marshalNInt2int32 = exec.MarshalFunc[*executionContext](true, graphql.MarshalInt32)

var unmarshalNInt2int64 = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalInt64)

var marshalNInt2int64 = exec.MarshalFunc[*executionContext](true, graphql.MarshalInt64)

var unmarshalNString2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalNString2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalString)

var unmarshalNString2ᚕstringᚄ = exec.UnmarshalList(false, unmarshalNString2string)

var marshalNString2ᚕstringᚄ = exec.MarshalList(marshalNString2string, exec.ListOptions{ElemNonNull: true, Leaf: true})

var unmarshalNString2ᚕᚖstring = exec.UnmarshalList(false, unmarshalOString2ᚖstring)

var marshalNString2ᚕᚖstring = exec.MarshalList(marshalOString2ᚖstring, exec.ListOptions{Leaf: true})

var unmarshalNString2ᚖstring = exec.UnmarshalFuncPtr[*executionContext](false, graphql.UnmarshalString)

var marshalNString2ᚖstring = exec.MarshalFuncPtr[*executionContext](true, graphql.MarshalString)

var marshalN__Directive2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirective = exec.MarshalObject[*executionContext, introspection.Directive](&object__Directive)

var marshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ = exec.MarshalList(marshalN__Directive2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirective, exec.ListOptions{ElemNonNull: true})

var unmarshalN__DirectiveLocation2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalN__DirectiveLocation2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalString)

var unmarshalN__DirectiveLocation2ᚕstringᚄ = exec.UnmarshalList(false, unmarshalN__DirectiveLocation2string)

var marshalN__DirectiveLocation2ᚕstringᚄ = exec.MarshalList(marshalN__DirectiveLocation2string, exec.ListOptions{ElemNonNull: true})

var marshalN__EnumValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValue = exec.MarshalObject[*executionContext, introspection.EnumValue](&object__EnumValue)

var marshalN__Field2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐField = exec.MarshalObject[*executionContext, introspection.Field](&object__Field)

var marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue = exec.MarshalObject[*executionContext, introspection.InputValue](&object__InputValue)

var marshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.MarshalList(marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue, exec.ListOptions{ElemNonNull: true})

var marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.MarshalObject[*executionContext, introspection.Type](&object__Type)

var marshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.MarshalList(marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, exec.ListOptions{ElemNonNull: true})

var marshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.MarshalObjectPtr[*executionContext, introspection.Type](true, &object__Type)

var unmarshalN__TypeKind2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalN__TypeKind2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalString)

var unmarshalOBoolean2bool = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalBoolean)

var marshalOBoolean2bool = exec.MarshalFunc[*executionContext](false, graphql.MarshalBoolean)

var unmarshalOBoolean2ᚖbool = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalBoolean)

var marshalOBoolean2ᚖbool = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalBoolean)

var unmarshalOFloat2float64 = exec.UnmarshalFuncContext[*executionContext](graphql.UnmarshalFloatContext)

var marshalOFloat2float64 = exec.MarshalFuncContext[*executionContext](false, graphql.MarshalFloatContext)

var unmarshalOFloat2ᚖfloat64 = exec.UnmarshalFuncContextPtr[*executionContext](true, graphql.UnmarshalFloatContext)

var marshalOFloat2ᚖfloat64 = exec.MarshalFuncContextPtr[*executionContext](false, graphql.MarshalFloatContext)

var unmarshalOID2ᚖstring = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalID)

var marshalOID2ᚖstring = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalID)

var unmarshalOInt2ᚖint = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalInt)

var marshalOInt2ᚖint = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalInt)

var unmarshalOString2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalOString2string = exec.MarshalFunc[*executionContext](false, graphql.MarshalString)

var unmarshalOString2ᚕstringᚄ = exec.UnmarshalList(true, unmarshalNString2string)

var marshalOString2ᚕstringᚄ = exec.MarshalList(marshalNString2string, exec.ListOptions{Nullable: true, ElemNonNull: true, Leaf: true})

var unmarshalOString2ᚕᚖstring = exec.UnmarshalList(true, unmarshalOString2ᚖstring)

var marshalOString2ᚕᚖstring = exec.MarshalList(marshalOString2ᚖstring, exec.ListOptions{Nullable: true, Leaf: true})

var unmarshalOString2ᚖstring = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalString)

var marshalOString2ᚖstring = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalString)

func unmarshalOString2ᚖᚕstringᚄ(ctx context.Context, ec *executionContext, v any) (*[]string, error) {
	if v == nil {
		return nil, nil
	}
	res, err := unmarshalOString2ᚕstringᚄ(ctx, ec, v)
	return &res, graphql.ErrorOnPath(ctx, err)
}

func marshalOString2ᚖᚕstringᚄ(ctx context.Context, ec *executionContext, sel ast.SelectionSet, v *[]string) graphql.Marshaler {
	if v == nil {
		return graphql.Null
	}
	return marshalOString2ᚕstringᚄ(ctx, ec, sel, *v)
}

var marshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ = exec.MarshalList(marshalN__EnumValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValue, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ = exec.MarshalList(marshalN__Field2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐField, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.MarshalList(marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema = exec.MarshalObjectPtr[*executionContext, introspection.Schema](false, &object__Schema)

var marshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.MarshalList(marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.MarshalObjectPtr[*executionContext, introspection.Type](false, &object__Type)

// endregion ***************************** type.gotpl *****************************
