//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
)

// region    ************************** generated!.gotpl **************************

type PrimitiveResolver interface {
	Value(ctx context.Context, obj *Primitive) (int, error)
}
type PrimitiveStringResolver interface {
	Value(ctx context.Context, obj *PrimitiveString) (string, error)

	Len(ctx context.Context, obj *PrimitiveString) (int, error)
}

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectPrimitive = exec.Object[*executionContext]{Name: "Primitive", Implementors: []string{"Primitive"}}

func init() {
	objectPrimitive.Init([]exec.Field[*executionContext]{
		{Name: "value", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Int", Out: outMarshalNInt2int.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Primitive().Value(ctx, obj.(*Primitive))
		}},
		exec.FieldGet(exec.Field[*executionContext]{Name: "squared", NonNull: true, IsMethod: true, Leaf: "Int"}, outMarshalNInt2int, func(obj *Primitive) int { return obj.Squared() }),
	})
}

var objectPrimitiveString = exec.Object[*executionContext]{Name: "PrimitiveString", Implementors: []string{"PrimitiveString"}}

func init() {
	objectPrimitiveString.Init([]exec.Field[*executionContext]{
		{Name: "value", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Out: outMarshalNString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.PrimitiveString().Value(ctx, obj.(*PrimitiveString))
		}},
		exec.FieldGet(exec.Field[*executionContext]{Name: "doubled", NonNull: true, IsMethod: true, Leaf: "String"}, outMarshalNString2string, func(obj *PrimitiveString) string { return obj.Doubled() }),
		{Name: "len", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Int", Out: outMarshalNInt2int.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.PrimitiveString().Len(ctx, obj.(*PrimitiveString))
		}},
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var marshalNPrimitive2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPrimitive = exec.MarshalObject[*executionContext, Primitive](&objectPrimitive)

var marshalNPrimitive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPrimitiveᚄ = exec.MarshalList(marshalNPrimitive2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPrimitive, exec.ListOptions{ElemNonNull: true})

var marshalNPrimitiveString2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPrimitiveString = exec.MarshalObject[*executionContext, PrimitiveString](&objectPrimitiveString)

var marshalNPrimitiveString2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPrimitiveStringᚄ = exec.MarshalList(marshalNPrimitiveString2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPrimitiveString, exec.ListOptions{ElemNonNull: true})

// endregion ***************************** type.gotpl *****************************
