//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
)

func (t *tables) initObjectPtrToSliceContainer() {
	t.objectPtrToSliceContainer.Init(t.schema, "PtrToSliceContainer", _PtrToSliceContainer_resolve, []tableField{
		{Name: "ptrToSlice", Out: t.outMarshalOString2ᚖᚕstringᚄ.Out},
	})
}

func _PtrToSliceContainer_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*PtrToSliceContainer)
	switch fieldIndex {
	case 0:
		var v *[]string = obj.PtrToSlice
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}
