//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectEmbeddedDefaultScalar = exec.Object[*executionContext]{Name: "EmbeddedDefaultScalar", Implementors: []string{"EmbeddedDefaultScalar"}}

func init() {
	objectEmbeddedDefaultScalar.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "value", Leaf: "DefaultScalarImplementation"}, outMarshalODefaultScalarImplementation2ᚖstring, func(obj *EmbeddedDefaultScalar) *string { return obj.Value }),
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var unmarshalNDefaultScalarImplementation2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalNDefaultScalarImplementation2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalString)

var unmarshalODefaultScalarImplementation2ᚖstring = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalString)

var marshalODefaultScalarImplementation2ᚖstring = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalString)

// endregion ***************************** type.gotpl *****************************
