//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
)

func (t *tables) initObjectEmbeddedDefaultScalar() {
	t.objectEmbeddedDefaultScalar.Init(t.schema, "EmbeddedDefaultScalar", _EmbeddedDefaultScalar_resolve, []tableField{
		{Name: "value", Out: t.marshalODefaultScalarImplementation2ᚖstring.Out},
	})
}

func _EmbeddedDefaultScalar_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*EmbeddedDefaultScalar)
	switch fieldIndex {
	case 0:
		var v *string = obj.Value
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}
