//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"
	"time"

	introspection1 "github.com/99designs/gqlgen/codegen/testserver/followschema/introspection"
	invalid_packagename "github.com/99designs/gqlgen/codegen/testserver/followschema/invalid-packagename"
	"github.com/99designs/gqlgen/codegen/testserver/followschema/otherpkg"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

type ForcedResolverResolver interface {
	Field(ctx context.Context, obj *ForcedResolver) (*Circle, error)
}
type ModelMethodsResolver interface {
	ResolverField(ctx context.Context, obj *ModelMethods) (bool, error)
}
type PetResolver interface {
	Friends(ctx context.Context, obj *Pet, limit *int) ([]*Pet, error)
}
type QueryResolver interface {
	InvalidIdentifier(ctx context.Context) (*invalid_packagename.InvalidIdentifier, error)
	Collision(ctx context.Context) (*introspection1.It, error)
	MapInput(ctx context.Context, input map[string]any) (*bool, error)
	Recursive(ctx context.Context, input *RecursiveInputSlice) (*bool, error)
	NestedInputs(ctx context.Context, input [][]*OuterInput) (*bool, error)
	NestedOutputs(ctx context.Context) ([][]*OuterObject, error)
	ModelMethods(ctx context.Context) (*ModelMethods, error)
	User(ctx context.Context, id int) (*User, error)
	NullableArg(ctx context.Context, arg *int) (*string, error)
	InputSlice(ctx context.Context, arg []string) (bool, error)
	InputNullableSlice(ctx context.Context, arg []string) (bool, error)
	InputOmittable(ctx context.Context, arg OmittableInput) (string, error)
	ShapeUnion(ctx context.Context) (ShapeUnion, error)
	Autobind(ctx context.Context) (*Autobind, error)
	DeprecatedField(ctx context.Context) (string, error)
	FieldWithDeprecatedArg(ctx context.Context, oldArg *int, newArg *int) (*string, error)
	Overlapping(ctx context.Context) (*OverlappingFields, error)
	DefaultParameters(ctx context.Context, falsyBoolean *bool, truthyBoolean *bool) (*DefaultParametersMirror, error)
	DeferSingle(ctx context.Context) (*DeferModel, error)
	DeferMultiple(ctx context.Context) ([]*DeferModel, error)
	DirectiveArg(ctx context.Context, arg string) (*string, error)
	DirectiveNullableArg(ctx context.Context, arg *int, arg2 *int, arg3 *string) (*string, error)
	DirectiveSingleNullableArg(ctx context.Context, arg1 *string) (*string, error)
	DirectiveInputNullable(ctx context.Context, arg *InputDirectives) (*string, error)
	DirectiveInput(ctx context.Context, arg InputDirectives) (*string, error)
	DirectiveInputType(ctx context.Context, arg InnerInput) (*string, error)
	DirectiveInputOuter(ctx context.Context, arg OuterWrapperInput) (*string, error)
	DirectiveInputWithArgs(ctx context.Context, arg InputDirectivesWithArgs) (*string, error)
	DirectiveObject(ctx context.Context) (*ObjectDirectives, error)
	DirectiveObjectWithCustomGoModel(ctx context.Context) (*ObjectDirectivesWithCustomGoModel, error)
	DirectiveFieldDef(ctx context.Context, ret string) (string, error)
	DirectiveField(ctx context.Context) (*string, error)
	DirectiveDouble(ctx context.Context) (*string, error)
	DirectiveUnimplemented(ctx context.Context) (*string, error)
	EmbeddedCase1(ctx context.Context) (*EmbeddedCase1, error)
	EmbeddedCase2(ctx context.Context) (*EmbeddedCase2, error)
	EmbeddedCase3(ctx context.Context) (*EmbeddedCase3, error)
	EnumInInput(ctx context.Context, input *InputWithEnumValue) (EnumTest, error)
	SearchProducts(ctx context.Context, filters map[string]interface{}) ([]string, error)
	SearchRequired(ctx context.Context, filters map[string]interface{}) ([]string, error)
	SearchProductsNormal(ctx context.Context, filters map[string]any) ([]string, error)
	SearchWithDefaults(ctx context.Context, filters map[string]interface{}) ([]string, error)
	SearchMixed(ctx context.Context, filters map[string]interface{}, limit *int, offset *int, sortBy *string) ([]string, error)
	FilterProducts(ctx context.Context, filters map[string]interface{}) ([]string, error)
	FindProducts(ctx context.Context, filters map[string]interface{}) ([]string, error)
	SearchWithDirectives(ctx context.Context, input map[string]interface{}) ([]string, error)
	Shapes(ctx context.Context) ([]Shape, error)
	NoShape(ctx context.Context) (Shape, error)
	Node(ctx context.Context) (Node, error)
	NoShapeTypedNil(ctx context.Context) (Shape, error)
	Animal(ctx context.Context) (Animal, error)
	NotAnInterface(ctx context.Context) (BackedByInterface, error)
	Dog(ctx context.Context) (*Dog, error)
	Issue896a(ctx context.Context) ([]*CheckIssue896, error)
	MapStringInterface(ctx context.Context, in map[string]any) (map[string]any, error)
	MapNestedStringInterface(ctx context.Context, in *NestedMapInput) (map[string]any, error)
	MapNestedMapSlice(ctx context.Context, input map[string]any) (*bool, error)
	ErrorBubble(ctx context.Context) (*Error, error)
	ErrorBubbleList(ctx context.Context) ([]*Error, error)
	ErrorList(ctx context.Context) ([]*Error, error)
	Errors(ctx context.Context) (*Errors, error)
	Valid(ctx context.Context) (string, error)
	Invalid(ctx context.Context) (string, error)
	Panics(ctx context.Context) (*Panics, error)
	PrimitiveObject(ctx context.Context) ([]Primitive, error)
	PrimitiveStringObject(ctx context.Context) ([]PrimitiveString, error)
	PtrToAnyContainer(ctx context.Context) (*PtrToAnyContainer, error)
	PtrToSliceContainer(ctx context.Context) (*PtrToSliceContainer, error)
	Infinity(ctx context.Context) (float64, error)
	StringFromContextInterface(ctx context.Context) (*StringFromContextInterface, error)
	StringFromContextFunction(ctx context.Context) (string, error)
	DefaultScalar(ctx context.Context, arg string) (string, error)
	SkipInclude(ctx context.Context) (*SkipIncludeTestType, error)
	Slices(ctx context.Context) (*Slices, error)
	ScalarSlice(ctx context.Context) ([]byte, error)
	Fallback(ctx context.Context, arg FallbackToStringEncoding) (FallbackToStringEncoding, error)
	OptionalUnion(ctx context.Context) (TestUnion, error)
	VOkCaseValue(ctx context.Context) (*VOkCaseValue, error)
	VOkCaseNil(ctx context.Context) (*VOkCaseNil, error)
	ValidType(ctx context.Context) (*ValidType, error)
	VariadicModel(ctx context.Context) (*VariadicModel, error)
	WrappedStruct(ctx context.Context) (*WrappedStruct, error)
	WrappedScalar(ctx context.Context) (otherpkg.Scalar, error)
	WrappedMap(ctx context.Context) (WrappedMap, error)
	WrappedSlice(ctx context.Context) (WrappedSlice, error)
}
type SubscriptionResolver interface {
	Updated(ctx context.Context) (<-chan string, error)
	InitPayload(ctx context.Context) (<-chan string, error)
	DirectiveArg(ctx context.Context, arg string) (<-chan *string, error)
	DirectiveNullableArg(ctx context.Context, arg *int, arg2 *int, arg3 *string) (<-chan *string, error)
	DirectiveDouble(ctx context.Context) (<-chan *string, error)
	DirectiveUnimplemented(ctx context.Context) (<-chan *string, error)
	Issue896b(ctx context.Context) (<-chan []*CheckIssue896, error)
	ErrorRequired(ctx context.Context) (<-chan *Error, error)
}
type UserResolver interface {
	Friends(ctx context.Context, obj *User) ([]*User, error)

	Pets(ctx context.Context, obj *User, limit *int) ([]*Pet, error)
}

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

func dir_defer_args(ctx context.Context, ec *executionContext, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "if",
		func(ctx context.Context, v any) (*bool, error) {
			return unmarshalOBoolean2ᚖbool(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["if"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "label",
		func(ctx context.Context, v any) (*string, error) {
			return unmarshalOString2ᚖstring(ctx, ec, v)
		})
	if err != nil {
		return nil, err
	}
	args["label"] = arg1
	return args, nil
}

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

var inputChanges = exec.Input[*executionContext]{Name: "Changes", GoType: "map[string]any", IsMap: true}

func init() {
	inputChanges.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "a"}, inUnmarshalOInt2ᚖint, func(it *map[string]any, v *int) { (*it)["a"] = v }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "b"}, inUnmarshalOInt2ᚖint, func(it *map[string]any, v *int) { (*it)["b"] = v }),
	}
}

// UnmarshalChanges unmarshals raw into the Changes input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalChanges(ctx context.Context, raw any) (map[string]any, error) {
	var out map[string]any
	err := graphql.UnmarshalNamedInputFromContext(ctx, "Changes", raw, &out)
	return out, err
}

var inputInnerInput = exec.Input[*executionContext]{Name: "InnerInput", GoType: "InnerInput"}

func init() {
	inputInnerInput.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "id"}, inUnmarshalNInt2int, func(it *InnerInput, v int) { it.ID = v }),
	}
}

// UnmarshalInnerInput unmarshals raw into the InnerInput input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalInnerInput(ctx context.Context, raw any) (InnerInput, error) {
	var out InnerInput
	err := graphql.UnmarshalNamedInputFromContext(ctx, "InnerInput", raw, &out)
	return out, err
}

var inputOmittableInput = exec.Input[*executionContext]{Name: "OmittableInput", GoType: "OmittableInput"}

func init() {
	inputOmittableInput.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "id"}, inUnmarshalOID2ᚖstring, func(it *OmittableInput, v *string) { it.ID = graphql.OmittableOf(v) }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "bool"}, inUnmarshalOBoolean2ᚖbool, func(it *OmittableInput, v *bool) { it.Bool = graphql.OmittableOf(v) }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "str"}, inUnmarshalOString2ᚖstring, func(it *OmittableInput, v *string) { it.Str = graphql.OmittableOf(v) }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "int"}, inUnmarshalOInt2ᚖint, func(it *OmittableInput, v *int) { it.Int = graphql.OmittableOf(v) }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "time"}, inUnmarshalOTime2ᚖtimeᚐTime, func(it *OmittableInput, v *time.Time) { it.Time = graphql.OmittableOf(v) }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "enum"}, inUnmarshalOStatus2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐStatus, func(it *OmittableInput, v *Status) { it.Enum = graphql.OmittableOf(v) }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "scalar"}, inUnmarshalOThirdParty2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐThirdParty, func(it *OmittableInput, v *ThirdParty) { it.Scalar = graphql.OmittableOf(v) }),
		exec.InputSet(exec.InputField[*executionContext]{Name: "object"}, inUnmarshalOOuterInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterInput, func(it *OmittableInput, v *OuterInput) { it.Object = graphql.OmittableOf(v) }),
	}
}

// UnmarshalOmittableInput unmarshals raw into the OmittableInput input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalOmittableInput(ctx context.Context, raw any) (OmittableInput, error) {
	var out OmittableInput
	err := graphql.UnmarshalNamedInputFromContext(ctx, "OmittableInput", raw, &out)
	return out, err
}

var inputOuterInput = exec.Input[*executionContext]{Name: "OuterInput", GoType: "OuterInput"}

func init() {
	inputOuterInput.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "inner"}, inUnmarshalNInnerInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInnerInput, func(it *OuterInput, v *InnerInput) { it.Inner = v }),
	}
}

// UnmarshalOuterInput unmarshals raw into the OuterInput input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalOuterInput(ctx context.Context, raw any) (OuterInput, error) {
	var out OuterInput
	err := graphql.UnmarshalNamedInputFromContext(ctx, "OuterInput", raw, &out)
	return out, err
}

var inputRecursiveInputSlice = exec.Input[*executionContext]{Name: "RecursiveInputSlice", GoType: "RecursiveInputSlice"}

func init() {
	inputRecursiveInputSlice.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "self"}, inUnmarshalORecursiveInputSlice2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐRecursiveInputSliceᚄ, func(it *RecursiveInputSlice, v []RecursiveInputSlice) { it.Self = v }),
	}
}

// UnmarshalRecursiveInputSlice unmarshals raw into the RecursiveInputSlice input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalRecursiveInputSlice(ctx context.Context, raw any) (RecursiveInputSlice, error) {
	var out RecursiveInputSlice
	err := graphql.UnmarshalNamedInputFromContext(ctx, "RecursiveInputSlice", raw, &out)
	return out, err
}

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectAutobind = exec.Object[*executionContext]{Name: "Autobind", Implementors: []string{"Autobind"}}

func init() {
	objectAutobind.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "int", NonNull: true, Leaf: "Int"}, outMarshalNInt2int, func(obj *Autobind) int { return obj.Int }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "int32", NonNull: true, Leaf: "Int"}, outMarshalNInt2int32, func(obj *Autobind) int32 { return obj.Int32 }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "int64", NonNull: true, Leaf: "Int"}, outMarshalNInt2int64, func(obj *Autobind) int64 { return obj.Int64 }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "idStr", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *Autobind) string { return obj.IdStr }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "idInt", NonNull: true, Leaf: "ID"}, outMarshalNID2int, func(obj *Autobind) int { return obj.IdInt }),
	})
}

var objectEmbeddedPointer = exec.Object[*executionContext]{Name: "EmbeddedPointer", Implementors: []string{"EmbeddedPointer"}}

func init() {
	objectEmbeddedPointer.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "ID", Leaf: "String"}, outMarshalOString2string, func(obj *EmbeddedPointerModel) string { return obj.ID }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "Title", Leaf: "String"}, outMarshalOString2string, func(obj *EmbeddedPointerModel) string { return obj.Title }),
	})
}

var objectForcedResolver = exec.Object[*executionContext]{Name: "ForcedResolver", Implementors: []string{"ForcedResolver"}}

func init() {
	objectForcedResolver.Init([]exec.Field[*executionContext]{
		{Name: "field", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectCircle, Out: outMarshalOCircle2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐCircle.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.ForcedResolver().Field(ctx, obj.(*ForcedResolver))
		}},
	})
}

var objectInnerObject = exec.Object[*executionContext]{Name: "InnerObject", Implementors: []string{"InnerObject"}}

func init() {
	objectInnerObject.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "Int"}, outMarshalNInt2int, func(obj *InnerObject) int { return obj.ID }),
	})
}

var objectInvalidIdentifier = exec.Object[*executionContext]{Name: "InvalidIdentifier", Implementors: []string{"InvalidIdentifier"}}

func init() {
	objectInvalidIdentifier.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "Int"}, outMarshalNInt2int, func(obj *invalid_packagename.InvalidIdentifier) int { return obj.ID }),
	})
}

var objectIt = exec.Object[*executionContext]{Name: "It", Implementors: []string{"It"}}

func init() {
	objectIt.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *introspection1.It) string { return obj.ID }),
	})
}

var objectModelMethods = exec.Object[*executionContext]{Name: "ModelMethods", Implementors: []string{"ModelMethods"}}

func init() {
	objectModelMethods.Init([]exec.Field[*executionContext]{
		{Name: "resolverField", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Boolean", Out: outMarshalNBoolean2bool.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.ModelMethods().ResolverField(ctx, obj.(*ModelMethods))
		}},
		exec.FieldGet(exec.Field[*executionContext]{Name: "noContext", NonNull: true, IsMethod: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *ModelMethods) bool { return obj.NoContext() }),
		{Name: "withContext", NonNull: true, Concurrent: true, IsMethod: true, Leaf: "Boolean", Out: outMarshalNBoolean2bool.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return obj.(*ModelMethods).WithContext(ctx), nil
		}},
	})
}

var objectOuterObject = exec.Object[*executionContext]{Name: "OuterObject", Implementors: []string{"OuterObject"}}

func init() {
	objectOuterObject.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "inner", NonNull: true, Children: &objectInnerObject}, outMarshalNInnerObject2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInnerObject, func(obj *OuterObject) *InnerObject { return obj.Inner }),
	})
}

var objectPet = exec.Object[*executionContext]{Name: "Pet", Implementors: []string{"Pet"}}

func init() {
	objectPet.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "Int"}, outMarshalNInt2int, func(obj *Pet) int { return obj.ID }),
		{Name: "friends", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectPet, Args: []exec.Arg[*executionContext]{
			{Name: "limit", Type: inUnmarshalOInt2ᚖint.In},
		}, Out: outMarshalOPet2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPetᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Pet().Friends(ctx, obj.(*Pet), args["limit"].(*int))
		}},
	})
}

var objectQuery = exec.Object[*executionContext]{Name: "Query", Implementors: []string{"Query"}, Root: true}

func init() {
	objectQuery.Init([]exec.Field[*executionContext]{
		{Name: "invalidIdentifier", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectInvalidIdentifier, Out: outMarshalOInvalidIdentifier2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚋinvalidᚑpackagenameᚐInvalidIdentifier.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().InvalidIdentifier(ctx)
		}},
		{Name: "collision", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectIt, Out: outMarshalOIt2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚋintrospectionᚐIt.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Collision(ctx)
		}},
		{Name: "mapInput", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Boolean", Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalOChanges2map.In},
		}, Out: outMarshalOBoolean2ᚖbool.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().MapInput(ctx, args["input"].(map[string]any))
		}},
		{Name: "recursive", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Boolean", Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalORecursiveInputSlice2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐRecursiveInputSlice.In},
		}, Out: outMarshalOBoolean2ᚖbool.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Recursive(ctx, args["input"].(*RecursiveInputSlice))
		}},
		{Name: "nestedInputs", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Boolean", Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalOOuterInput2ᚕᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterInput.In},
		}, Out: outMarshalOBoolean2ᚖbool.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().NestedInputs(ctx, args["input"].([][]*OuterInput))
		}},
		{Name: "nestedOutputs", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectOuterObject, Out: outMarshalOOuterObject2ᚕᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterObject.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().NestedOutputs(ctx)
		}},
		{Name: "modelMethods", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectModelMethods, Out: outMarshalOModelMethods2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐModelMethods.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().ModelMethods(ctx)
		}},
		{Name: "user", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectUser, Args: []exec.Arg[*executionContext]{
			{Name: "id", Type: inUnmarshalNInt2int.In},
		}, Out: outMarshalNUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐUser.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().User(ctx, args["id"].(int))
		}},
		{Name: "nullableArg", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Type: inUnmarshalOInt2ᚖint.In},
		}, Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().NullableArg(ctx, args["arg"].(*int))
		}},
		{Name: "inputSlice", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Boolean", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Type: inUnmarshalNString2ᚕstringᚄ.In},
		}, Out: outMarshalNBoolean2bool.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().InputSlice(ctx, args["arg"].([]string))
		}},
		{Name: "inputNullableSlice", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Boolean", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Type: inUnmarshalOString2ᚕstringᚄ.In},
		}, Out: outMarshalNBoolean2bool.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().InputNullableSlice(ctx, args["arg"].([]string))
		}},
		{Name: "inputOmittable", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Type: inUnmarshalNOmittableInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOmittableInput.In},
		}, Out: outMarshalNString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().InputOmittable(ctx, args["arg"].(OmittableInput))
		}},
		{Name: "shapeUnion", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "ShapeUnion", Out: outMarshalNShapeUnion2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐShapeUnion.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().ShapeUnion(ctx)
		}},
		{Name: "autobind", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectAutobind, Out: outMarshalOAutobind2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐAutobind.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Autobind(ctx)
		}},
		{Name: "deprecatedField", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Out: outMarshalNString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DeprecatedField(ctx)
		}},
		{Name: "fieldWithDeprecatedArg", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "oldArg", Type: inUnmarshalOInt2ᚖint.In},
			{Name: "newArg", Type: inUnmarshalOInt2ᚖint.In},
		}, Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().FieldWithDeprecatedArg(ctx, args["oldArg"].(*int), args["newArg"].(*int))
		}},
		{Name: "overlapping", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectOverlappingFields, Out: outMarshalOOverlappingFields2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOverlappingFields.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Overlapping(ctx)
		}},
		{Name: "defaultParameters", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectDefaultParametersMirror, Args: []exec.Arg[*executionContext]{
			{Name: "falsyBoolean", Type: inUnmarshalOBoolean2ᚖbool.In},
			{Name: "truthyBoolean", Type: inUnmarshalOBoolean2ᚖbool.In},
		}, Out: outMarshalNDefaultParametersMirror2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDefaultParametersMirror.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DefaultParameters(ctx, args["falsyBoolean"].(*bool), args["truthyBoolean"].(*bool))
		}},
		{Name: "deferSingle", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectDeferModel, Out: outMarshalODeferModel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDeferModel.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DeferSingle(ctx)
		}},
		{Name: "deferMultiple", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectDeferModel, Out: outMarshalODeferModel2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDeferModelᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DeferMultiple(ctx)
		}},
		{Name: "directiveArg", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Directives: exec.Dirs(directiveLength.With(map[string]any{"min": 1, "max": 255, "message": "invalid length"})), Type: inUnmarshalNString2string.In},
		}, Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveArg(ctx, args["arg"].(string))
		}},
		{Name: "directiveNullableArg", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg", NilOK: true, Directives: exec.Dirs(directiveRange.With(map[string]any{"min": 0})), Type: inUnmarshalOInt2ᚖint.In},
			{Name: "arg2", NilOK: true, Directives: exec.Dirs(directiveRange.With(map[string]any{"min": 0})), Type: inUnmarshalOInt2ᚖint.In},
			{Name: "arg3", NilOK: true, Directives: exec.Dirs(directiveToNull.With(nil)), Type: inUnmarshalOString2ᚖstring.In},
		}, Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveNullableArg(ctx, args["arg"].(*int), args["arg2"].(*int), args["arg3"].(*string))
		}},
		{Name: "directiveSingleNullableArg", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg1", NilOK: true, Directives: exec.Dirs(directivePopulate.With(map[string]any{"value": "test"}), directiveNoop.With(nil)), Type: inUnmarshalOString2ᚖstring.In},
		}, Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveSingleNullableArg(ctx, args["arg1"].(*string))
		}},
		{Name: "directiveInputNullable", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Type: inUnmarshalOInputDirectives2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInputDirectives.In},
		}, Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveInputNullable(ctx, args["arg"].(*InputDirectives))
		}},
		{Name: "directiveInput", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Type: inUnmarshalNInputDirectives2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInputDirectives.In},
		}, Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveInput(ctx, args["arg"].(InputDirectives))
		}},
		{Name: "directiveInputType", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Directives: exec.Dirs(directiveCustom.With(nil)), Type: inUnmarshalNInnerInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInnerInput.In},
		}, Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveInputType(ctx, args["arg"].(InnerInput))
		}},
		{Name: "directiveInputOuter", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Type: inUnmarshalNOuterWrapperInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterWrapperInput.In},
		}, Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveInputOuter(ctx, args["arg"].(OuterWrapperInput))
		}},
		{Name: "directiveInputWithArgs", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Type: inUnmarshalNInputDirectivesWithArgs2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInputDirectivesWithArgs.In},
		}, Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveInputWithArgs(ctx, args["arg"].(InputDirectivesWithArgs))
		}},
		{Name: "directiveObject", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectObjectDirectives, Directives: exec.Dirs(directiveOrder1.With(map[string]any{"location": "order1_1"}), directiveOrder1.With(map[string]any{"location": "order1_2"}), directiveOrder2.With(map[string]any{"location": "order2_1"}), directiveOrder1.With(map[string]any{"location": "Query_field"})), Out: outMarshalOObjectDirectives2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐObjectDirectives.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveObject(ctx)
		}},
		{Name: "directiveObjectWithCustomGoModel", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectObjectDirectivesWithCustomGoModel, Out: outMarshalOObjectDirectivesWithCustomGoModel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐObjectDirectivesWithCustomGoModel.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveObjectWithCustomGoModel(ctx)
		}},
		{Name: "directiveFieldDef", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "ret", Type: inUnmarshalNString2string.In},
		}, Directives: exec.Dirs(directiveLength.With(map[string]any{"min": 1, "message": "not valid"})), Out: outMarshalNString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveFieldDef(ctx, args["ret"].(string))
		}},
		{Name: "directiveField", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveField(ctx)
		}},
		{Name: "directiveDouble", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Directives: exec.Dirs(directiveDirective1.With(nil), directiveDirective2.With(nil)), Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveDouble(ctx)
		}},
		{Name: "directiveUnimplemented", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Directives: exec.Dirs(directiveUnimplemented.With(nil)), Out: outMarshalOString2ᚖstring.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DirectiveUnimplemented(ctx)
		}},
		{Name: "embeddedCase1", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectEmbeddedCase1, Out: outMarshalOEmbeddedCase12ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐEmbeddedCase1.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().EmbeddedCase1(ctx)
		}},
		{Name: "embeddedCase2", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectEmbeddedCase2, Out: outMarshalOEmbeddedCase22ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐEmbeddedCase2.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().EmbeddedCase2(ctx)
		}},
		{Name: "embeddedCase3", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectEmbeddedCase3, Out: outMarshalOEmbeddedCase32ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐEmbeddedCase3.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().EmbeddedCase3(ctx)
		}},
		{Name: "enumInInput", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "EnumTest", Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalOInputWithEnumValue2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInputWithEnumValue.In},
		}, Out: outMarshalNEnumTest2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐEnumTest.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().EnumInInput(ctx, args["input"].(*InputWithEnumValue))
		}},
		{Name: "searchProducts", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "query", Type: inUnmarshalOString2ᚖstring.In},
			{Name: "category", Type: inUnmarshalOString2ᚖstring.In},
			{Name: "minPrice", Type: inUnmarshalOInt2ᚖint.In},
		}, Out: outMarshalNString2ᚕstringᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, _ any, args map[string]any) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().SearchProducts(ctx, map[string]interface{}{
				"query":    fc.Args["query"].(*string),
				"category": fc.Args["category"].(*string),
				"minPrice": fc.Args["minPrice"].(*int),
			})
		}},
		{Name: "searchRequired", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "name", Type: inUnmarshalNString2string.In},
			{Name: "age", Type: inUnmarshalNInt2int.In},
		}, Out: outMarshalNString2ᚕstringᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, _ any, args map[string]any) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().SearchRequired(ctx, map[string]interface{}{
				"name": fc.Args["name"].(string),
				"age":  fc.Args["age"].(int),
			})
		}},
		{Name: "searchProductsNormal", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "filters", Type: inUnmarshalOSearchFilters2map.In},
		}, Out: outMarshalNString2ᚕstringᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().SearchProductsNormal(ctx, args["filters"].(map[string]any))
		}},
		{Name: "searchWithDefaults", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "query", Type: inUnmarshalOString2ᚖstring.In},
			{Name: "limit", Type: inUnmarshalOInt2ᚖint.In},
			{Name: "includeArchived", Type: inUnmarshalOBoolean2ᚖbool.In},
		}, Out: outMarshalNString2ᚕstringᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, _ any, args map[string]any) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().SearchWithDefaults(ctx, map[string]interface{}{
				"query":           fc.Args["query"].(*string),
				"limit":           fc.Args["limit"].(*int),
				"includeArchived": fc.Args["includeArchived"].(*bool),
			})
		}},
		{Name: "searchMixed", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "query", Type: inUnmarshalOString2ᚖstring.In},
			{Name: "category", Type: inUnmarshalOString2ᚖstring.In},
			{Name: "minPrice", Type: inUnmarshalOInt2ᚖint.In},
			{Name: "limit", Type: inUnmarshalOInt2ᚖint.In},
			{Name: "offset", Type: inUnmarshalOInt2ᚖint.In},
			{Name: "sortBy", Type: inUnmarshalOString2ᚖstring.In},
		}, Out: outMarshalNString2ᚕstringᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, _ any, args map[string]any) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().SearchMixed(ctx, map[string]interface{}{
				"query":    fc.Args["query"].(*string),
				"category": fc.Args["category"].(*string),
				"minPrice": fc.Args["minPrice"].(*int),
			}, fc.Args["limit"].(*int), fc.Args["offset"].(*int), fc.Args["sortBy"].(*string))
		}},
		{Name: "filterProducts", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "query", Type: inUnmarshalOString2ᚖstring.In},
			{Name: "category", Type: inUnmarshalOString2ᚖstring.In},
			{Name: "minPrice", Type: inUnmarshalOInt2ᚖint.In},
		}, Out: outMarshalNString2ᚕstringᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, _ any, args map[string]any) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().FilterProducts(ctx, map[string]interface{}{
				"query":    fc.Args["query"].(*string),
				"category": fc.Args["category"].(*string),
				"minPrice": fc.Args["minPrice"].(*int),
			})
		}},
		{Name: "findProducts", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "query", Type: inUnmarshalOString2ᚖstring.In},
			{Name: "category", Type: inUnmarshalOString2ᚖstring.In},
			{Name: "minPrice", Type: inUnmarshalOInt2ᚖint.In},
		}, Out: outMarshalNString2ᚕstringᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, _ any, args map[string]any) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().FindProducts(ctx, map[string]interface{}{
				"query":    fc.Args["query"].(*string),
				"category": fc.Args["category"].(*string),
				"minPrice": fc.Args["minPrice"].(*int),
			})
		}},
		{Name: "searchWithDirectives", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "oldField", Type: inUnmarshalOString2ᚖstring.In},
			{Name: "newField", Type: inUnmarshalOString2ᚖstring.In},
		}, Out: outMarshalNString2ᚕstringᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, _ any, args map[string]any) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().SearchWithDirectives(ctx, map[string]interface{}{
				"oldField": fc.Args["oldField"].(*string),
				"newField": fc.Args["newField"].(*string),
			})
		}},
		{Name: "shapes", Concurrent: true, IsMethod: true, IsResolver: true, Abstract: "INTERFACE", Out: outMarshalOShape2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐShape.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Shapes(ctx)
		}},
		{Name: "noShape", Concurrent: true, IsMethod: true, IsResolver: true, Abstract: "INTERFACE", Directives: exec.Dirs(directiveMakeNil.With(nil)), Out: outMarshalOShape2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐShape.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().NoShape(ctx)
		}},
		{Name: "node", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Abstract: "INTERFACE", Out: outMarshalNNode2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐNode.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Node(ctx)
		}},
		{Name: "noShapeTypedNil", Concurrent: true, IsMethod: true, IsResolver: true, Abstract: "INTERFACE", Directives: exec.Dirs(directiveMakeTypedNil.With(nil)), Out: outMarshalOShape2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐShape.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().NoShapeTypedNil(ctx)
		}},
		{Name: "animal", Concurrent: true, IsMethod: true, IsResolver: true, Abstract: "INTERFACE", Directives: exec.Dirs(directiveMakeTypedNil.With(nil)), Out: outMarshalOAnimal2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐAnimal.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Animal(ctx)
		}},
		{Name: "notAnInterface", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectBackedByInterface, Out: outMarshalOBackedByInterface2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐBackedByInterface.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().NotAnInterface(ctx)
		}},
		{Name: "dog", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectDog, Out: outMarshalODog2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐDog.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Dog(ctx)
		}},
		{Name: "issue896a", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectCheckIssue896, Out: outMarshalOCheckIssue8962ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐCheckIssue896ᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Issue896a(ctx)
		}},
		{Name: "mapStringInterface", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectMapStringInterfaceType, Args: []exec.Arg[*executionContext]{
			{Name: "in", Type: inUnmarshalOMapStringInterfaceInput2map.In},
		}, Out: outMarshalOMapStringInterfaceType2map.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().MapStringInterface(ctx, args["in"].(map[string]any))
		}},
		{Name: "mapNestedStringInterface", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectMapStringInterfaceType, Args: []exec.Arg[*executionContext]{
			{Name: "in", Type: inUnmarshalONestedMapInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐNestedMapInput.In},
		}, Out: outMarshalOMapStringInterfaceType2map.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().MapNestedStringInterface(ctx, args["in"].(*NestedMapInput))
		}},
		{Name: "mapNestedMapSlice", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Boolean", Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalOMapNestedMapSliceInput2map.In},
		}, Out: outMarshalOBoolean2ᚖbool.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().MapNestedMapSlice(ctx, args["input"].(map[string]any))
		}},
		{Name: "errorBubble", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectError, Out: outMarshalOError2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐError.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().ErrorBubble(ctx)
		}},
		{Name: "errorBubbleList", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectError, Out: outMarshalOError2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐErrorᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().ErrorBubbleList(ctx)
		}},
		{Name: "errorList", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectError, Out: outMarshalOError2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐError.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().ErrorList(ctx)
		}},
		{Name: "errors", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectErrors, Out: outMarshalOErrors2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐErrors.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Errors(ctx)
		}},
		{Name: "valid", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Out: outMarshalNString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Valid(ctx)
		}},
		{Name: "invalid", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Out: outMarshalNString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Invalid(ctx)
		}},
		{Name: "panics", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectPanics, Out: outMarshalOPanics2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPanics.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Panics(ctx)
		}},
		{Name: "primitiveObject", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectPrimitive, Out: outMarshalNPrimitive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPrimitiveᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().PrimitiveObject(ctx)
		}},
		{Name: "primitiveStringObject", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectPrimitiveString, Out: outMarshalNPrimitiveString2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPrimitiveStringᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().PrimitiveStringObject(ctx)
		}},
		{Name: "ptrToAnyContainer", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectPtrToAnyContainer, Out: outMarshalNPtrToAnyContainer2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPtrToAnyContainer.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().PtrToAnyContainer(ctx)
		}},
		{Name: "ptrToSliceContainer", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectPtrToSliceContainer, Out: outMarshalNPtrToSliceContainer2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPtrToSliceContainer.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().PtrToSliceContainer(ctx)
		}},
		{Name: "infinity", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Float", Out: outMarshalNFloat2float64.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Infinity(ctx)
		}},
		{Name: "stringFromContextInterface", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "StringFromContextInterface", Out: outMarshalNStringFromContextInterface2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐStringFromContextInterface.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().StringFromContextInterface(ctx)
		}},
		{Name: "stringFromContextFunction", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "StringFromContextFunction", Out: outMarshalNStringFromContextFunction2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().StringFromContextFunction(ctx)
		}},
		{Name: "defaultScalar", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "DefaultScalarImplementation", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Type: inUnmarshalNDefaultScalarImplementation2string.In},
		}, Out: outMarshalNDefaultScalarImplementation2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().DefaultScalar(ctx, args["arg"].(string))
		}},
		{Name: "skipInclude", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectSkipIncludeTestType, Out: outMarshalOSkipIncludeTestType2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐSkipIncludeTestType.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().SkipInclude(ctx)
		}},
		{Name: "slices", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectSlices, Out: outMarshalOSlices2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐSlices.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Slices(ctx)
		}},
		{Name: "scalarSlice", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Bytes", Out: outMarshalNBytes2ᚕbyte.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().ScalarSlice(ctx)
		}},
		{Name: "fallback", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "FallbackToStringEncoding", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Type: inUnmarshalNFallbackToStringEncoding2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐFallbackToStringEncoding.In},
		}, Out: outMarshalNFallbackToStringEncoding2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐFallbackToStringEncoding.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Fallback(ctx, args["arg"].(FallbackToStringEncoding))
		}},
		{Name: "optionalUnion", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "TestUnion", Out: outMarshalOTestUnion2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐTestUnion.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().OptionalUnion(ctx)
		}},
		{Name: "vOkCaseValue", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectVOkCaseValue, Out: outMarshalOVOkCaseValue2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐVOkCaseValue.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().VOkCaseValue(ctx)
		}},
		{Name: "vOkCaseNil", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectVOkCaseNil, Out: outMarshalOVOkCaseNil2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐVOkCaseNil.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().VOkCaseNil(ctx)
		}},
		{Name: "validType", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectValidType, Out: outMarshalOValidType2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐValidType.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().ValidType(ctx)
		}},
		{Name: "variadicModel", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectVariadicModel, Out: outMarshalOVariadicModel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐVariadicModel.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().VariadicModel(ctx)
		}},
		{Name: "wrappedStruct", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectWrappedStruct, Out: outMarshalNWrappedStruct2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐWrappedStruct.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().WrappedStruct(ctx)
		}},
		{Name: "wrappedScalar", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "WrappedScalar", Out: outMarshalNWrappedScalar2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚋotherpkgᚐScalar.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().WrappedScalar(ctx)
		}},
		{Name: "wrappedMap", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectWrappedMap, Out: outMarshalNWrappedMap2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐWrappedMap.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().WrappedMap(ctx)
		}},
		{Name: "wrappedSlice", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectWrappedSlice, Out: outMarshalNWrappedSlice2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐWrappedSlice.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().WrappedSlice(ctx)
		}},
		{Name: "__type", IsMethod: true, Children: &object__Type, Args: []exec.Arg[*executionContext]{
			{Name: "name", Type: inUnmarshalNString2string.In},
		}, Out: outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.IntrospectType(args["name"].(string))
		}},
		{Name: "__schema", IsMethod: true, Children: &object__Schema, Out: outMarshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.IntrospectSchema()
		}},
	})
}

var objectSubscription = exec.Object[*executionContext]{Name: "Subscription", Implementors: []string{"Subscription"}, Root: true}

func init() {
	objectSubscription.Init([]exec.Field[*executionContext]{
		{Name: "updated", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Out: outMarshalNString2string.Out, Stream: exec.StreamOf[string](), Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Subscription().Updated(ctx)
		}},
		{Name: "initPayload", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Out: outMarshalNString2string.Out, Stream: exec.StreamOf[string](), Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Subscription().InitPayload(ctx)
		}},
		{Name: "directiveArg", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg", Directives: exec.Dirs(directiveLength.With(map[string]any{"min": 1, "max": 255, "message": "invalid length"})), Type: inUnmarshalNString2string.In},
		}, Out: outMarshalOString2ᚖstring.Out, Stream: exec.StreamOf[*string](), Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Subscription().DirectiveArg(ctx, args["arg"].(string))
		}},
		{Name: "directiveNullableArg", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "arg", NilOK: true, Directives: exec.Dirs(directiveRange.With(map[string]any{"min": 0})), Type: inUnmarshalOInt2ᚖint.In},
			{Name: "arg2", NilOK: true, Directives: exec.Dirs(directiveRange.With(map[string]any{"min": 0})), Type: inUnmarshalOInt2ᚖint.In},
			{Name: "arg3", NilOK: true, Directives: exec.Dirs(directiveToNull.With(nil)), Type: inUnmarshalOString2ᚖstring.In},
		}, Out: outMarshalOString2ᚖstring.Out, Stream: exec.StreamOf[*string](), Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Subscription().DirectiveNullableArg(ctx, args["arg"].(*int), args["arg2"].(*int), args["arg3"].(*string))
		}},
		{Name: "directiveDouble", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Directives: exec.Dirs(directiveDirective1.With(nil), directiveDirective2.With(nil)), Out: outMarshalOString2ᚖstring.Out, Stream: exec.StreamOf[*string](), Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Subscription().DirectiveDouble(ctx)
		}},
		{Name: "directiveUnimplemented", Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Directives: exec.Dirs(directiveUnimplemented.With(nil)), Out: outMarshalOString2ᚖstring.Out, Stream: exec.StreamOf[*string](), Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Subscription().DirectiveUnimplemented(ctx)
		}},
		{Name: "issue896b", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectCheckIssue896, Out: outMarshalOCheckIssue8962ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐCheckIssue896.Out, Stream: exec.StreamOf[[]*CheckIssue896](), Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Subscription().Issue896b(ctx)
		}},
		{Name: "errorRequired", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectError, Out: outMarshalNError2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐError.Out, Stream: exec.StreamOf[*Error](), Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Subscription().ErrorRequired(ctx)
		}},
	})
}

func _Subscription(ctx context.Context, ec *executionContext, sel ast.SelectionSet) func(ctx context.Context) graphql.Marshaler {
	return objectSubscription.Subscribe(ctx, ec, sel)
}

var objectUser = exec.Object[*executionContext]{Name: "User", Implementors: []string{"User"}}

func init() {
	objectUser.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "Int"}, outMarshalNInt2int, func(obj *User) int { return obj.ID }),
		{Name: "friends", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectUser, Out: outMarshalNUser2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐUserᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.User().Friends(ctx, obj.(*User))
		}},
		exec.FieldGet(exec.Field[*executionContext]{Name: "created", NonNull: true, Leaf: "Time"}, outMarshalNTime2timeᚐTime, func(obj *User) time.Time { return obj.Created }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "updated", Leaf: "Time"}, outMarshalOTime2ᚖtimeᚐTime, func(obj *User) *time.Time { return obj.Updated }),
		{Name: "pets", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectPet, Args: []exec.Arg[*executionContext]{
			{Name: "limit", Type: inUnmarshalOInt2ᚖint.In},
		}, Out: outMarshalOPet2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPetᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.User().Pets(ctx, obj.(*User), args["limit"].(*int))
		}},
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var unmarshalNInnerInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInnerInput = exec.UnmarshalInput[*executionContext, InnerInput](&inputInnerInput)

var unmarshalNInnerInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInnerInput = exec.UnmarshalInputPtr[*executionContext, InnerInput](false, &inputInnerInput)

var marshalNInnerObject2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐInnerObject = exec.MarshalObjectPtr[*executionContext, InnerObject](true, &objectInnerObject)

var unmarshalNOmittableInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOmittableInput = exec.UnmarshalInput[*executionContext, OmittableInput](&inputOmittableInput)

var marshalNPet2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPet = exec.MarshalObjectPtr[*executionContext, Pet](true, &objectPet)

var unmarshalNRecursiveInputSlice2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐRecursiveInputSlice = exec.UnmarshalInput[*executionContext, RecursiveInputSlice](&inputRecursiveInputSlice)

var unmarshalNTime2timeᚐTime = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalTime)

var marshalNTime2timeᚐTime = exec.MarshalFunc[*executionContext](true, graphql.MarshalTime)

var unmarshalNUUID2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalNUUID2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalString)

var marshalNUser2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐUserᚄ = exec.MarshalList(marshalNUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐUser, exec.ListOptions{ElemNonNull: true})

var marshalNUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐUser = exec.MarshalObjectPtr[*executionContext, User](true, &objectUser)

var marshalOAutobind2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐAutobind = exec.MarshalObjectPtr[*executionContext, Autobind](false, &objectAutobind)

func unmarshalOChanges2map(ctx context.Context, ec *executionContext, v any) (map[string]any, error) {
	if v == nil {
		return nil, nil
	}
	res, err := exec.InputValue[*executionContext, map[string]any](ctx, ec, &inputChanges, v)
	return res, graphql.ErrorOnPath(ctx, err)
}

var marshalOInvalidIdentifier2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚋinvalidᚑpackagenameᚐInvalidIdentifier = exec.MarshalObjectPtr[*executionContext, invalid_packagename.InvalidIdentifier](false, &objectInvalidIdentifier)

var marshalOIt2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚋintrospectionᚐIt = exec.MarshalObjectPtr[*executionContext, introspection1.It](false, &objectIt)

var marshalOModelMethods2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐModelMethods = exec.MarshalObjectPtr[*executionContext, ModelMethods](false, &objectModelMethods)

var unmarshalOOuterInput2ᚕᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterInput = exec.UnmarshalList(true, unmarshalOOuterInput2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterInput)

var unmarshalOOuterInput2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterInput = exec.UnmarshalList(true, unmarshalOOuterInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterInput)

var unmarshalOOuterInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterInput = exec.UnmarshalInputPtr[*executionContext, OuterInput](true, &inputOuterInput)

var marshalOOuterObject2ᚕᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterObject = exec.MarshalList(marshalOOuterObject2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterObject, exec.ListOptions{Nullable: true})

var marshalOOuterObject2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterObject = exec.MarshalList(marshalOOuterObject2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterObject, exec.ListOptions{Nullable: true})

var marshalOOuterObject2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐOuterObject = exec.MarshalObjectPtr[*executionContext, OuterObject](false, &objectOuterObject)

var marshalOPet2ᚕᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPetᚄ = exec.MarshalList(marshalNPet2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐPet, exec.ListOptions{Nullable: true, ElemNonNull: true})

var unmarshalORecursiveInputSlice2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐRecursiveInputSliceᚄ = exec.UnmarshalList(true, unmarshalNRecursiveInputSlice2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐRecursiveInputSlice)

var unmarshalORecursiveInputSlice2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐRecursiveInputSlice = exec.UnmarshalInputPtr[*executionContext, RecursiveInputSlice](true, &inputRecursiveInputSlice)

var unmarshalOStatus2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐStatus = exec.UnmarshalGQLPtr[*executionContext, Status](true)

var marshalOStatus2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐStatus = exec.MarshalSelfPtr[*executionContext, Status](false)

var unmarshalOThirdParty2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐThirdParty = exec.UnmarshalFuncPtr[*executionContext](true, UnmarshalThirdParty)

var marshalOThirdParty2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐThirdParty = exec.MarshalFuncPtr[*executionContext](false, MarshalThirdParty)

var unmarshalOTime2ᚖtimeᚐTime = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalTime)

var marshalOTime2ᚖtimeᚐTime = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalTime)

// endregion ***************************** type.gotpl *****************************
