//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"
	"reflect"
	"time"

	introspection1 "github.com/99designs/gqlgen/codegen/testserver/followschema/introspection"
	invalid_packagename "github.com/99designs/gqlgen/codegen/testserver/followschema/invalid-packagename"
	"github.com/99designs/gqlgen/codegen/testserver/followschema/otherpkg"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/99designs/gqlgen/graphql/introspection"
	"github.com/vektah/gqlparser/v2/ast"
)

type ForcedResolverResolver interface {
	Field(ctx context.Context, obj *ForcedResolver) (*Circle, error)
}
type ModelMethodsResolver interface {
	ResolverField(ctx context.Context, obj *ModelMethods) (bool, error)
}
type PetResolver interface {
	Friends(ctx context.Context, obj *Pet, limit *int) ([]*Pet, error)
}
type QueryResolver interface {
	InvalidIdentifier(ctx context.Context) (*invalid_packagename.InvalidIdentifier, error)
	Collision(ctx context.Context) (*introspection1.It, error)
	MapInput(ctx context.Context, input map[string]any) (*bool, error)
	Recursive(ctx context.Context, input *RecursiveInputSlice) (*bool, error)
	NestedInputs(ctx context.Context, input [][]*OuterInput) (*bool, error)
	NestedOutputs(ctx context.Context) ([][]*OuterObject, error)
	ModelMethods(ctx context.Context) (*ModelMethods, error)
	User(ctx context.Context, id int) (*User, error)
	NullableArg(ctx context.Context, arg *int) (*string, error)
	InputSlice(ctx context.Context, arg []string) (bool, error)
	InputNullableSlice(ctx context.Context, arg []string) (bool, error)
	InputOmittable(ctx context.Context, arg OmittableInput) (string, error)
	ShapeUnion(ctx context.Context) (ShapeUnion, error)
	Autobind(ctx context.Context) (*Autobind, error)
	DeprecatedField(ctx context.Context) (string, error)
	FieldWithDeprecatedArg(ctx context.Context, oldArg *int, newArg *int) (*string, error)
	Overlapping(ctx context.Context) (*OverlappingFields, error)
	DefaultParameters(ctx context.Context, falsyBoolean *bool, truthyBoolean *bool) (*DefaultParametersMirror, error)
	DeferSingle(ctx context.Context) (*DeferModel, error)
	DeferMultiple(ctx context.Context) ([]*DeferModel, error)
	DirectiveArg(ctx context.Context, arg string) (*string, error)
	DirectiveNullableArg(ctx context.Context, arg *int, arg2 *int, arg3 *string) (*string, error)
	DirectiveSingleNullableArg(ctx context.Context, arg1 *string) (*string, error)
	DirectiveInputNullable(ctx context.Context, arg *InputDirectives) (*string, error)
	DirectiveInput(ctx context.Context, arg InputDirectives) (*string, error)
	DirectiveInputType(ctx context.Context, arg InnerInput) (*string, error)
	DirectiveInputOuter(ctx context.Context, arg OuterWrapperInput) (*string, error)
	DirectiveInputWithArgs(ctx context.Context, arg InputDirectivesWithArgs) (*string, error)
	DirectiveObject(ctx context.Context) (*ObjectDirectives, error)
	DirectiveObjectWithCustomGoModel(ctx context.Context) (*ObjectDirectivesWithCustomGoModel, error)
	DirectiveFieldDef(ctx context.Context, ret string) (string, error)
	DirectiveField(ctx context.Context) (*string, error)
	DirectiveDouble(ctx context.Context) (*string, error)
	DirectiveUnimplemented(ctx context.Context) (*string, error)
	EmbeddedCase1(ctx context.Context) (*EmbeddedCase1, error)
	EmbeddedCase2(ctx context.Context) (*EmbeddedCase2, error)
	EmbeddedCase3(ctx context.Context) (*EmbeddedCase3, error)
	EnumInInput(ctx context.Context, input *InputWithEnumValue) (EnumTest, error)
	SearchProducts(ctx context.Context, filters map[string]interface{}) ([]string, error)
	SearchRequired(ctx context.Context, filters map[string]interface{}) ([]string, error)
	SearchProductsNormal(ctx context.Context, filters map[string]any) ([]string, error)
	SearchWithDefaults(ctx context.Context, filters map[string]interface{}) ([]string, error)
	SearchMixed(ctx context.Context, filters map[string]interface{}, limit *int, offset *int, sortBy *string) ([]string, error)
	FilterProducts(ctx context.Context, filters map[string]interface{}) ([]string, error)
	FindProducts(ctx context.Context, filters map[string]interface{}) ([]string, error)
	SearchWithDirectives(ctx context.Context, input map[string]interface{}) ([]string, error)
	Shapes(ctx context.Context) ([]Shape, error)
	NoShape(ctx context.Context) (Shape, error)
	Node(ctx context.Context) (Node, error)
	NoShapeTypedNil(ctx context.Context) (Shape, error)
	Animal(ctx context.Context) (Animal, error)
	NotAnInterface(ctx context.Context) (BackedByInterface, error)
	Dog(ctx context.Context) (*Dog, error)
	Issue896a(ctx context.Context) ([]*CheckIssue896, error)
	MapStringInterface(ctx context.Context, in map[string]any) (map[string]any, error)
	MapNestedStringInterface(ctx context.Context, in *NestedMapInput) (map[string]any, error)
	MapNestedMapSlice(ctx context.Context, input map[string]any) (*bool, error)
	ErrorBubble(ctx context.Context) (*Error, error)
	ErrorBubbleList(ctx context.Context) ([]*Error, error)
	ErrorList(ctx context.Context) ([]*Error, error)
	Errors(ctx context.Context) (*Errors, error)
	Valid(ctx context.Context) (string, error)
	Invalid(ctx context.Context) (string, error)
	Panics(ctx context.Context) (*Panics, error)
	PrimitiveObject(ctx context.Context) ([]Primitive, error)
	PrimitiveStringObject(ctx context.Context) ([]PrimitiveString, error)
	PtrToAnyContainer(ctx context.Context) (*PtrToAnyContainer, error)
	PtrToSliceContainer(ctx context.Context) (*PtrToSliceContainer, error)
	Infinity(ctx context.Context) (float64, error)
	StringFromContextInterface(ctx context.Context) (*StringFromContextInterface, error)
	StringFromContextFunction(ctx context.Context) (string, error)
	DefaultScalar(ctx context.Context, arg string) (string, error)
	SkipInclude(ctx context.Context) (*SkipIncludeTestType, error)
	Slices(ctx context.Context) (*Slices, error)
	ScalarSlice(ctx context.Context) ([]byte, error)
	Fallback(ctx context.Context, arg FallbackToStringEncoding) (FallbackToStringEncoding, error)
	OptionalUnion(ctx context.Context) (TestUnion, error)
	VOkCaseValue(ctx context.Context) (*VOkCaseValue, error)
	VOkCaseNil(ctx context.Context) (*VOkCaseNil, error)
	ValidType(ctx context.Context) (*ValidType, error)
	VariadicModel(ctx context.Context) (*VariadicModel, error)
	WrappedStruct(ctx context.Context) (*WrappedStruct, error)
	WrappedScalar(ctx context.Context) (otherpkg.Scalar, error)
	WrappedMap(ctx context.Context) (WrappedMap, error)
	WrappedSlice(ctx context.Context) (WrappedSlice, error)
}
type SubscriptionResolver interface {
	Updated(ctx context.Context) (<-chan string, error)
	InitPayload(ctx context.Context) (<-chan string, error)
	DirectiveArg(ctx context.Context, arg string) (<-chan *string, error)
	DirectiveNullableArg(ctx context.Context, arg *int, arg2 *int, arg3 *string) (<-chan *string, error)
	DirectiveDouble(ctx context.Context) (<-chan *string, error)
	DirectiveUnimplemented(ctx context.Context) (<-chan *string, error)
	Issue896b(ctx context.Context) (<-chan []*CheckIssue896, error)
	ErrorRequired(ctx context.Context) (<-chan *Error, error)
}
type UserResolver interface {
	Friends(ctx context.Context, obj *User) ([]*User, error)

	Pets(ctx context.Context, obj *User, limit *int) ([]*Pet, error)
}

// UnmarshalChanges unmarshals raw into the Changes input type, as graphql.UnmarshalNamedInputFromContext does.
func UnmarshalChanges(ctx context.Context, raw any) (out map[string]any, err error) {
	err = graphql.UnmarshalNamedInputFromContext(ctx, "Changes", raw, &out)
	return out, err
}

// UnmarshalInnerInput unmarshals raw into the InnerInput input type, as graphql.UnmarshalNamedInputFromContext does.
func UnmarshalInnerInput(ctx context.Context, raw any) (out InnerInput, err error) {
	err = graphql.UnmarshalNamedInputFromContext(ctx, "InnerInput", raw, &out)
	return out, err
}

// UnmarshalOmittableInput unmarshals raw into the OmittableInput input type, as graphql.UnmarshalNamedInputFromContext does.
func UnmarshalOmittableInput(ctx context.Context, raw any) (out OmittableInput, err error) {
	err = graphql.UnmarshalNamedInputFromContext(ctx, "OmittableInput", raw, &out)
	return out, err
}

// UnmarshalOuterInput unmarshals raw into the OuterInput input type, as graphql.UnmarshalNamedInputFromContext does.
func UnmarshalOuterInput(ctx context.Context, raw any) (out OuterInput, err error) {
	err = graphql.UnmarshalNamedInputFromContext(ctx, "OuterInput", raw, &out)
	return out, err
}

// UnmarshalRecursiveInputSlice unmarshals raw into the RecursiveInputSlice input type, as graphql.UnmarshalNamedInputFromContext does.
func UnmarshalRecursiveInputSlice(ctx context.Context, raw any) (out RecursiveInputSlice, err error) {
	err = graphql.UnmarshalNamedInputFromContext(ctx, "RecursiveInputSlice", raw, &out)
	return out, err
}

func (t *tables) initObjectAutobind() {
	t.objectAutobind.Init(t.schema, "Autobind", _Autobind_resolve, []tableField{
		{Name: "int", Out: t.marshalNInt2int.Out},
		{Name: "int32", Out: t.marshalNInt2int32.Out},
		{Name: "int64", Out: t.marshalNInt2int64.Out},
		{Name: "idStr", Out: t.marshalNID2string.Out},
		{Name: "idInt", Out: t.marshalNID2int.Out},
	})
	t.objectEmbeddedPointer.Init(t.schema, "EmbeddedPointer", _EmbeddedPointer_resolve, []tableField{
		{Name: "ID", Out: t.marshalOString2string.Out},
		{Name: "Title", Out: t.marshalOString2string.Out},
	})
	t.objectForcedResolver.Init(t.schema, "ForcedResolver", _ForcedResolver_resolve, []tableField{
		{Name: "field", IsResolver: true, Type: (**Circle)(nil)},
	})
	t.objectInnerObject.Init(t.schema, "InnerObject", _InnerObject_resolve, []tableField{
		{Name: "id", Out: t.marshalNInt2int.Out},
	})
	t.objectInvalidIdentifier.Init(t.schema, "InvalidIdentifier", _InvalidIdentifier_resolve, []tableField{
		{Name: "id", Out: t.marshalNInt2int.Out},
	})
	t.objectIt.Init(t.schema, "It", _It_resolve, []tableField{
		{Name: "id", Out: t.marshalNID2string.Out},
	})
	t.objectModelMethods.Init(t.schema, "ModelMethods", _ModelMethods_resolve, []tableField{
		{Name: "resolverField", IsResolver: true, Out: t.marshalNBoolean2bool.Out},
		{Name: "noContext", IsMethod: true, Out: t.marshalNBoolean2bool.Out},
		{Name: "withContext", Concurrent: true, IsMethod: true, Out: t.marshalNBoolean2bool.Out},
	})
	t.objectOuterObject.Init(t.schema, "OuterObject", _OuterObject_resolve, []tableField{
		{Name: "inner", Type: (**InnerObject)(nil)},
	})
}

func _Autobind_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*Autobind)
	switch fieldIndex {
	case 0:
		var v int = obj.Int
		return v, nil
	case 1:
		var v int32 = obj.Int32
		return v, nil
	case 2:
		var v int64 = obj.Int64
		return v, nil
	case 3:
		var v string = obj.IdStr
		return v, nil
	case 4:
		var v int = obj.IdInt
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func _EmbeddedPointer_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*EmbeddedPointerModel)
	switch fieldIndex {
	case 0:
		var v string = obj.ID
		return v, nil
	case 1:
		var v string = obj.Title
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func _ForcedResolver_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*ForcedResolver)
	switch fieldIndex {
	case 0:
		return ec.Resolvers.ForcedResolver().Field(ctx, obj)
	}
	return nil, exec.NoField(fieldIndex)
}

func _InnerObject_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*InnerObject)
	switch fieldIndex {
	case 0:
		var v int = obj.ID
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func _InvalidIdentifier_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*invalid_packagename.InvalidIdentifier)
	switch fieldIndex {
	case 0:
		var v int = obj.ID
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func _It_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection1.It)
	switch fieldIndex {
	case 0:
		var v string = obj.ID
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func _ModelMethods_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*ModelMethods)
	switch fieldIndex {
	case 0:
		return ec.Resolvers.ModelMethods().ResolverField(ctx, obj)
	case 1:
		var v bool = obj.NoContext()
		return v, nil
	case 2:
		return obj.WithContext(ctx), nil
	}
	return nil, exec.NoField(fieldIndex)
}

func _OuterObject_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*OuterObject)
	switch fieldIndex {
	case 0:
		var v *InnerObject = obj.Inner
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func (t *tables) initObjectPet() {
	t.objectPet.Init(t.schema, "Pet", _Pet_resolve, []tableField{
		{Name: "id", Out: t.marshalNInt2int.Out},
		{Name: "friends", IsResolver: true, Args: []any{t.unmarshalOInt2ᚖint.In}, Type: (*[]*Pet)(nil)},
	})
}

func _Pet_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*Pet)
	switch fieldIndex {
	case 0:
		var v int = obj.ID
		return v, nil
	case 1:
		return ec.Resolvers.Pet().Friends(ctx, obj, fieldArgs["limit"].(*int))
	}
	return nil, exec.NoField(fieldIndex)
}

func (t *tables) initObjectQuery() {
	t.objectQuery.Init(t.schema, "Query", _Query_resolve, []tableField{
		{Name: "invalidIdentifier", IsResolver: true, Type: (**invalid_packagename.InvalidIdentifier)(nil)},
		{Name: "collision", IsResolver: true, Type: (**introspection1.It)(nil)},
		{Name: "mapInput", IsResolver: true, Args: []any{t.inUnmarshalOChanges2map.In}, Out: t.marshalOBoolean2ᚖbool.Out},
		{Name: "recursive", IsResolver: true, Args: []any{(**RecursiveInputSlice)(nil)}, Out: t.marshalOBoolean2ᚖbool.Out},
		{Name: "nestedInputs", IsResolver: true, Args: []any{t.unmarshalOOuterInput2ᚕᚕᚖfollowschemaᚐOuterInput}, Out: t.marshalOBoolean2ᚖbool.Out},
		{Name: "nestedOutputs", IsResolver: true, Out: t.marshalOOuterObject2ᚕᚕᚖfollowschemaᚐOuterObject},
		{Name: "modelMethods", IsResolver: true, Type: (**ModelMethods)(nil)},
		{Name: "user", IsResolver: true, Args: []any{t.unmarshalNInt2int.In}, Type: (**User)(nil)},
		{Name: "nullableArg", IsResolver: true, Args: []any{t.unmarshalOInt2ᚖint.In}, Out: t.marshalOString2ᚖstring.Out},
		{Name: "inputSlice", IsResolver: true, Args: []any{t.unmarshalNString2ᚕstringᚄ}, Out: t.marshalNBoolean2bool.Out},
		{Name: "inputNullableSlice", IsResolver: true, Args: []any{t.unmarshalOString2ᚕstringᚄ.In}, Out: t.marshalNBoolean2bool.Out},
		{Name: "inputOmittable", IsResolver: true, Args: []any{(*OmittableInput)(nil)}, Out: t.marshalNString2string.Out},
		{Name: "shapeUnion", IsResolver: true, Out: t.marshalNShapeUnion2followschemaᚐShapeUnion.Out},
		{Name: "autobind", IsResolver: true, Type: (**Autobind)(nil)},
		{Name: "deprecatedField", IsResolver: true, Out: t.marshalNString2string.Out},
		{Name: "fieldWithDeprecatedArg", IsResolver: true, Args: []any{t.unmarshalOInt2ᚖint.In, t.unmarshalOInt2ᚖint.In}, Out: t.marshalOString2ᚖstring.Out},
		{Name: "overlapping", IsResolver: true, Type: (**OverlappingFields)(nil)},
		{Name: "defaultParameters", IsResolver: true, Args: []any{t.unmarshalOBoolean2ᚖbool.In, t.unmarshalOBoolean2ᚖbool.In}, Type: (**DefaultParametersMirror)(nil)},
		{Name: "deferSingle", IsResolver: true, Type: (**DeferModel)(nil)},
		{Name: "deferMultiple", IsResolver: true, Type: (*[]*DeferModel)(nil)},
		{Name: "directiveArg", IsResolver: true, Args: []any{t.unmarshalNString2string.In}, Out: t.marshalOString2ᚖstring.Out},
		{Name: "directiveNullableArg", IsResolver: true, Args: []any{t.unmarshalOInt2ᚖint.In, t.unmarshalOInt2ᚖint.In, t.unmarshalOString2ᚖstring.In}, Out: t.marshalOString2ᚖstring.Out},
		{Name: "directiveSingleNullableArg", IsResolver: true, Args: []any{t.unmarshalOString2ᚖstring.In}, Out: t.marshalOString2ᚖstring.Out},
		{Name: "directiveInputNullable", IsResolver: true, Args: []any{(**InputDirectives)(nil)}, Out: t.marshalOString2ᚖstring.Out},
		{Name: "directiveInput", IsResolver: true, Args: []any{(*InputDirectives)(nil)}, Out: t.marshalOString2ᚖstring.Out},
		{Name: "directiveInputType", IsResolver: true, Args: []any{(*InnerInput)(nil)}, Out: t.marshalOString2ᚖstring.Out},
		{Name: "directiveInputOuter", IsResolver: true, Args: []any{(*OuterWrapperInput)(nil)}, Out: t.marshalOString2ᚖstring.Out},
		{Name: "directiveInputWithArgs", IsResolver: true, Args: []any{(*InputDirectivesWithArgs)(nil)}, Out: t.marshalOString2ᚖstring.Out},
		{Name: "directiveObject", IsResolver: true, Type: (**ObjectDirectives)(nil)},
		{Name: "directiveObjectWithCustomGoModel", IsResolver: true, Type: (**ObjectDirectivesWithCustomGoModel)(nil)},
		{Name: "directiveFieldDef", IsResolver: true, Args: []any{t.unmarshalNString2string.In}, Out: t.marshalNString2string.Out},
		{Name: "directiveField", IsResolver: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "directiveDouble", IsResolver: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "directiveUnimplemented", IsResolver: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "embeddedCase1", IsResolver: true, Type: (**EmbeddedCase1)(nil)},
		{Name: "embeddedCase2", IsResolver: true, Type: (**EmbeddedCase2)(nil)},
		{Name: "embeddedCase3", IsResolver: true, Type: (**EmbeddedCase3)(nil)},
		{Name: "enumInInput", IsResolver: true, Args: []any{(**InputWithEnumValue)(nil)}, Type: (*EnumTest)(nil)},
		{Name: "searchProducts", IsResolver: true, Args: []any{t.unmarshalOString2ᚖstring.In, t.unmarshalOString2ᚖstring.In, t.unmarshalOInt2ᚖint.In}, Out: t.marshalNString2ᚕstringᚄ},
		{Name: "searchRequired", IsResolver: true, Args: []any{t.unmarshalNString2string.In, t.unmarshalNInt2int.In}, Out: t.marshalNString2ᚕstringᚄ},
		{Name: "searchProductsNormal", IsResolver: true, Args: []any{t.inUnmarshalOSearchFilters2map.In}, Out: t.marshalNString2ᚕstringᚄ},
		{Name: "searchWithDefaults", IsResolver: true, Args: []any{t.unmarshalOString2ᚖstring.In, t.unmarshalOInt2ᚖint.In, t.unmarshalOBoolean2ᚖbool.In}, Out: t.marshalNString2ᚕstringᚄ},
		{Name: "searchMixed", IsResolver: true, Args: []any{t.unmarshalOString2ᚖstring.In, t.unmarshalOString2ᚖstring.In, t.unmarshalOInt2ᚖint.In, t.unmarshalOInt2ᚖint.In, t.unmarshalOInt2ᚖint.In, t.unmarshalOString2ᚖstring.In}, Out: t.marshalNString2ᚕstringᚄ},
		{Name: "filterProducts", IsResolver: true, Args: []any{t.unmarshalOString2ᚖstring.In, t.unmarshalOString2ᚖstring.In, t.unmarshalOInt2ᚖint.In}, Out: t.marshalNString2ᚕstringᚄ},
		{Name: "findProducts", IsResolver: true, Args: []any{t.unmarshalOString2ᚖstring.In, t.unmarshalOString2ᚖstring.In, t.unmarshalOInt2ᚖint.In}, Out: t.marshalNString2ᚕstringᚄ},
		{Name: "searchWithDirectives", IsResolver: true, Args: []any{t.unmarshalOString2ᚖstring.In, t.unmarshalOString2ᚖstring.In}, Out: t.marshalNString2ᚕstringᚄ},
		{Name: "shapes", IsResolver: true, Out: t.marshalOShape2ᚕfollowschemaᚐShape},
		{Name: "noShape", IsResolver: true, Out: t.marshalOShape2followschemaᚐShape.Out},
		{Name: "node", IsResolver: true, Out: t.marshalNNode2followschemaᚐNode.Out},
		{Name: "noShapeTypedNil", IsResolver: true, Out: t.marshalOShape2followschemaᚐShape.Out},
		{Name: "animal", IsResolver: true, Out: t.marshalOAnimal2followschemaᚐAnimal.Out},
		{Name: "notAnInterface", IsResolver: true, Out: t.outMarshalOBackedByInterface2followschemaᚐBackedByInterface.Out},
		{Name: "dog", IsResolver: true, Type: (**Dog)(nil)},
		{Name: "issue896a", IsResolver: true, Type: (*[]*CheckIssue896)(nil)},
		{Name: "mapStringInterface", IsResolver: true, Args: []any{t.inUnmarshalOMapStringInterfaceInput2map.In}, Out: t.outMarshalOMapStringInterfaceType2map.Out},
		{Name: "mapNestedStringInterface", IsResolver: true, Args: []any{(**NestedMapInput)(nil)}, Out: t.outMarshalOMapStringInterfaceType2map.Out},
		{Name: "mapNestedMapSlice", IsResolver: true, Args: []any{t.inUnmarshalOMapNestedMapSliceInput2map.In}, Out: t.marshalOBoolean2ᚖbool.Out},
		{Name: "errorBubble", IsResolver: true, Type: (**Error)(nil)},
		{Name: "errorBubbleList", IsResolver: true, Type: (*[]*Error)(nil)},
		{Name: "errorList", IsResolver: true, Type: (*[]*Error)(nil)},
		{Name: "errors", IsResolver: true, Type: (**Errors)(nil)},
		{Name: "valid", IsResolver: true, Out: t.marshalNString2string.Out},
		{Name: "invalid", IsResolver: true, Out: t.marshalNString2string.Out},
		{Name: "panics", IsResolver: true, Type: (**Panics)(nil)},
		{Name: "primitiveObject", IsResolver: true, Out: t.marshalNPrimitive2ᚕfollowschemaᚐPrimitiveᚄ},
		{Name: "primitiveStringObject", IsResolver: true, Out: t.marshalNPrimitiveString2ᚕfollowschemaᚐPrimitiveStringᚄ},
		{Name: "ptrToAnyContainer", IsResolver: true, Type: (**PtrToAnyContainer)(nil)},
		{Name: "ptrToSliceContainer", IsResolver: true, Type: (**PtrToSliceContainer)(nil)},
		{Name: "infinity", IsResolver: true, Out: t.marshalNFloat2float64.Out},
		{Name: "stringFromContextInterface", IsResolver: true, Out: t.outMarshalNStringFromContextInterface2ᚖfollowschemaᚐStringFromContextInterface.Out},
		{Name: "stringFromContextFunction", IsResolver: true, Out: t.marshalNStringFromContextFunction2string.Out},
		{Name: "defaultScalar", IsResolver: true, Args: []any{t.unmarshalNDefaultScalarImplementation2string.In}, Out: t.marshalNDefaultScalarImplementation2string.Out},
		{Name: "skipInclude", IsResolver: true, Type: (**SkipIncludeTestType)(nil)},
		{Name: "slices", IsResolver: true, Type: (**Slices)(nil)},
		{Name: "scalarSlice", IsResolver: true, Out: t.outMarshalNBytes2ᚕbyte.Out},
		{Name: "fallback", IsResolver: true, Args: []any{t.unmarshalNFallbackToStringEncoding2followschemaᚐFallbackToStringEncoding}, Out: t.marshalNFallbackToStringEncoding2followschemaᚐFallbackToStringEncoding},
		{Name: "optionalUnion", IsResolver: true, Out: t.marshalOTestUnion2followschemaᚐTestUnion.Out},
		{Name: "vOkCaseValue", IsResolver: true, Type: (**VOkCaseValue)(nil)},
		{Name: "vOkCaseNil", IsResolver: true, Type: (**VOkCaseNil)(nil)},
		{Name: "validType", IsResolver: true, Type: (**ValidType)(nil)},
		{Name: "variadicModel", IsResolver: true, Type: (**VariadicModel)(nil)},
		{Name: "wrappedStruct", IsResolver: true, Type: (**WrappedStruct)(nil)},
		{Name: "wrappedScalar", IsResolver: true, Out: t.marshalNWrappedScalar2otherpkgᚐScalar},
		{Name: "wrappedMap", IsResolver: true, Out: t.outMarshalNWrappedMap2followschemaᚐWrappedMap.Out},
		{Name: "wrappedSlice", IsResolver: true, Out: t.outMarshalNWrappedSlice2followschemaᚐWrappedSlice.Out},
		{Name: "__type", IsMethod: true, Args: []any{t.unmarshalNString2string.In}, Type: (**introspection.Type)(nil)},
		{Name: "__schema", IsMethod: true, Type: (**introspection.Schema)(nil)},
	})
}

func _Query_resolve(ctx context.Context, ec *executionContext, _ any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	switch fieldIndex {
	case 0:
		return ec.Resolvers.Query().InvalidIdentifier(ctx)
	case 1:
		return ec.Resolvers.Query().Collision(ctx)
	case 2:
		return ec.Resolvers.Query().MapInput(ctx, fieldArgs["input"].(map[string]any))
	case 3:
		return ec.Resolvers.Query().Recursive(ctx, fieldArgs["input"].(*RecursiveInputSlice))
	case 4:
		return ec.Resolvers.Query().NestedInputs(ctx, fieldArgs["input"].([][]*OuterInput))
	case 5:
		return ec.Resolvers.Query().NestedOutputs(ctx)
	case 6:
		return ec.Resolvers.Query().ModelMethods(ctx)
	case 7:
		return ec.Resolvers.Query().User(ctx, fieldArgs["id"].(int))
	case 8:
		return ec.Resolvers.Query().NullableArg(ctx, fieldArgs["arg"].(*int))
	case 9:
		return ec.Resolvers.Query().InputSlice(ctx, fieldArgs["arg"].([]string))
	case 10:
		return ec.Resolvers.Query().InputNullableSlice(ctx, fieldArgs["arg"].([]string))
	case 11:
		return ec.Resolvers.Query().InputOmittable(ctx, fieldArgs["arg"].(OmittableInput))
	case 12:
		return ec.Resolvers.Query().ShapeUnion(ctx)
	case 13:
		return ec.Resolvers.Query().Autobind(ctx)
	case 14:
		return ec.Resolvers.Query().DeprecatedField(ctx)
	case 15:
		return ec.Resolvers.Query().FieldWithDeprecatedArg(ctx, fieldArgs["oldArg"].(*int), fieldArgs["newArg"].(*int))
	case 16:
		return ec.Resolvers.Query().Overlapping(ctx)
	case 17:
		return ec.Resolvers.Query().DefaultParameters(ctx, fieldArgs["falsyBoolean"].(*bool), fieldArgs["truthyBoolean"].(*bool))
	case 18:
		return ec.Resolvers.Query().DeferSingle(ctx)
	case 19:
		return ec.Resolvers.Query().DeferMultiple(ctx)
	case 20:
		return ec.Resolvers.Query().DirectiveArg(ctx, fieldArgs["arg"].(string))
	case 21:
		return ec.Resolvers.Query().DirectiveNullableArg(ctx, fieldArgs["arg"].(*int), fieldArgs["arg2"].(*int), fieldArgs["arg3"].(*string))
	case 22:
		return ec.Resolvers.Query().DirectiveSingleNullableArg(ctx, fieldArgs["arg1"].(*string))
	case 23:
		return ec.Resolvers.Query().DirectiveInputNullable(ctx, fieldArgs["arg"].(*InputDirectives))
	case 24:
		return ec.Resolvers.Query().DirectiveInput(ctx, fieldArgs["arg"].(InputDirectives))
	case 25:
		return ec.Resolvers.Query().DirectiveInputType(ctx, fieldArgs["arg"].(InnerInput))
	case 26:
		return ec.Resolvers.Query().DirectiveInputOuter(ctx, fieldArgs["arg"].(OuterWrapperInput))
	case 27:
		return ec.Resolvers.Query().DirectiveInputWithArgs(ctx, fieldArgs["arg"].(InputDirectivesWithArgs))
	case 28:
		return ec.Resolvers.Query().DirectiveObject(ctx)
	case 29:
		return ec.Resolvers.Query().DirectiveObjectWithCustomGoModel(ctx)
	case 30:
		return ec.Resolvers.Query().DirectiveFieldDef(ctx, fieldArgs["ret"].(string))
	case 31:
		return ec.Resolvers.Query().DirectiveField(ctx)
	case 32:
		return ec.Resolvers.Query().DirectiveDouble(ctx)
	case 33:
		return ec.Resolvers.Query().DirectiveUnimplemented(ctx)
	case 34:
		return ec.Resolvers.Query().EmbeddedCase1(ctx)
	case 35:
		return ec.Resolvers.Query().EmbeddedCase2(ctx)
	case 36:
		return ec.Resolvers.Query().EmbeddedCase3(ctx)
	case 37:
		return ec.Resolvers.Query().EnumInInput(ctx, fieldArgs["input"].(*InputWithEnumValue))
	case 38:
		fc := graphql.GetFieldContext(ctx)
		return ec.Resolvers.Query().SearchProducts(ctx, map[string]interface{}{
			"query":    fc.Args["query"].(*string),
			"category": fc.Args["category"].(*string),
			"minPrice": fc.Args["minPrice"].(*int),
		})
	case 39:
		fc := graphql.GetFieldContext(ctx)
		return ec.Resolvers.Query().SearchRequired(ctx, map[string]interface{}{
			"name": fc.Args["name"].(string),
			"age":  fc.Args["age"].(int),
		})
	case 40:
		return ec.Resolvers.Query().SearchProductsNormal(ctx, fieldArgs["filters"].(map[string]any))
	case 41:
		fc := graphql.GetFieldContext(ctx)
		return ec.Resolvers.Query().SearchWithDefaults(ctx, map[string]interface{}{
			"query":           fc.Args["query"].(*string),
			"limit":           fc.Args["limit"].(*int),
			"includeArchived": fc.Args["includeArchived"].(*bool),
		})
	case 42:
		fc := graphql.GetFieldContext(ctx)
		return ec.Resolvers.Query().SearchMixed(ctx, map[string]interface{}{
			"query":    fc.Args["query"].(*string),
			"category": fc.Args["category"].(*string),
			"minPrice": fc.Args["minPrice"].(*int),
		}, fc.Args["limit"].(*int), fc.Args["offset"].(*int), fc.Args["sortBy"].(*string))
	case 43:
		fc := graphql.GetFieldContext(ctx)
		return ec.Resolvers.Query().FilterProducts(ctx, map[string]interface{}{
			"query":    fc.Args["query"].(*string),
			"category": fc.Args["category"].(*string),
			"minPrice": fc.Args["minPrice"].(*int),
		})
	case 44:
		fc := graphql.GetFieldContext(ctx)
		return ec.Resolvers.Query().FindProducts(ctx, map[string]interface{}{
			"query":    fc.Args["query"].(*string),
			"category": fc.Args["category"].(*string),
			"minPrice": fc.Args["minPrice"].(*int),
		})
	case 45:
		fc := graphql.GetFieldContext(ctx)
		return ec.Resolvers.Query().SearchWithDirectives(ctx, map[string]interface{}{
			"oldField": fc.Args["oldField"].(*string),
			"newField": fc.Args["newField"].(*string),
		})
	case 46:
		return ec.Resolvers.Query().Shapes(ctx)
	case 47:
		return ec.Resolvers.Query().NoShape(ctx)
	case 48:
		return ec.Resolvers.Query().Node(ctx)
	case 49:
		return ec.Resolvers.Query().NoShapeTypedNil(ctx)
	case 50:
		return ec.Resolvers.Query().Animal(ctx)
	case 51:
		return ec.Resolvers.Query().NotAnInterface(ctx)
	case 52:
		return ec.Resolvers.Query().Dog(ctx)
	case 53:
		return ec.Resolvers.Query().Issue896a(ctx)
	case 54:
		return ec.Resolvers.Query().MapStringInterface(ctx, fieldArgs["in"].(map[string]any))
	case 55:
		return ec.Resolvers.Query().MapNestedStringInterface(ctx, fieldArgs["in"].(*NestedMapInput))
	case 56:
		return ec.Resolvers.Query().MapNestedMapSlice(ctx, fieldArgs["input"].(map[string]any))
	case 57:
		return ec.Resolvers.Query().ErrorBubble(ctx)
	case 58:
		return ec.Resolvers.Query().ErrorBubbleList(ctx)
	case 59:
		return ec.Resolvers.Query().ErrorList(ctx)
	case 60:
		return ec.Resolvers.Query().Errors(ctx)
	case 61:
		return ec.Resolvers.Query().Valid(ctx)
	case 62:
		return ec.Resolvers.Query().Invalid(ctx)
	case 63:
		return ec.Resolvers.Query().Panics(ctx)
	case 64:
		return ec.Resolvers.Query().PrimitiveObject(ctx)
	case 65:
		return ec.Resolvers.Query().PrimitiveStringObject(ctx)
	case 66:
		return ec.Resolvers.Query().PtrToAnyContainer(ctx)
	case 67:
		return ec.Resolvers.Query().PtrToSliceContainer(ctx)
	case 68:
		return ec.Resolvers.Query().Infinity(ctx)
	case 69:
		return ec.Resolvers.Query().StringFromContextInterface(ctx)
	case 70:
		return ec.Resolvers.Query().StringFromContextFunction(ctx)
	case 71:
		return ec.Resolvers.Query().DefaultScalar(ctx, fieldArgs["arg"].(string))
	case 72:
		return ec.Resolvers.Query().SkipInclude(ctx)
	case 73:
		return ec.Resolvers.Query().Slices(ctx)
	case 74:
		return ec.Resolvers.Query().ScalarSlice(ctx)
	case 75:
		return ec.Resolvers.Query().Fallback(ctx, fieldArgs["arg"].(FallbackToStringEncoding))
	case 76:
		return ec.Resolvers.Query().OptionalUnion(ctx)
	case 77:
		return ec.Resolvers.Query().VOkCaseValue(ctx)
	case 78:
		return ec.Resolvers.Query().VOkCaseNil(ctx)
	case 79:
		return ec.Resolvers.Query().ValidType(ctx)
	case 80:
		return ec.Resolvers.Query().VariadicModel(ctx)
	case 81:
		return ec.Resolvers.Query().WrappedStruct(ctx)
	case 82:
		return ec.Resolvers.Query().WrappedScalar(ctx)
	case 83:
		return ec.Resolvers.Query().WrappedMap(ctx)
	case 84:
		return ec.Resolvers.Query().WrappedSlice(ctx)
	case 85:
		return ec.IntrospectType(fieldArgs["name"].(string))
	case 86:
		return ec.IntrospectSchema()
	}
	return nil, exec.NoField(fieldIndex)
}

func (t *tables) initObjectSubscription() {
	t.objectSubscription.Init(t.schema, "Subscription", _Subscription_resolve, []tableField{
		{Name: "updated", IsResolver: true, Out: t.marshalNString2string.Out, Stream: exec.StreamOf[string]()},
		{Name: "initPayload", IsResolver: true, Out: t.marshalNString2string.Out, Stream: exec.StreamOf[string]()},
		{Name: "directiveArg", IsResolver: true, Args: []any{t.unmarshalNString2string.In}, Out: t.marshalOString2ᚖstring.Out, Stream: exec.StreamOf[*string]()},
		{Name: "directiveNullableArg", IsResolver: true, Args: []any{t.unmarshalOInt2ᚖint.In, t.unmarshalOInt2ᚖint.In, t.unmarshalOString2ᚖstring.In}, Out: t.marshalOString2ᚖstring.Out, Stream: exec.StreamOf[*string]()},
		{Name: "directiveDouble", IsResolver: true, Out: t.marshalOString2ᚖstring.Out, Stream: exec.StreamOf[*string]()},
		{Name: "directiveUnimplemented", IsResolver: true, Out: t.marshalOString2ᚖstring.Out, Stream: exec.StreamOf[*string]()},
		{Name: "issue896b", IsResolver: true, Type: (*[]*CheckIssue896)(nil), Stream: exec.StreamOf[[]*CheckIssue896]()},
		{Name: "errorRequired", IsResolver: true, Type: (**Error)(nil), Stream: exec.StreamOf[*Error]()},
	})
	t.objectUser.Init(t.schema, "User", _User_resolve, []tableField{
		{Name: "id", Out: t.marshalNInt2int.Out},
		{Name: "friends", IsResolver: true, Type: (*[]*User)(nil)},
		{Name: "created", Out: t.marshalNTime2timeᚐTime.Out},
		{Name: "updated", Out: t.marshalOTime2ᚖtimeᚐTime.Out},
		{Name: "pets", IsResolver: true, Args: []any{t.unmarshalOInt2ᚖint.In}, Type: (*[]*Pet)(nil)},
	})
	t.inputChanges.Init(t.schema, exec.Input[*executionContext]{Name: "Changes", GoType: "map[string]any", Type: reflect.TypeOf((*map[string]any)(nil)).Elem(), IsMap: true, Set: _Changes_set}, []tableInputField{
		{Name: "a", In: t.unmarshalOInt2ᚖint.In},
		{Name: "b", In: t.unmarshalOInt2ᚖint.In},
	})
	t.inputInnerInput.Init(t.schema, exec.Input[*executionContext]{Name: "InnerInput", GoType: "InnerInput", Type: reflect.TypeOf((*InnerInput)(nil)).Elem(), Set: _InnerInput_set}, []tableInputField{
		{Name: "id", In: t.unmarshalNInt2int.In},
	})
}

func _Subscription_resolve(ctx context.Context, ec *executionContext, _ any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	switch fieldIndex {
	case 0:
		return ec.Resolvers.Subscription().Updated(ctx)
	case 1:
		return ec.Resolvers.Subscription().InitPayload(ctx)
	case 2:
		return ec.Resolvers.Subscription().DirectiveArg(ctx, fieldArgs["arg"].(string))
	case 3:
		return ec.Resolvers.Subscription().DirectiveNullableArg(ctx, fieldArgs["arg"].(*int), fieldArgs["arg2"].(*int), fieldArgs["arg3"].(*string))
	case 4:
		return ec.Resolvers.Subscription().DirectiveDouble(ctx)
	case 5:
		return ec.Resolvers.Subscription().DirectiveUnimplemented(ctx)
	case 6:
		return ec.Resolvers.Subscription().Issue896b(ctx)
	case 7:
		return ec.Resolvers.Subscription().ErrorRequired(ctx)
	}
	return nil, exec.NoField(fieldIndex)
}

func _User_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*User)
	switch fieldIndex {
	case 0:
		var v int = obj.ID
		return v, nil
	case 1:
		return ec.Resolvers.User().Friends(ctx, obj)
	case 2:
		var v time.Time = obj.Created
		return v, nil
	case 3:
		var v *time.Time = obj.Updated
		return v, nil
	case 4:
		return ec.Resolvers.User().Pets(ctx, obj, fieldArgs["limit"].(*int))
	}
	return nil, exec.NoField(fieldIndex)
}

func _Changes_set(inputValue any, fieldIndex int, v any) {
	m := *inputValue.(*map[string]any)
	switch fieldIndex {
	case 0:
		m["a"], _ = v.(*int)
	case 1:
		m["b"], _ = v.(*int)
	}
}

func _InnerInput_set(inputValue any, fieldIndex int, v any) {
	p := inputValue.(*InnerInput)
	switch fieldIndex {
	case 0:
		p.ID, _ = v.(int)
	}
}

func (t *tables) initInputOmittableInput() {
	t.inputOmittableInput.Init(t.schema, exec.Input[*executionContext]{Name: "OmittableInput", GoType: "OmittableInput", Type: reflect.TypeOf((*OmittableInput)(nil)).Elem(), Set: _OmittableInput_set}, []tableInputField{
		{Name: "id", In: t.unmarshalOID2ᚖstring.In},
		{Name: "bool", In: t.unmarshalOBoolean2ᚖbool.In},
		{Name: "str", In: t.unmarshalOString2ᚖstring.In},
		{Name: "int", In: t.unmarshalOInt2ᚖint.In},
		{Name: "time", In: t.unmarshalOTime2ᚖtimeᚐTime.In},
		{Name: "enum", Type: (**Status)(nil)},
		{Name: "scalar", In: t.unmarshalOThirdParty2ᚖfollowschemaᚐThirdParty.In},
		{Name: "object", In: t.unmarshalOOuterInput2ᚖfollowschemaᚐOuterInput},
	})
	t.inputOuterInput.Init(t.schema, exec.Input[*executionContext]{Name: "OuterInput", GoType: "OuterInput", Type: reflect.TypeOf((*OuterInput)(nil)).Elem(), Set: _OuterInput_set}, []tableInputField{
		{Name: "inner", Type: (**InnerInput)(nil)},
	})
	t.inputRecursiveInputSlice.Init(t.schema, exec.Input[*executionContext]{Name: "RecursiveInputSlice", GoType: "RecursiveInputSlice", Type: reflect.TypeOf((*RecursiveInputSlice)(nil)).Elem(), Set: _RecursiveInputSlice_set}, []tableInputField{
		{Name: "self", Type: (*[]RecursiveInputSlice)(nil)},
	})
}

func _OmittableInput_set(inputValue any, fieldIndex int, v any) {
	p := inputValue.(*OmittableInput)
	switch fieldIndex {
	case 0:
		x, _ := v.(*string)
		p.ID = graphql.OmittableOf(x)
	case 1:
		x, _ := v.(*bool)
		p.Bool = graphql.OmittableOf(x)
	case 2:
		x, _ := v.(*string)
		p.Str = graphql.OmittableOf(x)
	case 3:
		x, _ := v.(*int)
		p.Int = graphql.OmittableOf(x)
	case 4:
		x, _ := v.(*time.Time)
		p.Time = graphql.OmittableOf(x)
	case 5:
		x, _ := v.(*Status)
		p.Enum = graphql.OmittableOf(x)
	case 6:
		x, _ := v.(*ThirdParty)
		p.Scalar = graphql.OmittableOf(x)
	case 7:
		x, _ := v.(*OuterInput)
		p.Object = graphql.OmittableOf(x)
	}
}

func _OuterInput_set(inputValue any, fieldIndex int, v any) {
	p := inputValue.(*OuterInput)
	switch fieldIndex {
	case 0:
		p.Inner, _ = v.(*InnerInput)
	}
}

func _RecursiveInputSlice_set(inputValue any, fieldIndex int, v any) {
	p := inputValue.(*RecursiveInputSlice)
	switch fieldIndex {
	case 0:
		p.Self, _ = v.([]RecursiveInputSlice)
	}
}

func _Subscription(ctx context.Context, ec *executionContext, sel ast.SelectionSet) func(ctx context.Context) graphql.Marshaler {
	return ec.tables.objectSubscription.Subscribe(ctx, ec, sel)
}

func unmarshalOChanges2map(ctx context.Context, ec *executionContext, v any) (map[string]any, error) {
	if v == nil {
		return nil, nil
	}
	res, err := exec.InputValue[*executionContext, map[string]any](ctx, ec, &ec.tables.inputChanges, v)
	return res, graphql.ErrorOnPath(ctx, err)
}
