//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
)

func (t *tables) initObjectSkipIncludeTestType() {
	t.objectSkipIncludeTestType.Init(t.schema, "SkipIncludeTestType", _SkipIncludeTestType_resolve, []tableField{
		{Name: "a", Out: t.marshalOString2ᚖstring.Out},
		{Name: "b", Out: t.marshalOString2ᚖstring.Out},
	})
}

func _SkipIncludeTestType_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*SkipIncludeTestType)
	switch fieldIndex {
	case 0:
		var v *string = obj.A
		return v, nil
	case 1:
		var v *string = obj.B
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}
