//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/vektah/gqlparser/v2/ast"
)

func (t *tables) initObjectSlices() {
	t.objectSlices.Init(t.schema, "Slices", _Slices_resolve, []tableField{
		{Name: "test1", Out: t.marshalOString2ᚕᚖstring},
		{Name: "test2", Out: t.marshalOString2ᚕstringᚄ.Out},
		{Name: "test3", Out: t.marshalNString2ᚕᚖstring},
		{Name: "test4", Out: t.marshalNString2ᚕstringᚄ},
	})
}

func _Slices_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*Slices)
	switch fieldIndex {
	case 0:
		var v []*string = obj.Test1
		return v, nil
	case 1:
		var v []string = obj.Test2
		return v, nil
	case 2:
		var v []*string = obj.Test3
		return v, nil
	case 3:
		var v []string = obj.Test4
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func unmarshalNBytes2ᚕbyte(ctx context.Context, ec *executionContext, v any) ([]byte, error) {
	res, err := UnmarshalBytes(v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func marshalNBytes2ᚕbyte(ctx context.Context, ec *executionContext, sel ast.SelectionSet, v []byte) graphql.Marshaler {
	if v == nil {
		graphql.AddInvalidNullError(ctx, "Bytes!")
		return graphql.Null
	}
	_ = sel
	res := MarshalBytes(v)
	if res == graphql.Null {
		graphql.AddInvalidNullFromMarshaler(ctx, "Bytes!")
	}
	return res
}
