//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

func _TestUnion(ctx context.Context, ec *executionContext, sel ast.SelectionSet, obj TestUnion) graphql.Marshaler {
	switch obj := (obj).(type) {
	case nil:
		return graphql.Null
	case B:
		return objectB.Marshal(ctx, ec, sel, &obj)
	case *B:
		if obj == nil {
			return graphql.Null
		}
		return objectB.Marshal(ctx, ec, sel, obj)
	case A:
		return objectA.Marshal(ctx, ec, sel, &obj)
	case *A:
		if obj == nil {
			return graphql.Null
		}
		return objectA.Marshal(ctx, ec, sel, obj)
	default:
		if typedObj, ok := obj.(graphql.Marshaler); ok {
			return typedObj
		} else {
			panic(fmt.Errorf("unexpected type %T; non-generated variants of TestUnion must implement graphql.Marshaler", obj))
		}
	}
}

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectA = exec.Object[*executionContext]{Name: "A", Implementors: []string{"A", "TestUnion"}}

func init() {
	objectA.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *A) string { return obj.ID }),
	})
}

var objectB = exec.Object[*executionContext]{Name: "B", Implementors: []string{"B", "TestUnion"}}

func init() {
	objectB.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *B) string { return obj.ID }),
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var marshalOTestUnion2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐTestUnion = exec.MarshalInterface(false, _TestUnion)

// endregion ***************************** type.gotpl *****************************
