//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectVOkCaseNil = exec.Object[*executionContext]{Name: "VOkCaseNil", Implementors: []string{"VOkCaseNil"}}

func init() {
	objectVOkCaseNil.Init([]exec.Field[*executionContext]{
		{Name: "value", IsMethod: true, Leaf: "String", Out: outMarshalOString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, o any, args map[string]any) (any, error) {
			obj := o.(*VOkCaseNil)
			v, ok := obj.Value()
			if !ok {
				return nil, nil
			}
			return v, nil
		}},
	})
}

var objectVOkCaseValue = exec.Object[*executionContext]{Name: "VOkCaseValue", Implementors: []string{"VOkCaseValue"}}

func init() {
	objectVOkCaseValue.Init([]exec.Field[*executionContext]{
		{Name: "value", IsMethod: true, Leaf: "String", Out: outMarshalOString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, o any, args map[string]any) (any, error) {
			obj := o.(*VOkCaseValue)
			v, ok := obj.Value()
			if !ok {
				return nil, nil
			}
			return v, nil
		}},
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var marshalOVOkCaseNil2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐVOkCaseNil = exec.MarshalObjectPtr[*executionContext, VOkCaseNil](false, &objectVOkCaseNil)

var marshalOVOkCaseValue2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐVOkCaseValue = exec.MarshalObjectPtr[*executionContext, VOkCaseValue](false, &objectVOkCaseValue)

// endregion ***************************** type.gotpl *****************************
