//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectVariadicModel = exec.Object[*executionContext]{Name: "VariadicModel", Implementors: []string{"VariadicModel"}}

func init() {
	objectVariadicModel.Init([]exec.Field[*executionContext]{
		{Name: "value", Concurrent: true, IsMethod: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "rank", Type: inUnmarshalNInt2int.In},
		}, Out: outMarshalOString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return obj.(*VariadicModel).Value(ctx, args["rank"].(int))
		}},
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var marshalOVariadicModel2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐVariadicModel = exec.MarshalObjectPtr[*executionContext, VariadicModel](false, &objectVariadicModel)

// endregion ***************************** type.gotpl *****************************
