//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"github.com/99designs/gqlgen/graphql/exec"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectAIt = exec.Object[*executionContext]{Name: "AIt", Implementors: []string{"AIt"}}

func init() {
	objectAIt.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *AIt) string { return obj.ID }),
	})
}

var objectAbIt = exec.Object[*executionContext]{Name: "AbIt", Implementors: []string{"AbIt"}}

func init() {
	objectAbIt.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *AbIt) string { return obj.ID }),
	})
}

var objectXXIt = exec.Object[*executionContext]{Name: "XXIt", Implementors: []string{"XXIt"}}

func init() {
	objectXXIt.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *XXIt) string { return obj.ID }),
	})
}

var objectXxIt = exec.Object[*executionContext]{Name: "XxIt", Implementors: []string{"XxIt"}}

func init() {
	objectXxIt.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *XxIt) string { return obj.ID }),
	})
}

var objectasdfIt = exec.Object[*executionContext]{Name: "asdfIt", Implementors: []string{"asdfIt"}}

func init() {
	objectasdfIt.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *AsdfIt) string { return obj.ID }),
	})
}

var objectiIt = exec.Object[*executionContext]{Name: "iIt", Implementors: []string{"iIt"}}

func init() {
	objectiIt.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *IIt) string { return obj.ID }),
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

// endregion ***************************** type.gotpl *****************************
