//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package followschema

import (
	"context"

	"github.com/99designs/gqlgen/codegen/testserver/followschema/otherpkg"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

type WrappedMapResolver interface {
	Get(ctx context.Context, obj WrappedMap, key string) (string, error)
}
type WrappedSliceResolver interface {
	Get(ctx context.Context, obj WrappedSlice, idx int) (string, error)
}

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectWrappedMap = exec.Object[*executionContext]{Name: "WrappedMap", Implementors: []string{"WrappedMap"}}

func init() {
	objectWrappedMap.Init([]exec.Field[*executionContext]{
		{Name: "get", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "key", Type: inUnmarshalNString2string.In},
		}, Out: outMarshalNString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.WrappedMap().Get(ctx, obj.(WrappedMap), args["key"].(string))
		}},
	})
}

var objectWrappedSlice = exec.Object[*executionContext]{Name: "WrappedSlice", Implementors: []string{"WrappedSlice"}}

func init() {
	objectWrappedSlice.Init([]exec.Field[*executionContext]{
		{Name: "get", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "String", Args: []exec.Arg[*executionContext]{
			{Name: "idx", Type: inUnmarshalNInt2int.In},
		}, Out: outMarshalNString2string.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.WrappedSlice().Get(ctx, obj.(WrappedSlice), args["idx"].(int))
		}},
	})
}

var objectWrappedStruct = exec.Object[*executionContext]{Name: "WrappedStruct", Implementors: []string{"WrappedStruct"}}

func init() {
	objectWrappedStruct.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "WrappedScalar"}, outMarshalNWrappedScalar2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚋotherpkgᚐScalar, func(obj *WrappedStruct) otherpkg.Scalar { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "desc", Leaf: "WrappedScalar"}, outMarshalOWrappedScalar2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚋotherpkgᚐScalar, func(obj *WrappedStruct) *otherpkg.Scalar { return obj.Desc }),
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

func marshalNWrappedMap2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐWrappedMap(ctx context.Context, ec *executionContext, sel ast.SelectionSet, v WrappedMap) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return objectWrappedMap.Marshal(ctx, ec, sel, v)
}

func unmarshalNWrappedScalar2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚋotherpkgᚐScalar(ctx context.Context, ec *executionContext, v any) (otherpkg.Scalar, error) {
	tmp, err := graphql.UnmarshalString(v)
	res := otherpkg.Scalar(tmp)
	return res, graphql.ErrorOnPath(ctx, err)
}

func marshalNWrappedScalar2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚋotherpkgᚐScalar(ctx context.Context, ec *executionContext, sel ast.SelectionSet, v otherpkg.Scalar) graphql.Marshaler {
	_ = sel
	res := graphql.MarshalString(string(v))
	if res == graphql.Null {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
	}
	return res
}

func marshalNWrappedSlice2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐWrappedSlice(ctx context.Context, ec *executionContext, sel ast.SelectionSet, v WrappedSlice) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return objectWrappedSlice.Marshal(ctx, ec, sel, v)
}

var marshalNWrappedStruct2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚐWrappedStruct = exec.MarshalObjectPtr[*executionContext, WrappedStruct](true, &objectWrappedStruct)

func unmarshalOWrappedScalar2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚋotherpkgᚐScalar(ctx context.Context, ec *executionContext, v any) (*otherpkg.Scalar, error) {
	if v == nil {
		return nil, nil
	}
	tmp, err := graphql.UnmarshalString(v)
	res := otherpkg.Scalar(tmp)
	return &res, graphql.ErrorOnPath(ctx, err)
}

func marshalOWrappedScalar2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋfollowschemaᚋotherpkgᚐScalar(ctx context.Context, ec *executionContext, sel ast.SelectionSet, v *otherpkg.Scalar) graphql.Marshaler {
	if v == nil {
		return graphql.Null
	}
	_ = sel
	_ = ctx
	res := graphql.MarshalString(string(*v))
	return res
}

// endregion ***************************** type.gotpl *****************************
