package codegen

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"strings"
)

// The schema files outside the directory of the generated code cannot be embedded from
// there with go:embed, which does not follow .. or symbolic links. With
// exec.embed_schema_dir, gqlgen writes a copy of each of them into that directory and the
// generated code embeds the copies, instead of including the text of the files.

// schemaCopyPath returns where the copy of a schema file outside the directory of the
// generated code is written, relative to that directory: the path of the file relative to
// that directory without its leading parent directories, inside embedDir. ../a.graphql is
// copied to embedDir/a.graphql, and ../../shared/b.graphql to embedDir/shared/b.graphql.
func schemaCopyPath(embedDir, relative string) string {
	for strings.HasPrefix(relative, "../") {
		relative = strings.TrimPrefix(relative, "../")
	}
	return path.Join(embedDir, relative)
}

// checkSchemaCopies returns an error when two embedded files would have the same path,
// which happens for copies of files of the same name at different depths above the
// directory of the generated code.
func checkSchemaCopies(sources []AugmentedSource) error {
	names := map[string]string{}
	for _, s := range sources {
		if !s.Embeddable {
			continue
		}
		if other, ok := names[s.RelativePath]; ok {
			return fmt.Errorf(
				"embed_schema_dir: %s and %s would both be embedded as %s; rename one of them",
				other,
				s.Name,
				s.RelativePath,
			)
		}
		names[s.RelativePath] = s.Name
	}
	return nil
}

// schemaCopyNotice heads the copies, as the notice of the generated Go files heads them.
const schemaCopyNotice = "# Code generated by github.com/99designs/gqlgen, DO NOT EDIT.\n\n"

// writeSchemaCopies writes the copies of the schema files among sources into embedDir
// under dir, the directory of the generated code, and deletes the other files in embedDir,
// so that it holds only what the generated code embeds. A copy whose content has not
// changed is left as it is, which keeps its modification time for the build cache. With
// notice, the copies are headed by schemaCopyNotice.
func writeSchemaCopies(dir, embedDir string, sources []AugmentedSource, notice bool) error {
	if embedDir == "" {
		return nil
	}
	root := filepath.Join(dir, filepath.FromSlash(embedDir))
	written := map[string]bool{}
	for _, s := range sources {
		if !s.Copy {
			continue
		}
		name := filepath.Join(dir, filepath.FromSlash(s.RelativePath))
		content := s.Source
		if notice {
			content = schemaCopyNotice + content
		}
		if err := writeIfChanged(name, []byte(content)); err != nil {
			return fmt.Errorf("failed to write the copy of %s: %w", s.Name, err)
		}
		written[name] = true
	}
	if _, err := os.Stat(root); err != nil {
		return nil
	}
	return filepath.WalkDir(root, func(name string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || written[name] {
			return err
		}
		return os.Remove(name)
	})
}

// writeIfChanged writes content to name unless the file already holds it.
func writeIfChanged(name string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(name), 0o755); err != nil {
		return err
	}
	if existing, err := os.ReadFile(name); err == nil && bytes.Equal(existing, content) {
		return nil
	}
	return os.WriteFile(name, content, 0o644)
}
