//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

import (
	"bytes"
	"context"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/99designs/gqlgen/graphql/introspection"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ***************************** api!.gotpl *****************************

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{SchemaData: cfg.Schema, Resolvers: cfg.Resolvers, Directives: cfg.Directives, ComplexityRoot: cfg.Complexity}
}

type Config = graphql.Config[ResolverRoot, DirectiveRoot, ComplexityRoot]

type ResolverRoot interface {
	Query() QueryResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	Query struct {
		EchoInt64InputToInt64Object func(childComplexity int, input Input64) int
		EchoInt64ToInt64            func(childComplexity int, n *int) int
		EchoIntInputToIntObject     func(childComplexity int, input Input) int
		EchoIntToInt                func(childComplexity int, n *int32) int
	}

	Result struct {
		N func(childComplexity int) int
	}

	Result64 struct {
		N func(childComplexity int) int
	}
}

// endregion ***************************** api!.gotpl *****************************

// region    ************************** generated!.gotpl **************************

type QueryResolver interface {
	EchoIntToInt(ctx context.Context, n *int32) (int32, error)
	EchoInt64ToInt64(ctx context.Context, n *int) (int, error)
	EchoIntInputToIntObject(ctx context.Context, input Input) (*Result, error)
	EchoInt64InputToInt64Object(ctx context.Context, input Input64) (*Result64, error)
}

// endregion ************************** generated!.gotpl **************************

// region    ************************** internal!.gotpl ***************************

type executableSchema graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot]

func (e *executableSchema) Schema() *ast.Schema {
	if e.SchemaData != nil {
		return e.SchemaData
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := newExecutionContext(nil, e, nil)
	_ = ec
	switch typeName + "." + field {

	case "Query.echoInt64InputToInt64Object":
		if e.ComplexityRoot.Query.EchoInt64InputToInt64Object == nil {
			break
		}

		args, err := objectQuery.ParseArgs(ctx, ec, "echoInt64InputToInt64Object", rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.EchoInt64InputToInt64Object(childComplexity, args["input"].(Input64)), true
	case "Query.echoInt64ToInt64":
		if e.ComplexityRoot.Query.EchoInt64ToInt64 == nil {
			break
		}

		args, err := objectQuery.ParseArgs(ctx, ec, "echoInt64ToInt64", rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.EchoInt64ToInt64(childComplexity, args["n"].(*int)), true
	case "Query.echoIntInputToIntObject":
		if e.ComplexityRoot.Query.EchoIntInputToIntObject == nil {
			break
		}

		args, err := objectQuery.ParseArgs(ctx, ec, "echoIntInputToIntObject", rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.EchoIntInputToIntObject(childComplexity, args["input"].(Input)), true
	case "Query.echoIntToInt":
		if e.ComplexityRoot.Query.EchoIntToInt == nil {
			break
		}

		args, err := objectQuery.ParseArgs(ctx, ec, "echoIntToInt", rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.EchoIntToInt(childComplexity, args["n"].(*int32)), true

	case "Result.n":
		if e.ComplexityRoot.Result.N == nil {
			break
		}

		return e.ComplexityRoot.Result.N(childComplexity), true

	case "Result64.n":
		if e.ComplexityRoot.Result64.N == nil {
			break
		}

		return e.ComplexityRoot.Result64.N(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := newExecutionContext(opCtx, e, make(chan graphql.DeferredResult))
	inputUnmarshalers := func() *graphql.InputUnmarshalerIndex {
		return graphql.NewInputUnmarshalerIndex(
			graphql.NewInputUnmarshaler("Input", graphql.BindUnmarshaler(ec, exec.InputFunc[*executionContext, Input](&inputInput))),
			graphql.NewInputUnmarshaler("Input64", graphql.BindUnmarshaler(ec, exec.InputFunc[*executionContext, Input64](&inputInput64))),
		)
	}
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithLazyInputUnmarshalerIndex(ctx, inputUnmarshalers)
				data = objectQuery.Marshal(ctx, ec, opCtx.Operation.SelectionSet, nil)
			} else {
				if atomic.LoadInt32(&ec.PendingDeferred) > 0 {
					result := <-ec.DeferredResults
					atomic.AddInt32(&ec.PendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.Deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.PendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.ExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot]
}

func newExecutionContext(
	opCtx *graphql.OperationContext,
	execSchema *executableSchema,
	deferredResults chan graphql.DeferredResult,
) *executionContext {
	return &executionContext{
		ExecutionContextState: graphql.NewExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot](
			opCtx,
			(*graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot])(execSchema),
			parsedSchema,
			deferredResults,
		),
	}
}

var sources = []*ast.Source{
	{Name: "../schema.graphql", Input: `scalar Int64

input Input {
    n: Int
}

input Input64 {
    n: Int64
}

type Result {
    n: Int!
}

type Result64 {
    n: Int64!
}

type Query {
  echoIntToInt(n: Int): Int!
  echoInt64ToInt64(n: Int64): Int64!
  echoIntInputToIntObject(input: Input!): Result
  echoInt64InputToInt64Object(input: Input64!): Result64
}
`, BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)

// childFields_* functions provide shared child field context lookups.
// Each function is generated once per unique object type, deduplicating the
// switch statements that were previously inlined in every fieldContext_* function.
var outMarshalNBoolean2bool = exec.OutOf(marshalNBoolean2bool)
var outMarshalNInt2int32 = exec.OutOf(marshalNInt2int32)
var outMarshalNInt642int = exec.OutOf(marshalNInt642int)
var outMarshalNString2string = exec.OutOf(marshalNString2string)
var outMarshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ = exec.OutOf(marshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ)
var outMarshalN__DirectiveLocation2ᚕstringᚄ = exec.OutOf(marshalN__DirectiveLocation2ᚕstringᚄ)
var outMarshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.OutOf(marshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ)
var outMarshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.OutOf(marshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ)
var outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.OutOf(marshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType)
var outMarshalN__TypeKind2string = exec.OutOf(marshalN__TypeKind2string)
var outMarshalOBoolean2bool = exec.OutOf(marshalOBoolean2bool)
var outMarshalOResult2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐResult = exec.OutOf(marshalOResult2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐResult)
var outMarshalOResult642ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐResult64 = exec.OutOf(marshalOResult642ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐResult64)
var outMarshalOString2ᚖstring = exec.OutOf(marshalOString2ᚖstring)
var outMarshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ = exec.OutOf(marshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ)
var outMarshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ = exec.OutOf(marshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ)
var outMarshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.OutOf(marshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ)
var outMarshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema = exec.OutOf(marshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema)
var outMarshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.OutOf(marshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ)
var outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.OutOf(marshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType)
var inUnmarshalNInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐInput = exec.InOf(unmarshalNInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐInput)
var inUnmarshalNInput642githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐInput64 = exec.InOf(unmarshalNInput642githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐInput64)
var inUnmarshalNString2string = exec.InOf(unmarshalNString2string)
var inUnmarshalOBoolean2bool = exec.InOf(unmarshalOBoolean2bool)
var inUnmarshalOBoolean2ᚖbool = exec.InOf(unmarshalOBoolean2ᚖbool)
var inUnmarshalOInt2ᚖint32 = exec.InOf(unmarshalOInt2ᚖint32)
var inUnmarshalOInt642ᚖint = exec.InOf(unmarshalOInt642ᚖint)

// endregion ************************** internal!.gotpl ***************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

var inputInput = exec.Input[*executionContext]{Name: "Input", GoType: "Input"}

func init() {
	inputInput.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "n"}, inUnmarshalOInt2ᚖint32, func(it *Input, v *int32) { it.N = v }),
	}
}

// UnmarshalInput unmarshals raw into the Input input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalInput(ctx context.Context, raw any) (Input, error) {
	var out Input
	err := graphql.UnmarshalNamedInputFromContext(ctx, "Input", raw, &out)
	return out, err
}

var inputInput64 = exec.Input[*executionContext]{Name: "Input64", GoType: "Input64"}

func init() {
	inputInput64.Fields = []exec.InputField[*executionContext]{
		exec.InputSet(exec.InputField[*executionContext]{Name: "n"}, inUnmarshalOInt642ᚖint, func(it *Input64, v *int) { it.N = v }),
	}
}

// UnmarshalInput64 unmarshals raw into the Input64 input type, using the
// unmarshaler bound to ctx's request. Call it from a resolver to decode an input
// object that was not passed as a field argument.
//
// ctx must come from a gqlgen request; outside one there is no unmarshaler to use
// and the returned error says so.
func UnmarshalInput64(ctx context.Context, raw any) (Input64, error) {
	var out Input64
	err := graphql.UnmarshalNamedInputFromContext(ctx, "Input64", raw, &out)
	return out, err
}

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectQuery = exec.Object[*executionContext]{Name: "Query", Implementors: []string{"Query"}, Root: true}

func init() {
	objectQuery.Init([]exec.Field[*executionContext]{
		{Name: "echoIntToInt", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Int", Args: []exec.Arg[*executionContext]{
			{Name: "n", Type: inUnmarshalOInt2ᚖint32.In},
		}, Out: outMarshalNInt2int32.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().EchoIntToInt(ctx, args["n"].(*int32))
		}},
		{Name: "echoInt64ToInt64", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Leaf: "Int64", Args: []exec.Arg[*executionContext]{
			{Name: "n", Type: inUnmarshalOInt642ᚖint.In},
		}, Out: outMarshalNInt642int.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().EchoInt64ToInt64(ctx, args["n"].(*int))
		}},
		{Name: "echoIntInputToIntObject", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectResult, Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalNInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐInput.In},
		}, Out: outMarshalOResult2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐResult.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().EchoIntInputToIntObject(ctx, args["input"].(Input))
		}},
		{Name: "echoInt64InputToInt64Object", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectResult64, Args: []exec.Arg[*executionContext]{
			{Name: "input", Type: inUnmarshalNInput642githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐInput64.In},
		}, Out: outMarshalOResult642ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐResult64.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().EchoInt64InputToInt64Object(ctx, args["input"].(Input64))
		}},
		{Name: "__type", IsMethod: true, Children: &object__Type, Args: []exec.Arg[*executionContext]{
			{Name: "name", Type: inUnmarshalNString2string.In},
		}, Out: outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.IntrospectType(args["name"].(string))
		}},
		{Name: "__schema", IsMethod: true, Children: &object__Schema, Out: outMarshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.IntrospectSchema()
		}},
	})
}

var objectResult = exec.Object[*executionContext]{Name: "Result", Implementors: []string{"Result"}}

func init() {
	objectResult.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "n", NonNull: true, Leaf: "Int"}, outMarshalNInt2int32, func(obj *Result) int32 { return obj.N }),
	})
}

var objectResult64 = exec.Object[*executionContext]{Name: "Result64", Implementors: []string{"Result64"}}

func init() {
	objectResult64.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "n", NonNull: true, Leaf: "Int64"}, outMarshalNInt642int, func(obj *Result64) int { return obj.N }),
	})
}

var object__Directive = exec.Object[*executionContext]{Name: "__Directive", Implementors: []string{"__Directive"}}

func init() {
	object__Directive.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.Directive) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Directive) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isRepeatable", NonNull: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.Directive) bool { return obj.IsRepeatable }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "locations", NonNull: true, Leaf: "__DirectiveLocation"}, outMarshalN__DirectiveLocation2ᚕstringᚄ, func(obj *introspection.Directive) []string { return obj.Locations }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "args", NonNull: true, Children: &object__InputValue, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2ᚖbool.In},
		}}, outMarshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ, func(obj *introspection.Directive) []introspection.InputValue { return obj.Args }),
	})
}

var object__EnumValue = exec.Object[*executionContext]{Name: "__EnumValue", Implementors: []string{"__EnumValue"}}

func init() {
	object__EnumValue.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.EnumValue) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.EnumValue) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isDeprecated", NonNull: true, IsMethod: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.EnumValue) bool { return obj.IsDeprecated() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "deprecationReason", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.EnumValue) *string { return obj.DeprecationReason() }),
	})
}

var object__Field = exec.Object[*executionContext]{Name: "__Field", Implementors: []string{"__Field"}}

func init() {
	object__Field.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.Field) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Field) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "args", NonNull: true, Children: &object__InputValue, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2ᚖbool.In},
		}}, outMarshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ, func(obj *introspection.Field) []introspection.InputValue { return obj.Args }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "type", NonNull: true, Children: &object__Type}, outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Field) *introspection.Type { return obj.Type }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isDeprecated", NonNull: true, IsMethod: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.Field) bool { return obj.IsDeprecated() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "deprecationReason", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Field) *string { return obj.DeprecationReason() }),
	})
}

var object__InputValue = exec.Object[*executionContext]{Name: "__InputValue", Implementors: []string{"__InputValue"}}

func init() {
	object__InputValue.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *introspection.InputValue) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.InputValue) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "type", NonNull: true, Children: &object__Type}, outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.InputValue) *introspection.Type { return obj.Type }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "defaultValue", Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.InputValue) *string { return obj.DefaultValue }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isDeprecated", NonNull: true, IsMethod: true, Leaf: "Boolean"}, outMarshalNBoolean2bool, func(obj *introspection.InputValue) bool { return obj.IsDeprecated() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "deprecationReason", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.InputValue) *string { return obj.DeprecationReason() }),
	})
}

var object__Schema = exec.Object[*executionContext]{Name: "__Schema", Implementors: []string{"__Schema"}}

func init() {
	object__Schema.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Schema) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "types", NonNull: true, IsMethod: true, Children: &object__Type}, outMarshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ, func(obj *introspection.Schema) []introspection.Type { return obj.Types() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "queryType", NonNull: true, IsMethod: true, Children: &object__Type}, outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Schema) *introspection.Type { return obj.QueryType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "mutationType", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Schema) *introspection.Type { return obj.MutationType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "subscriptionType", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Schema) *introspection.Type { return obj.SubscriptionType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "directives", NonNull: true, IsMethod: true, Children: &object__Directive}, outMarshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ, func(obj *introspection.Schema) []introspection.Directive { return obj.Directives() }),
	})
}

var object__Type = exec.Object[*executionContext]{Name: "__Type", Implementors: []string{"__Type"}}

func init() {
	object__Type.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "kind", NonNull: true, IsMethod: true, Leaf: "__TypeKind"}, outMarshalN__TypeKind2string, func(obj *introspection.Type) string { return obj.Kind() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Type) *string { return obj.Name() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "description", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Type) *string { return obj.Description() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "specifiedByURL", IsMethod: true, Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *introspection.Type) *string { return obj.SpecifiedByURL() }),
		{Name: "fields", IsMethod: true, Children: &object__Field, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2bool.In},
		}, Out: outMarshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return obj.(*introspection.Type).Fields(args["includeDeprecated"].(bool)), nil
		}},
		exec.FieldGet(exec.Field[*executionContext]{Name: "interfaces", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ, func(obj *introspection.Type) []introspection.Type { return obj.Interfaces() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "possibleTypes", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ, func(obj *introspection.Type) []introspection.Type { return obj.PossibleTypes() }),
		{Name: "enumValues", IsMethod: true, Children: &object__EnumValue, Args: []exec.Arg[*executionContext]{
			{Name: "includeDeprecated", Type: inUnmarshalOBoolean2bool.In},
		}, Out: outMarshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return obj.(*introspection.Type).EnumValues(args["includeDeprecated"].(bool)), nil
		}},
		exec.FieldGet(exec.Field[*executionContext]{Name: "inputFields", IsMethod: true, Children: &object__InputValue}, outMarshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ, func(obj *introspection.Type) []introspection.InputValue { return obj.InputFields() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "ofType", IsMethod: true, Children: &object__Type}, outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, func(obj *introspection.Type) *introspection.Type { return obj.OfType() }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "isOneOf", IsMethod: true, Leaf: "Boolean"}, outMarshalOBoolean2bool, func(obj *introspection.Type) bool { return obj.IsOneOf() }),
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var unmarshalNBoolean2bool = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalBoolean)

var marshalNBoolean2bool = exec.MarshalFunc[*executionContext](true, graphql.MarshalBoolean)

var unmarshalNInput2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐInput = exec.UnmarshalInput[*executionContext, Input](&inputInput)

var unmarshalNInput642githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐInput64 = exec.UnmarshalInput[*executionContext, Input64](&inputInput64)

var unmarshalNInt2int32 = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalInt32)

var marshalNInt2int32 = exec.MarshalFunc[*executionContext](true, graphql.MarshalInt32)

var unmarshalNInt642int = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalInt)

var marshalNInt642int = exec.MarshalFunc[*executionContext](true, graphql.MarshalInt)

var unmarshalNString2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalNString2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalString)

var marshalN__Directive2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirective = exec.MarshalObject[*executionContext, introspection.Directive](&object__Directive)

var marshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ = exec.MarshalList(marshalN__Directive2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirective, exec.ListOptions{ElemNonNull: true})

var unmarshalN__DirectiveLocation2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalN__DirectiveLocation2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalString)

var unmarshalN__DirectiveLocation2ᚕstringᚄ = exec.UnmarshalList(false, unmarshalN__DirectiveLocation2string)

var marshalN__DirectiveLocation2ᚕstringᚄ = exec.MarshalList(marshalN__DirectiveLocation2string, exec.ListOptions{ElemNonNull: true})

var marshalN__EnumValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValue = exec.MarshalObject[*executionContext, introspection.EnumValue](&object__EnumValue)

var marshalN__Field2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐField = exec.MarshalObject[*executionContext, introspection.Field](&object__Field)

var marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue = exec.MarshalObject[*executionContext, introspection.InputValue](&object__InputValue)

var marshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.MarshalList(marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue, exec.ListOptions{ElemNonNull: true})

var marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.MarshalObject[*executionContext, introspection.Type](&object__Type)

var marshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.MarshalList(marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, exec.ListOptions{ElemNonNull: true})

var marshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.MarshalObjectPtr[*executionContext, introspection.Type](true, &object__Type)

var unmarshalN__TypeKind2string = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalString)

var marshalN__TypeKind2string = exec.MarshalFunc[*executionContext](true, graphql.MarshalString)

var unmarshalOBoolean2bool = exec.UnmarshalFunc[*executionContext](graphql.UnmarshalBoolean)

var marshalOBoolean2bool = exec.MarshalFunc[*executionContext](false, graphql.MarshalBoolean)

var unmarshalOBoolean2ᚖbool = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalBoolean)

var marshalOBoolean2ᚖbool = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalBoolean)

var unmarshalOInt2ᚖint32 = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalInt32)

var marshalOInt2ᚖint32 = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalInt32)

var unmarshalOInt642ᚖint = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalInt)

var marshalOInt642ᚖint = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalInt)

var marshalOResult2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐResult = exec.MarshalObjectPtr[*executionContext, Result](false, &objectResult)

var marshalOResult642ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋcompliantᚑintᚋgeneratedᚑcompliantᚑstrictᚐResult64 = exec.MarshalObjectPtr[*executionContext, Result64](false, &objectResult64)

var unmarshalOString2ᚖstring = exec.UnmarshalFuncPtr[*executionContext](true, graphql.UnmarshalString)

var marshalOString2ᚖstring = exec.MarshalFuncPtr[*executionContext](false, graphql.MarshalString)

var marshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ = exec.MarshalList(marshalN__EnumValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValue, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ = exec.MarshalList(marshalN__Field2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐField, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.MarshalList(marshalN__InputValue2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValue, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema = exec.MarshalObjectPtr[*executionContext, introspection.Schema](false, &object__Schema)

var marshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.MarshalList(marshalN__Type2githubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType, exec.ListOptions{Nullable: true, ElemNonNull: true})

var marshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.MarshalObjectPtr[*executionContext, introspection.Type](false, &object__Type)

// endregion ***************************** type.gotpl *****************************
