//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package returnpointersinunmarshalinput

import (
	"context"
	"reflect"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
)

// UnmarshalCheckedInput unmarshals raw into the CheckedInput input type, as graphql.UnmarshalNamedInputFromContext does.
func UnmarshalCheckedInput(ctx context.Context, raw any) (out *CheckedInput, err error) {
	err = graphql.UnmarshalNamedInputFromContext(ctx, "CheckedInput", raw, &out)
	return out, err
}

func (t *tables) initInputCheckedInput() {
	t.inputCheckedInput.Init(t.schema, exec.Input[*executionContext]{Name: "CheckedInput", GoType: "CheckedInput", Type: reflect.TypeOf((*CheckedInput)(nil)).Elem(), Pointer: true, Set: _CheckedInput_set}, []tableInputField{
		{Name: "mode", In: t.unmarshalNString2string.In},
		{Name: "value", In: t.unmarshalNString2string.In},
	})
}

func _CheckedInput_set(inputValue any, fieldIndex int, v any) {
	p := inputValue.(*CheckedInput)
	switch fieldIndex {
	case 0:
		p.Mode, _ = v.(string)
	case 1:
		p.Value, _ = v.(string)
	}
}

func unmarshalOCheckedInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋreturnpointersinunmarshalinputᚐCheckedInput(ctx context.Context, ec *executionContext, v any) (*CheckedInput, error) {
	if v == nil {
		return nil, nil
	}
	res, err := exec.InputPointer[*executionContext, CheckedInput](ctx, ec, &ec.tables.inputCheckedInput, v)
	return res, graphql.ErrorOnPath(ctx, err)
}
