//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package returnpointersinunmarshalinput

import (
	"bytes"
	"context"
	"embed"
	"errors"
	"fmt"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{SchemaData: cfg.Schema, Resolvers: cfg.Resolvers, Directives: cfg.Directives, ComplexityRoot: cfg.Complexity}
}

type Config = graphql.Config[ResolverRoot, DirectiveRoot, ComplexityRoot]

type ResolverRoot interface {
	Query() QueryResolver
}

type DirectiveRoot struct {
	InputCheck func(ctx context.Context, obj any, next graphql.Resolver) (res any, err error)
}

type ComplexityRoot struct {
}

type executableSchema graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot]

func (e *executableSchema) Schema() *ast.Schema {
	if e.SchemaData != nil {
		return e.SchemaData
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := newExecutionContext(nil, e, nil)
	_ = ec
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := newExecutionContext(opCtx, e, make(chan graphql.DeferredResult))
	inputUnmarshalers := func() *graphql.InputUnmarshalerIndex {
		return graphql.NewInputUnmarshalerIndex(
			graphql.NewInputUnmarshaler("CheckedInput", graphql.BindUnmarshaler(ec, exec.InputPointerFunc[*executionContext, CheckedInput](&inputCheckedInput))),
			graphql.NewInputUnmarshaler("LegacyFilters", graphql.BindUnmarshaler(ec, exec.InputPointerFunc[*executionContext, LegacyFilters](&inputLegacyFilters))),
			graphql.NewInputUnmarshaler("SearchFilters", graphql.BindUnmarshaler(ec, exec.InputPointerFunc[*executionContext, SearchFilters](&inputSearchFilters))),
		)
	}
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithLazyInputUnmarshalerIndex(ctx, inputUnmarshalers)
				data = objectQuery.Marshal(ctx, ec, opCtx.Operation.SelectionSet, nil)
			} else {
				if atomic.LoadInt32(&ec.PendingDeferred) > 0 {
					result := <-ec.DeferredResults
					atomic.AddInt32(&ec.PendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.Deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.PendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.ExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot]
}

func newExecutionContext(
	opCtx *graphql.OperationContext,
	execSchema *executableSchema,
	deferredResults chan graphql.DeferredResult,
) *executionContext {
	return &executionContext{
		ExecutionContextState: graphql.NewExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot](
			opCtx,
			(*graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot])(execSchema),
			parsedSchema,
			deferredResults,
		),
	}
}

//go:embed "input_object_directive.graphql" "schema.graphql"
var sourcesFS embed.FS

func sourceData(filename string) string {
	data, err := sourcesFS.ReadFile(filename)
	if err != nil {
		panic(fmt.Sprintf("codegen problem: %s not available", filename))
	}
	return string(data)
}

var sources = []*ast.Source{
	{Name: "input_object_directive.graphql", Input: sourceData("input_object_directive.graphql"), BuiltIn: false},
	{Name: "schema.graphql", Input: sourceData("schema.graphql"), BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)

// childFields_* functions provide shared child field context lookups.
// Each function is generated once per unique object type, deduplicating the
// switch statements that were previously inlined in every fieldContext_* function.
var outMarshalNBoolean2bool = exec.OutOf(marshalNBoolean2bool)
var outMarshalNString2string = exec.OutOf(marshalNString2string)
var outMarshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ = exec.OutOf(marshalN__Directive2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐDirectiveᚄ)
var outMarshalN__DirectiveLocation2ᚕstringᚄ = exec.OutOf(marshalN__DirectiveLocation2ᚕstringᚄ)
var outMarshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.OutOf(marshalN__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ)
var outMarshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.OutOf(marshalN__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ)
var outMarshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.OutOf(marshalN__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType)
var outMarshalN__TypeKind2string = exec.OutOf(marshalN__TypeKind2string)
var outMarshalOBoolean2bool = exec.OutOf(marshalOBoolean2bool)
var outMarshalOString2ᚖstring = exec.OutOf(marshalOString2ᚖstring)
var outMarshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ = exec.OutOf(marshalO__EnumValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐEnumValueᚄ)
var outMarshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ = exec.OutOf(marshalO__Field2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐFieldᚄ)
var outMarshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ = exec.OutOf(marshalO__InputValue2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐInputValueᚄ)
var outMarshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema = exec.OutOf(marshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema)
var outMarshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ = exec.OutOf(marshalO__Type2ᚕgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐTypeᚄ)
var outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType = exec.OutOf(marshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType)
var inUnmarshalNLegacyFilters2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋreturnpointersinunmarshalinputᚐLegacyFilters = exec.InOf(unmarshalNLegacyFilters2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋreturnpointersinunmarshalinputᚐLegacyFilters)
var inUnmarshalNSearchFilters2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋreturnpointersinunmarshalinputᚐSearchFilters = exec.InOf(unmarshalNSearchFilters2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋreturnpointersinunmarshalinputᚐSearchFilters)
var inUnmarshalNString2string = exec.InOf(unmarshalNString2string)
var inUnmarshalOBoolean2bool = exec.InOf(unmarshalOBoolean2bool)
var inUnmarshalOBoolean2ᚖbool = exec.InOf(unmarshalOBoolean2ᚖbool)
var inUnmarshalOCheckedInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋreturnpointersinunmarshalinputᚐCheckedInput = exec.InOf(unmarshalOCheckedInput2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋreturnpointersinunmarshalinputᚐCheckedInput)
var inUnmarshalOInt2ᚖint = exec.InOf(unmarshalOInt2ᚖint)
var inUnmarshalOString2ᚖstring = exec.InOf(unmarshalOString2ᚖstring)

var directiveInputCheck = exec.DirectiveDef[*executionContext]{Name: "inputCheck",
	Call: func(ctx context.Context, ec *executionContext, obj any, n graphql.Resolver, args map[string]any) (any, error) {
		if ec.Directives.InputCheck == nil {
			return nil, errors.New("directive inputCheck is not implemented")
		}
		return ec.Directives.InputCheck(ctx, obj, n)
	},
}
