//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package returnpointersinunmarshalinput

import (
	"context"
	"reflect"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/99designs/gqlgen/graphql/introspection"
)

type QueryResolver interface {
	Search(ctx context.Context, filters SearchFilters) (string, error)
	Legacy(ctx context.Context, filters LegacyFilters) (string, error)
	CheckedInput(ctx context.Context, input *CheckedInput) (string, error)
}

// UnmarshalLegacyFilters unmarshals raw into the LegacyFilters input type, as graphql.UnmarshalNamedInputFromContext does.
func UnmarshalLegacyFilters(ctx context.Context, raw any) (out *LegacyFilters, err error) {
	err = graphql.UnmarshalNamedInputFromContext(ctx, "LegacyFilters", raw, &out)
	return out, err
}

// UnmarshalSearchFilters unmarshals raw into the SearchFilters input type, as graphql.UnmarshalNamedInputFromContext does.
func UnmarshalSearchFilters(ctx context.Context, raw any) (out *SearchFilters, err error) {
	err = graphql.UnmarshalNamedInputFromContext(ctx, "SearchFilters", raw, &out)
	return out, err
}

func (t *tables) initObjectQuery() {
	t.objectQuery.Init(t.schema, "Query", _Query_resolve, []tableField{
		{Name: "search", IsResolver: true, Args: []any{t.inUnmarshalNSearchFilters2returnpointersinunmarshalinputᚐSearchFilters.In}, Out: t.marshalNString2string.Out},
		{Name: "legacy", IsResolver: true, Args: []any{t.inUnmarshalNLegacyFilters2returnpointersinunmarshalinputᚐLegacyFilters.In}, Out: t.marshalNString2string.Out},
		{Name: "checkedInput", IsResolver: true, Args: []any{t.inUnmarshalOCheckedInput2ᚖreturnpointersinunmarshalinputᚐCheckedInput.In}, Out: t.marshalNString2string.Out},
		{Name: "__type", IsMethod: true, Args: []any{t.unmarshalNString2string.In}, Type: (**introspection.Type)(nil)},
		{Name: "__schema", IsMethod: true, Type: (**introspection.Schema)(nil)},
	})
	t.inputLegacyFilters.Init(t.schema, exec.Input[*executionContext]{Name: "LegacyFilters", GoType: "LegacyFilters", Type: reflect.TypeOf((*LegacyFilters)(nil)).Elem(), Pointer: true, Set: _LegacyFilters_set}, []tableInputField{
		{Name: "name", In: t.unmarshalOString2ᚖstring.In},
	})
	t.inputSearchFilters.Init(t.schema, exec.Input[*executionContext]{Name: "SearchFilters", GoType: "SearchFilters", Type: reflect.TypeOf((*SearchFilters)(nil)).Elem(), Pointer: true, Set: _SearchFilters_set}, []tableInputField{
		{Name: "name", In: t.unmarshalOString2ᚖstring.In},
		{Name: "limit", In: t.unmarshalOInt2ᚖint.In},
	})
}

func _Query_resolve(ctx context.Context, ec *executionContext, _ any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	switch fieldIndex {
	case 0:
		return ec.Resolvers.Query().Search(ctx, fieldArgs["filters"].(SearchFilters))
	case 1:
		return ec.Resolvers.Query().Legacy(ctx, fieldArgs["filters"].(LegacyFilters))
	case 2:
		return ec.Resolvers.Query().CheckedInput(ctx, fieldArgs["input"].(*CheckedInput))
	case 3:
		return ec.IntrospectType(fieldArgs["name"].(string))
	case 4:
		return ec.IntrospectSchema()
	}
	return nil, exec.NoField(fieldIndex)
}

func _LegacyFilters_set(inputValue any, fieldIndex int, v any) {
	p := inputValue.(*LegacyFilters)
	switch fieldIndex {
	case 0:
		p.Name, _ = v.(*string)
	}
}

func _SearchFilters_set(inputValue any, fieldIndex int, v any) {
	p := inputValue.(*SearchFilters)
	switch fieldIndex {
	case 0:
		p.Name, _ = v.(*string)
	case 1:
		p.Limit, _ = v.(*int)
	}
}

func unmarshalNLegacyFilters2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋreturnpointersinunmarshalinputᚐLegacyFilters(ctx context.Context, ec *executionContext, v any) (LegacyFilters, error) {
	res, err := exec.InputPointer[*executionContext, LegacyFilters](ctx, ec, &ec.tables.inputLegacyFilters, v)
	return *res, graphql.ErrorOnPath(ctx, err)
}

func unmarshalNSearchFilters2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋreturnpointersinunmarshalinputᚐSearchFilters(ctx context.Context, ec *executionContext, v any) (SearchFilters, error) {
	res, err := exec.InputPointer[*executionContext, SearchFilters](ctx, ec, &ec.tables.inputSearchFilters, v)
	return *res, graphql.ErrorOnPath(ctx, err)
}
