//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package childfielddedup

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
	"github.com/99designs/gqlgen/graphql/introspection"
)

func (t *tables) initObject__Directive() {
	t.object__Directive.Init(t.schema, "__Directive", ___Directive_resolve, []tableField{
		{Name: "name", Out: t.marshalNString2string.Out},
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "isRepeatable", Out: t.marshalNBoolean2bool.Out},
		{Name: "locations", Out: t.marshalN__DirectiveLocation2ᚕstringᚄ},
		{Name: "args", Args: []any{t.unmarshalOBoolean2ᚖbool.In}, Out: t.marshalN__InputValue2ᚕintrospectionᚐInputValueᚄ},
	})
	t.object__EnumValue.Init(t.schema, "__EnumValue", ___EnumValue_resolve, []tableField{
		{Name: "name", Out: t.marshalNString2string.Out},
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "isDeprecated", IsMethod: true, Out: t.marshalNBoolean2bool.Out},
		{Name: "deprecationReason", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
	})
	t.object__Field.Init(t.schema, "__Field", ___Field_resolve, []tableField{
		{Name: "name", Out: t.marshalNString2string.Out},
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "args", Args: []any{t.unmarshalOBoolean2ᚖbool.In}, Out: t.marshalN__InputValue2ᚕintrospectionᚐInputValueᚄ},
		{Name: "type", Type: (**introspection.Type)(nil)},
		{Name: "isDeprecated", IsMethod: true, Out: t.marshalNBoolean2bool.Out},
		{Name: "deprecationReason", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
	})
}

func ___Directive_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.Directive)
	switch fieldIndex {
	case 0:
		var v string = obj.Name
		return v, nil
	case 1:
		var v *string = obj.Description()
		return v, nil
	case 2:
		var v bool = obj.IsRepeatable
		return v, nil
	case 3:
		var v []string = obj.Locations
		return v, nil
	case 4:
		var v []introspection.InputValue = obj.Args
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func ___EnumValue_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.EnumValue)
	switch fieldIndex {
	case 0:
		var v string = obj.Name
		return v, nil
	case 1:
		var v *string = obj.Description()
		return v, nil
	case 2:
		var v bool = obj.IsDeprecated()
		return v, nil
	case 3:
		var v *string = obj.DeprecationReason()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func ___Field_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.Field)
	switch fieldIndex {
	case 0:
		var v string = obj.Name
		return v, nil
	case 1:
		var v *string = obj.Description()
		return v, nil
	case 2:
		var v []introspection.InputValue = obj.Args
		return v, nil
	case 3:
		var v *introspection.Type = obj.Type
		return v, nil
	case 4:
		var v bool = obj.IsDeprecated()
		return v, nil
	case 5:
		var v *string = obj.DeprecationReason()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func (t *tables) initObject__InputValue() {
	t.object__InputValue.Init(t.schema, "__InputValue", ___InputValue_resolve, []tableField{
		{Name: "name", Out: t.marshalNString2string.Out},
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "type", Type: (**introspection.Type)(nil)},
		{Name: "defaultValue", Out: t.marshalOString2ᚖstring.Out},
		{Name: "isDeprecated", IsMethod: true, Out: t.marshalNBoolean2bool.Out},
		{Name: "deprecationReason", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
	})
	t.object__Schema.Init(t.schema, "__Schema", ___Schema_resolve, []tableField{
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "types", IsMethod: true, Out: t.marshalN__Type2ᚕintrospectionᚐTypeᚄ},
		{Name: "queryType", IsMethod: true, Type: (**introspection.Type)(nil)},
		{Name: "mutationType", IsMethod: true, Type: (**introspection.Type)(nil)},
		{Name: "subscriptionType", IsMethod: true, Type: (**introspection.Type)(nil)},
		{Name: "directives", IsMethod: true, Out: t.marshalN__Directive2ᚕintrospectionᚐDirectiveᚄ},
	})
}

func ___InputValue_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.InputValue)
	switch fieldIndex {
	case 0:
		var v string = obj.Name
		return v, nil
	case 1:
		var v *string = obj.Description()
		return v, nil
	case 2:
		var v *introspection.Type = obj.Type
		return v, nil
	case 3:
		var v *string = obj.DefaultValue
		return v, nil
	case 4:
		var v bool = obj.IsDeprecated()
		return v, nil
	case 5:
		var v *string = obj.DeprecationReason()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func ___Schema_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.Schema)
	switch fieldIndex {
	case 0:
		var v *string = obj.Description()
		return v, nil
	case 1:
		var v []introspection.Type = obj.Types()
		return v, nil
	case 2:
		var v *introspection.Type = obj.QueryType()
		return v, nil
	case 3:
		var v *introspection.Type = obj.MutationType()
		return v, nil
	case 4:
		var v *introspection.Type = obj.SubscriptionType()
		return v, nil
	case 5:
		var v []introspection.Directive = obj.Directives()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}

func (t *tables) initObject__Type() {
	t.object__Type.Init(t.schema, "__Type", ___Type_resolve, []tableField{
		{Name: "kind", IsMethod: true, Out: t.marshalN__TypeKind2string.Out},
		{Name: "name", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "description", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "specifiedByURL", IsMethod: true, Out: t.marshalOString2ᚖstring.Out},
		{Name: "fields", IsMethod: true, Args: []any{t.unmarshalOBoolean2bool.In}, Out: t.marshalO__Field2ᚕintrospectionᚐFieldᚄ},
		{Name: "interfaces", IsMethod: true, Out: t.marshalO__Type2ᚕintrospectionᚐTypeᚄ},
		{Name: "possibleTypes", IsMethod: true, Out: t.marshalO__Type2ᚕintrospectionᚐTypeᚄ},
		{Name: "enumValues", IsMethod: true, Args: []any{t.unmarshalOBoolean2bool.In}, Out: t.marshalO__EnumValue2ᚕintrospectionᚐEnumValueᚄ},
		{Name: "inputFields", IsMethod: true, Args: []any{nil}, Out: t.marshalO__InputValue2ᚕintrospectionᚐInputValueᚄ},
		{Name: "ofType", IsMethod: true, Type: (**introspection.Type)(nil)},
		{Name: "isOneOf", IsMethod: true, Out: t.marshalOBoolean2bool.Out},
	})
}

func ___Type_resolve(ctx context.Context, ec *executionContext, o any, fieldIndex int, fieldArgs map[string]any) (any, error) {
	obj := o.(*introspection.Type)
	switch fieldIndex {
	case 0:
		var v string = obj.Kind()
		return v, nil
	case 1:
		var v *string = obj.Name()
		return v, nil
	case 2:
		var v *string = obj.Description()
		return v, nil
	case 3:
		var v *string = obj.SpecifiedByURL()
		return v, nil
	case 4:
		return obj.Fields(fieldArgs["includeDeprecated"].(bool)), nil
	case 5:
		var v []introspection.Type = obj.Interfaces()
		return v, nil
	case 6:
		var v []introspection.Type = obj.PossibleTypes()
		return v, nil
	case 7:
		return obj.EnumValues(fieldArgs["includeDeprecated"].(bool)), nil
	case 8:
		var v []introspection.InputValue = obj.InputFields()
		return v, nil
	case 9:
		var v *introspection.Type = obj.OfType()
		return v, nil
	case 10:
		var v bool = obj.IsOneOf()
		return v, nil
	}
	return nil, exec.NoField(fieldIndex)
}
