//go:build exectable

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package childfielddedup

import (
	"context"

	"github.com/99designs/gqlgen/graphql/exec"
)

// region    ************************** generated!.gotpl **************************

type InvoiceResolver interface {
	CreatedBy(ctx context.Context, obj *Invoice) (*User, error)
	ApprovedBy(ctx context.Context, obj *Invoice) (*User, error)
}
type QueryResolver interface {
	Book(ctx context.Context, id string) (*Book, error)
	Article(ctx context.Context, id string) (*Article, error)
	Review(ctx context.Context, id string) (*Review, error)
	Comment(ctx context.Context, id string) (*Comment, error)
	Task(ctx context.Context, id string) (*Task, error)
	Invoice(ctx context.Context, id string) (*Invoice, error)
}

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    **************************** field.gotpl *****************************

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var objectArticle = exec.Object[*executionContext]{Name: "Article", Implementors: []string{"Article"}}

func init() {
	objectArticle.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *Article) string { return obj.ID }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "headline", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *Article) string { return obj.Headline }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "author", NonNull: true, Children: &objectAuthor}, outMarshalNAuthor2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐAuthor, func(obj *Article) *Author { return obj.Author }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "assignee", Children: &objectUser}, outMarshalOUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐUser, func(obj *Article) *User { return obj.Assignee }),
	})
}

var objectAuthor = exec.Object[*executionContext]{Name: "Author", Implementors: []string{"Author"}}

func init() {
	objectAuthor.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *Author) string { return obj.ID }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *Author) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "email", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *Author) string { return obj.Email }),
	})
}

var objectBook = exec.Object[*executionContext]{Name: "Book", Implementors: []string{"Book"}}

func init() {
	objectBook.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *Book) string { return obj.ID }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "title", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *Book) string { return obj.Title }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "author", NonNull: true, Children: &objectAuthor}, outMarshalNAuthor2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐAuthor, func(obj *Book) *Author { return obj.Author }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "reviewer", Children: &objectUser}, outMarshalOUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐUser, func(obj *Book) *User { return obj.Reviewer }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "editor", Children: &objectUser}, outMarshalOUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐUser, func(obj *Book) *User { return obj.Editor }),
	})
}

var objectComment = exec.Object[*executionContext]{Name: "Comment", Implementors: []string{"Comment"}}

func init() {
	objectComment.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *Comment) string { return obj.ID }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "text", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *Comment) string { return obj.Text }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "commenter", NonNull: true, Children: &objectUser}, outMarshalNUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐUser, func(obj *Comment) *User { return obj.Commenter }),
	})
}

var objectInvoice = exec.Object[*executionContext]{Name: "Invoice", Implementors: []string{"Invoice"}}

func init() {
	objectInvoice.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *Invoice) string { return obj.ID }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "total", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *Invoice) string { return obj.Total }),
		{Name: "createdBy", NonNull: true, Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectUser, Out: outMarshalNUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐUser.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Invoice().CreatedBy(ctx, obj.(*Invoice))
		}},
		{Name: "approvedBy", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectUser, Out: outMarshalOUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐUser.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Invoice().ApprovedBy(ctx, obj.(*Invoice))
		}},
	})
}

var objectQuery = exec.Object[*executionContext]{Name: "Query", Implementors: []string{"Query"}, Root: true}

func init() {
	objectQuery.Init([]exec.Field[*executionContext]{
		{Name: "book", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectBook, Args: []exec.Arg[*executionContext]{
			{Name: "id", Type: inUnmarshalNID2string.In},
		}, Out: outMarshalOBook2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐBook.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Book(ctx, args["id"].(string))
		}},
		{Name: "article", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectArticle, Args: []exec.Arg[*executionContext]{
			{Name: "id", Type: inUnmarshalNID2string.In},
		}, Out: outMarshalOArticle2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐArticle.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Article(ctx, args["id"].(string))
		}},
		{Name: "review", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectReview, Args: []exec.Arg[*executionContext]{
			{Name: "id", Type: inUnmarshalNID2string.In},
		}, Out: outMarshalOReview2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐReview.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Review(ctx, args["id"].(string))
		}},
		{Name: "comment", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectComment, Args: []exec.Arg[*executionContext]{
			{Name: "id", Type: inUnmarshalNID2string.In},
		}, Out: outMarshalOComment2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐComment.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Comment(ctx, args["id"].(string))
		}},
		{Name: "task", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectTask, Args: []exec.Arg[*executionContext]{
			{Name: "id", Type: inUnmarshalNID2string.In},
		}, Out: outMarshalOTask2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐTask.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Task(ctx, args["id"].(string))
		}},
		{Name: "invoice", Concurrent: true, IsMethod: true, IsResolver: true, Children: &objectInvoice, Args: []exec.Arg[*executionContext]{
			{Name: "id", Type: inUnmarshalNID2string.In},
		}, Out: outMarshalOInvoice2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐInvoice.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.Resolvers.Query().Invoice(ctx, args["id"].(string))
		}},
		{Name: "__type", IsMethod: true, Children: &object__Type, Args: []exec.Arg[*executionContext]{
			{Name: "name", Type: inUnmarshalNString2string.In},
		}, Out: outMarshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.IntrospectType(args["name"].(string))
		}},
		{Name: "__schema", IsMethod: true, Children: &object__Schema, Out: outMarshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema.Out, Resolve: func(ctx context.Context, ec *executionContext, obj any, args map[string]any) (any, error) {
			return ec.IntrospectSchema()
		}},
	})
}

var objectReview = exec.Object[*executionContext]{Name: "Review", Implementors: []string{"Review"}}

func init() {
	objectReview.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *Review) string { return obj.ID }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "body", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *Review) string { return obj.Body }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "author", NonNull: true, Children: &objectAuthor}, outMarshalNAuthor2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐAuthor, func(obj *Review) *Author { return obj.Author }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "moderator", Children: &objectUser}, outMarshalOUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐUser, func(obj *Review) *User { return obj.Moderator }),
	})
}

var objectTask = exec.Object[*executionContext]{Name: "Task", Implementors: []string{"Task"}}

func init() {
	objectTask.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *Task) string { return obj.ID }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "title", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *Task) string { return obj.Title }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "assignee", NonNull: true, Children: &objectUser}, outMarshalNUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐUser, func(obj *Task) *User { return obj.Assignee }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "reporter", Children: &objectUser}, outMarshalOUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐUser, func(obj *Task) *User { return obj.Reporter }),
	})
}

var objectUser = exec.Object[*executionContext]{Name: "User", Implementors: []string{"User"}}

func init() {
	objectUser.Init([]exec.Field[*executionContext]{
		exec.FieldGet(exec.Field[*executionContext]{Name: "id", NonNull: true, Leaf: "ID"}, outMarshalNID2string, func(obj *User) string { return obj.ID }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "name", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *User) string { return obj.Name }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "email", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *User) string { return obj.Email }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "phone", Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *User) *string { return obj.Phone }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "avatar", Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *User) *string { return obj.Avatar }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "role", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *User) string { return obj.Role }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "status", NonNull: true, Leaf: "String"}, outMarshalNString2string, func(obj *User) string { return obj.Status }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "language", Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *User) *string { return obj.Language }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "timezone", Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *User) *string { return obj.Timezone }),
		exec.FieldGet(exec.Field[*executionContext]{Name: "createdAt", Leaf: "String"}, outMarshalOString2ᚖstring, func(obj *User) *string { return obj.CreatedAt }),
	})
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

var marshalNAuthor2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐAuthor = exec.MarshalObjectPtr[*executionContext, Author](true, &objectAuthor)

var marshalNUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐUser = exec.MarshalObjectPtr[*executionContext, User](true, &objectUser)

var marshalOArticle2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐArticle = exec.MarshalObjectPtr[*executionContext, Article](false, &objectArticle)

var marshalOBook2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐBook = exec.MarshalObjectPtr[*executionContext, Book](false, &objectBook)

var marshalOComment2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐComment = exec.MarshalObjectPtr[*executionContext, Comment](false, &objectComment)

var marshalOInvoice2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐInvoice = exec.MarshalObjectPtr[*executionContext, Invoice](false, &objectInvoice)

var marshalOReview2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐReview = exec.MarshalObjectPtr[*executionContext, Review](false, &objectReview)

var marshalOTask2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐTask = exec.MarshalObjectPtr[*executionContext, Task](false, &objectTask)

var marshalOUser2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋchildfielddedupᚐUser = exec.MarshalObjectPtr[*executionContext, User](false, &objectUser)

// endregion ***************************** type.gotpl *****************************
