//go:generate go run ../../../testdata/gqlgen.go -config gqlgen.yml -stub stub.go

package embedschema

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/99designs/gqlgen/client"
	"github.com/99designs/gqlgen/codegen/testserver/embedschema/generated"
	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/handler/transport"
)

// The schema files of this server lie outside the directory of the generated code, which
// embeds the copies that exec.embed_schema_dir makes of them.

func TestSchemaCopies(t *testing.T) {
	notice := "# Code generated by github.com/99designs/gqlgen, DO NOT EDIT.\n\n"
	for _, name := range []string{"schema/schema.graphql", "schema/shared/types.graphql"} {
		content, err := os.ReadFile(filepath.Join("generated", name))
		require.NoError(t, err)
		// A checkout on Windows may have changed the line endings of the copies.
		text := strings.ReplaceAll(string(content), "\r\n", "\n")
		require.True(t, strings.HasPrefix(text, notice), name)
	}

	root, err := os.ReadFile(filepath.Join("generated", "root_.generated.go"))
	require.NoError(t, err)
	require.Contains(
		t,
		string(root),
		`//go:embed "schema/schema.graphql" "schema/shared/types.graphql"`,
	)
	require.NotContains(t, string(root), "type Greeting {")
}

func TestEmbeddedSchema(t *testing.T) {
	resolvers := &Stub{}
	resolvers.QueryResolver.Greeting = func(
		_ context.Context,
		name string,
	) (*generated.Greeting, error) {
		return &generated.Greeting{Text: "hello " + name}, nil
	}
	srv := handler.New(generated.NewExecutableSchema(generated.Config{Resolvers: resolvers}))
	srv.AddTransport(transport.POST{})
	c := client.New(srv)

	var resp struct{ Greeting struct{ Text string } }
	c.MustPost(`{ greeting(name: "gqlgen") { text } }`, &resp)
	require.Equal(t, "hello gqlgen", resp.Greeting.Text)
}
