// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package embedschema

import (
	"context"

	"github.com/99designs/gqlgen/codegen/testserver/embedschema/generated"
)

type Stub struct {
	QueryResolver struct {
		Greeting func(ctx context.Context, name string) (*generated.Greeting, error)
	}
}

func (r *Stub) Query() generated.QueryResolver {
	return &stubQuery{r}
}

type stubQuery struct{ *Stub }

func (r *stubQuery) Greeting(ctx context.Context, name string) (*generated.Greeting, error) {
	return r.QueryResolver.Greeting(ctx, name)
}
