// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package nullargdirectives

import (
	"context"
)

type Stub struct {
	QueryResolver struct {
		Echo func(ctx context.Context, arg *string) (*string, error)
	}
}

func (r *Stub) Query() QueryResolver {
	return &stubQuery{r}
}

type stubQuery struct{ *Stub }

func (r *stubQuery) Echo(ctx context.Context, arg *string) (*string, error) {
	return r.QueryResolver.Echo(ctx, arg)
}
